### ISSUE TITLE
Journeymap becoming transparent

### ISSUE THREAD

**Issue by garrarq** [Haggle1996/RevolutionPack#10]
I'm having problems with Journeymap unlimited. I have every recommended mod installed except for Journeymap Fairplay. The causes of the map becoming transparent are inconsistent. The map becomes opaque again after breaking a block, but sometimes goes right back to being transparent. All the Journeymap settings are on default.

![2015-04-26_21 54 41](https://cloud.githubusercontent.com/assets/12194482/7426431/080e0352-ef82-11e4-8cca-85bd2a5c46bf.png)

**Comment by Haggle1996** [comment]
Can you provide some specifics on your configuration? I cannot replicate this consistently on my end -- it only ever happens (briefly) when I change dimensions or load the game. After combing through the forums, I can't find anyone with a similar issue. Brand of video card? Processor speed and memory? Drivers up to date? From the screen, it looks like you have view distance set really low.

**Comment by Haggle1996** [comment]
Closing
