### ISSUE TITLE
Creosote Oil Unusable In Wooden Tie Recipe

### ISSUE THREAD

**Issue by viperior** [Haggle1996/RevolutionPack#100]
I am trying to craft a Railcraft "Wooden Tie".
I loaded several stacks of logs into a Coke Oven and got plenty of Creosote Oil.
I right-click on the coke oven with a Minecraft Bucket (item 325, vanilla).
It gives me "Bucket of Creosote Oil 5984:1" and is labeled as coming from the mod, "Immersive Engineering".
I then try to use this to craft a Railcraft "Wooden Tie" using the NEI recipe and a recipe I found online.
Neither recipe seems to work using this oil, and the recipe in-game shows the Railcraft version of Creosote bucket (item 5111 from Railcraft).

If the Shaped Crafting recipe for Wooden Tie is intended to be functional, it needs to be able to take the Immersive Engineering version of Creosote Oil, because that is what you get when you scoop oil out of a Coke Oven.

**Comment by Haggle1996** [comment]
You must use a Carpenter to craft ties. 

HARD mode recipes are enabled for RailCraft, but due to a bug in the mod, the EASY mode recipes for ties still show up in NEI (in addition to the hardmode ones). Filling a Carpenter with either RailCraft or Immersive Engineering creosote works fine.

**Comment by viperior** [comment]
I suspected that might be the case! Since it seems to behave normally as a liquid, I thought the pack required the harder way of using the Carpenter. I wasn't sure if that would just be a workaround or the intentional way, but thank you for clarifying that it is intentional. That might make a good item to have in the pack Wiki, in case other players get confused over the same issue.

**Comment by Haggle1996** [comment]
Yes, I'll get it added to the guide.. Thanks for the comment, these kinds of things are helpful to point out.

**Comment by romanticjo** [comment]
I was able to craft ties with creosote bottle directly, no carpenter required. Expected?
