### ISSUE TITLE
Induction Matrix Block + AE2 Crafting terminal = client crash

### ISSUE THREAD

**Issue by Yuri4171** [Haggle1996/RevolutionPack#102]
Placing a Mekanism Induction matrix block inside the crafting grid of an AE2 crafting terminal crashes the client.
New info: a regular crafting table also triggers the crash.

Crashlog using AE2:
http://pastebin.com/wGeekAxZ
Crashlog using vanilla crafting table:
http://pastebin.com/CKc0mNQx

**Comment by Haggle1996** [comment]
aidancbrady/Mekanism#2938

**Comment by Haggle1996** [comment]
In the short term, cheat in the component you're trying to craft. I'll look into the minetweaker fix and if it works, add it to the next version.
