### ISSUE TITLE
Help for launching Revolution server.

### ISSUE THREAD

**Issue by bick88** [Haggle1996/RevolutionPack#105]
I have been trying to launch a server with some friends for a month ; I have downloaded the instance Revolution server from ATlauncher, I started it on our server but it cannot be played because the game lags terribly. As I am not used to Forge, I wanted to make a Cauldron server, which does not exist anymore and has been replaced by Kcauldron. The server works very well but lots of mods are incompatible.
To avoid removing all incompatible mods I went back to Forge. After one week search I saw that it is possible to launch Forge with JVM arguments. I managed to create those : -Xmn2G -Xss4M -Xms6G -Xmx20G -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10 -Djava.net.preferIPv4Stack=true

But even then, and a pregen spawner with a 150 radius, I cannot manage to play.
I saw that the server on Youtube with SentinalMC works under Revolution, I would like to know how you did it... Please help me I am desperate!!!

**Comment by bick88** [comment]
With Kcauldron, I installed on the server the compatible version with the Revolution instance (Forge 1448), but it had a conflict with Dragon API. So I tried with the Kcauldron 1492.155 version and the server launched but there was a big problem with Flans mod that provoked major display bugs but still allowed to play.
There were also crashes because of Zombie awareness. 

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 27/09/15 22:30
Description: Exception in server tick loop

java.lang.IndexOutOfBoundsException
	at kcauldron.wrapper.LinkedHelper.get(LinkedHelper.java:27)
	at kcauldron.wrapper.QueueToList.get(QueueToList.java:30)
	at ZombieAwareness.ZombieAwareness.worldTick(ZombieAwareness.java:218)
	at ZombieAwareness.ZombieAwareness.onTickInGame(ZombieAwareness.java:185)
	at ZombieAwareness.ZombieAwareness.onTick(ZombieAwareness.java:157)
	at ZombieAwareness.ZAEventHandlerFML.tickServer(ZAEventHandlerFML.java:19)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_933_ZAEventHandlerFML_tickServer_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:797)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

I hope this helps you help me.

**Comment by Haggle1996** [comment]
KCauldron is not supported for this pack, and that's not something I have the power to change. As you discovered, there are way too many mod incompatibilities, with new ones popping up with every new mod or kcauldron release.

That said, the server should run fine with standard Forge, for 5-10 simultaneous players on typical server hardware. You can eke out 15 on great hardware (SSD + Great Processor). I run with very simple java optimizations, only specifying the maximum memory. On the development server (where SentinalH plays), I have maximum memory capped at 8GB. The pack typically hovers around 3.5 - 4 GBs of used RAM, unless people are generating chunks (or there's lot of people online). Dedicating more than 6 or 8GB of RAM generally causes issues more issues than its worth. I only recommend you increase RAM if you're frequently getting out of RAM issues during normal gameplay (not during world generation).

Without knowing the details, here's some general tips for server performance:

1. Run on good hardware. The pack runs great with 4-8GB of RAM supporting 10-15 simultaneous players, assuming a good CPU and SSDs. During the early days of the server (before too much automation), the pack generally performs well with 20-25.
2. Make sure you pregenerate the overworld. Using ATG world type, it is not uncommon for the server to crash a few times during world generation with a concurrent modification exception. Restart the server and continue generation. It is also not uncommon to run out of heap space -- world gen is memory-expensive in this pack. Again, restart the server and continue generation.
3. Pregenerate at least the Twilight Forest, Moon, Mars, and Nether. The other dimensions are relatively inexpensive to generate if a player stumbles into them.
4. The ForgeEssentials /filler command works significantly better than AdminCommandsToolbox /pregenspawn I recommend for single-player.
5.. Use Java 8, if possible
6. BIOMESOP world type is significantly better than ATG for performance -- much less data to transfer over the wire -- but you lose out on some of the terrain uniqueness.
7. Run Opis and periodically check for expensive chunks -- usually its things like players having 200 chickens, etc.
8. Restart the server at least once per day -- extremely busy servers should consider 2 to 4 times daily.
9. Warn players against using the following blocks which are very hard on TPS (I use ForgeEssentials TimedMessage chat facility on the dev server): RotaryCraft Solar Towers, Steve's Workshop Tables (for autocrafting), Vanilla Hoppers.
10. Placing Stefinus 3D Guns into the hands of Statues mod statues will crash the server. It's the only known crashbug at the moment. Again, I warn players in my TimedMessage. You could optionally remove the Statues mod from the server -- it's for decoration only.
11. Take regular backups. While the pack is very stable, we've inevitably had a couple of problems that we're much easier to resolve by rolling back to the last backup.
12. ReactorCraft reactors behave badly when they cross loaded/unloaded chunk boundaries -- meaning they tend to blow up and irradiate the area around them. In the past, I made players run their own world anchors (which require fuel) to avoid this. However, we ran into trouble with players taking a break and their reactors blowing up. The solution I use now is to place an Admin Anchor over a nuclear reactor on behalf of the player. If you're okay with world destruction, then you can safely skip this.
13. Regularly regenerate the Twilight Forest or a mining world that has mines. There are not enough sources of ChromatiCraft fragments to support more than a couple of players pursuing research. Regenerating TF or a mining world (something with loot chests) on a regular basis opens up fragment finding for many more players. I backed up my initial generation of TF and just restore it every couple of weeks.

**Comment by bick88** [comment]
I use a dedicated server with Xenon E3-1245 V2 and 32Gb of ram. The server works on linux with debian 7 and java 8. It's too bad the moders no longer conceive their mods for Kcauldron but only for forge. 
On the previous server based on the Beyond reality instance, there was no trouble with up to ten players and I only rebooted the server once a week. 
I know a lot about Kcauldron, would you like to work together to make the instance work with kcauldron?

**Comment by Haggle1996** [comment]
I'm happy to help if you want to make the effort, but I don't have much time available to devote at this juncture. If you are able to get it working, I will add it to our pack guidance.

-----Original Message-----
