### ISSUE TITLE
Inventory Visuals

### ISSUE THREAD

**Issue by QuantumBolt** [Haggle1996/RevolutionPack#111]
Whenever I hover over an item in my inventory the metadata, unlocalized names etc. appear. How do I turn this function off?

**Comment by Haggle1996** [comment]
There are a couple of ways this can get added; perchance can you post a screenshot so I can give you the correct fix?

**Comment by QuantumBolt** [comment]
I've no idea if I'm uploading correctly, but here's a link to imgur http://i.imgur.com/qG07NXD.png

**Comment by Haggle1996** [comment]
Hmm. This is none of the ways I know to add tooltips -- let me figure out where this came from. Thanks for uploading the screenshot.

**Comment by Rearth** [comment]
i had this Problem also, try pressing f3 + h while ingame, but not while you are in the inventory. Should fix it.
http://minecraft.gamepedia.com/Debug_screen#More_debug-keys

**Comment by Haggle1996** [comment]
Ooo...I wonder if I can force this off with the KeyConfig & Options mod

**Comment by Haggle1996** [comment]
As Rearth commented, this is fixed by F3+H. It's my fault -- I included the options.txt file in the pack configuration.
