### ISSUE TITLE
Tps problem

### ISSUE THREAD

**Issue by thebakker** [Haggle1996/RevolutionPack#113]
My tps in this modpack is very bad (3-5) instead of 20, is it a mod that gives a memory leak or something? i use version 1.2.2.0. 
I know that the problem is not my pc, because other modpacks (with more mods) don't lag as much as this one

**Comment by Haggle1996** [comment]
Make sure you've followed the performance section of the first day guide, located here: http://haggle1996.github.io/RevolutionPack/articles/your-first-day/

If this is an established world (you've been playing on it for a while and its slowly gotten laggier and laggier), you may want to add the optional Opis mod and use it to figure out what block(s) are causing the TPS lag.

If its a new world, and you've followed the performance/pregeneration tips in the first day guide, you'll need to zip up a log file so I can take a look at white might be eating up TPS. That said, this is a 'heavy' pack in comparison to packs like Sky Factory 2 -- it doesn't run well on older/slower hardware.

**Comment by thebakker** [comment]
http://paste.atlauncher.com/view/c78db70b
this is the log. It is a new world.
I tried to do that command, but afterwards i can't even start my world.
It is not my pc, because i can run dns techpack without problem, but i found this modpack and this one looked cooler.
