### ISSUE TITLE
Kcauldron server works but we have a problem

### ISSUE THREAD

**Issue by bick88** [Haggle1996/RevolutionPack#114]
Hi, I finally managed to make the instance Revolution work with Kcauldron, including all mods except ZombieAwareness that is not compatible with Kcauldron.
I pre-generated the world without any trouble but when I started playing I realized there were several issues that in my opinion come from the same source. 
It consists of a slowing down of liquid sources, the falling of blocks subject to gravity and redstone. 
I am going to share this problem on the Kcauldron forum,
http://tcpr.ca/forums/discussion/154/liquid-source-falling-of-blocks-and-redstone/p1

 I enclose a video to show you the problems.
https://www.youtube.com/watch?v=YcuXTWLLhzk&feature=youtu.be

I have been looking everywhere but I cannot seem to find the origin of those issues.

**Comment by Haggle1996** [comment]
Thanks for working with this. I'll keep an eye out on your forum post, in case it's resolved.
