### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by Caprikachu** [Haggle1996/RevolutionPack#118]
So I've been playing the Revolution pack for a few weeks and I have been plagued with constant crashing from the beginning.  At times it would work, for hours, or not at all. The crashes usually happen when I interact with something like my inventory or a chest. As of today I have not been able to log in for more than ten minutes without it crashing on me. I have tried uninstalling and reinstalling both Java and the launcher as well as the instance pack itself. I've tried messing with the RAM settings and allocating more to the game. I just don't know what to do any more. I'm getting frustrated and I would just like to play.

**Comment by Haggle1996** [comment]
I need a copy of your crash log from your <instance>/crash-reports folder. Paste it into pastebin.com and I can take a look.

**Comment by Haggle1996** [comment]
You've been added to the server. Welcome aboard!

We have only 3 rules on the server:
1). Absolutely no griefing is tolerated (this includes entering/stealing
from other players/bases without permission)
2). Please act like an adult, even if you aren't one.
3). Obey the admins

The server IP address is: 45.58.126.98:25565 -- Please Select Recommended
in the launcher, then REMOVE Animals+ and SpecialAI

Type '/kit starter' to receive your starter kit, containing basic materials
to make tinker's flint tools, and most importantly, a sleeping bag.

It's not safe to wander at night before you get settled on the server, so
either sleep it off or hide. Once you find a nice starting location, type
'/home set' to set your respawn point. You can also type '/home' at any
time to return to this point. '/spawn' will return you to the world spawn,
and '/back' will return you to your dead body (or back to wherever you
teleported from last).

Please note that the area immediately around spawn is crowded. Use one of
the /warp destinations to move to a fresh area (/warp list to list them).
Also note, that if there are no plants or flowers in a given biome, it will
have minimal ore underground.

The world border extends out to 10,000 blocks around spawn.

If you haven't already, be sure to check out the following to articles:
http://haggle1996.github.io/RevolutionPack/articles/game-changes/
http://haggle1996.github.io/RevolutionPack/articles/your-first-day/

Have fun and welcome to the server!
-Haggle1996

**Comment by Caprikachu** [comment]
Please forgive my ignorance, but would that be in the console? I don't know where I'd find the crash log.

**Comment by Haggle1996** [comment]
In the ATLauncher instances list, find your Revolution instance. Click the
'Open Folder' button to the bottom right of the Play button. This should
open up a window containing all the files that make up your Revolution
instance. One of the folders in this view should be labeled
'crash-reports'. Inside this folder will be all the crash reports generated
when Revolution crashes. Open the most recent one and copy/paste it into
pastebin.com

**Comment by Caprikachu** [comment]
There isnt a crash reports folder in my revolution folder. I've gone up and down the list.

**Comment by Caprikachu** [comment]
I also reinstalled again and changed my map mod from journey map to opis and that allowed me to stay in the game a bit longer, or it was coincidence. I figured it was worth mentioning.

**Comment by Haggle1996** [comment]
Without a log, I can't do too much to troubleshoot this...however, Minecraft only generates a crash reports folder if the crash was caused by Minecraft, versus something higher up the chain (the Java Virtual Machine which hosts Minecraft or your graphics adapter are examples). Make sure you're running Java 1.8 and that your video card drivers are up to date -- those are common sources of crashes that don't generate a log.

Another alternative we have is for you to run minecraft as normal until it crashes, then, at the ATLauncher console, click 'Upload Log'. This will upload your log to the ATLauncher site, and copy the URL to your paste buffer (just press CTRL+V on a PC to paste it into a text window). Put that link here and maybe it will shed a bit more light on the problem.

**Comment by Caprikachu** [comment]
Ok. I'll do that. :3 And perhaps it is a Java problem, but I've uninstalled and reinstalled java like a million times.

**Comment by Benedikt20** [comment]
The same Thing happens by me. Very often when I open a furnace, my Inventory or something like that Minecraft crashes. Here is the link to the Crash Report: http://pastebin.com/bjxsw35B

**Comment by Haggle1996** [comment]
I don't think your problems are related, but a crashlog is worth a thousand words, so to speak. In your case, @Benedikt20 you need to turn off Torch Assist in your Zyin's HUD. This is off by default in the pack, but somehow you've got yours turned on.

**Comment by Benedikt20** [comment]
Thank you so much Haggle1996 i was realy upset about this crashes.
