### ISSUE TITLE
Chromaticraft crash?

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#119]
https://gist.github.com/romanticjo/d9bd487a00cc6536490f

Happened while mining a chromaticraft block.

**Comment by romanticjo** [comment]
Reproduceable.  Mining chromaticraft block with water flowing over it:

https://gist.github.com/romanticjo/ccf94d3a46e8b8624fe4

**Comment by Haggle1996** [comment]
Have you reported this to Reika?

**Comment by romanticjo** [comment]
Didn't find a github issue list for his stuff.

**Comment by Haggle1996** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues
