### ISSUE TITLE
Remington rifle, from Flan, impossible to craft

### ISSUE THREAD

**Issue by arnoleo** [Haggle1996/RevolutionPack#120]
Hi,

Following the HQM quest Gunsmith in Clearing the Lands quest line, I wanted to craft a remington 870. It's just impossible to craft, the treated wood planks used in the recipe are deprecated. When I use NEI to give one to myself, I got an error message:

Data tag parsing failed: Unbalanced brackets:
 {attachments:{barrel:{},grip:{},generic_0:{},scope:{},stock:{}},ammo:[0:{}]

Thanks for your assistance

**Comment by Haggle1996** [comment]
Apologies, this sneaked in when we updated to IE 0.6.0. It will be fixed in 1.2.4.0.

In the mean time, you can do /give <playername> flansmod:r870
