### ISSUE TITLE
Steam grate on moon not working

### ISSUE THREAD

**Issue by Rearth** [Haggle1996/RevolutionPack#122]
The Reactorcraft steam grate doesnt work on the moon. Exact the same Setup on earth works without Problems, but on moon, the steam grate just wont create the atmosperic steam
![2015-11-19_22 23 25](https://cloud.githubusercontent.com/assets/10100603/11284973/47ff8460-8f0d-11e5-8dc0-84c555568e24.png)

**Comment by Haggle1996** [comment]
Report this to reika on his issue tracker.. There's nothing I can do about it as a pack maintainer.

-----Original Message-----

**Comment by Rearth** [comment]
ok, i'll do that
