### ISSUE TITLE
crafting recipes

### ISSUE THREAD

**Issue by jasonnva** [Haggle1996/RevolutionPack#123]
when i click on an item it says i have no permission to use so i cant see the crafting patterns

**Comment by Haggle1996** [comment]
I need more information than this. Which item?

**Comment by jasonnva** [comment]
says i dont have permission to click to see the pattern of any item works fine for single player but not on server
 


    On Saturday, November 21, 2015 1:19 PM, Haggle1996 <notifications@github.com> wrote:
 

 I need more information than this. Which item? —

**Comment by Haggle1996** [comment]
Sounds like you have ForgeEssentials turned on, but you're still in the
_GUEST_ group for permissions. Your server administrator needs to either
promote you, or configure default permissions for the server (or remove
Forge Essentials).

**Comment by jasonnva** [comment]
Hopefully i can trouble you for one more question were are forge essentials located so i can remove it .
also i believe i played about every pack out there your pack is well thought out in its balance.absolutely in my opinion the best 



    On Saturday, November 21, 2015 1:38 PM, Haggle1996 <notifications@github.com> wrote:
 

 Sounds like you have ForgeEssentials turned on, but you're still in the
_GUEST_ group for permissions. Your server administrator needs to either
promote you, or configure default permissions for the server (or remove
Forge Essentials).

**Comment by Haggle1996** [comment]
Thank you.

ForgeEssentials is located in the mods folder. Simply delete the file.

**Comment by jasonnva** [comment]
oddly i only see a config file for essentials no jar or permissions.txt
 


    On Saturday, November 21, 2015 2:16 PM, Haggle1996 <notifications@github.com> wrote:
 

 Thank you.

ForgeEssentials is located in the mods folder. Simply delete the file.

**Comment by Haggle1996** [comment]
ForgeEssentials is server-side only, so you'll only find it there, not on your client.
