### ISSUE TITLE
More detailed backstory for your minions

### ISSUE THREAD

**Issue by TheMachinator** [Haggle1996/RevolutionPack#126]
A request has been made by your loyal army of minion builders and demolitions experts that more detailed information on the level of technology and the method of destruction applied to these buildings be supplied. 
For example, do they represent FallOut (the game series) level prewar tech, with (no longer present) miniature fusion reactors and other devices, and exhibit destruction similar to that which would be caused by miniature nukes and other, similar weapons? Should they exhibit destruction comparable to that caused by a current-day conventional bombing run? Should we assume a Mutually Assured Destruction scenario, where everything that moves gets nuked, or nukes only being used for tactical purposes on industrial complexes and military installations?

The minions assigned to Pre-war Simulation Presentations would like to know the official explanation of the powerful forces known collectively as "magic". Were they created by the effects of high levels of radiation and strong EMP waves typically associated with nuclear detonations, similar to the effects of the present-day EMP Weapon on the rifts known as "aura nodes", or were they always there?

Respectfully,
The Unofficial Representative of Haggle's Minions

**Comment by DaMachinator** [comment]
Information provided elsewhere, please close
