### ISSUE TITLE
Gravity

### ISSUE THREAD

**Issue by Melkin25** [Haggle1996/RevolutionPack#127]
Gravity is affecting the pylon centers in cromaitcrafts hidden borrows and deletes loot on falling

**Comment by DaMachinator** [comment]
There are blocks that have antigravity or are not affected by gravity. Glowstone and end stone IIRC. I think you can add more.

**Comment by DaMachinator** [comment]
Submitted PR #129 to fix.

**Comment by Melkin25** [comment]
![2015-12-06_13 01 11](https://cloud.githubusercontent.com/assets/13159917/11614995/b4eea6be-9c19-11e5-891b-faef99e48874.png)
