### ISSUE TITLE
Few config changes

### ISSUE THREAD

**Issue by ShadowXx** [Haggle1996/RevolutionPack#13]
Openblocks.cfg > # Should filled tanks be searchable with creative menu
    B:displayAllFluids=true
Change to false to disable rendering of all liquid tanks in nei.

ThaumicTinkerer.cfg > # Set to false to disable imbued fire making cake. For those people who don't like cake
    B:imbuedFire.cake.enabled=true
    B:imbuedFire.enabled=true
Change ImbuedFire.enabled to false to remove items that can potentially destroy the world.

RandomThings.cfg > # How close can enemys spawn next to the player on a bloodmoon in blocks? (Vanilla=24)
    I:BloodMoonSpawnRange=3
Raise so mobs dont spawn ontop of you regardless of light level. 

Cofh/ Core / Common.cfg > # Set to true to display death messages for any named entity.
    B:EnableGenericDeathMessage=true
Change to false to prevent death messages of named entities, excluding players. Stops Thaumcrafts named mobs death messages.

Erebus.cfg > B:"Block O' Bones Inventory Save"=true
Change to false. Openblocks graves will be default and store everything.

Reika/ Rotarycraft.cfg > B:"Tools Clear Chat"=false
Prevents angular transducer clearing chat.

**Comment by Haggle1996** [comment]
All changes made, more or less. Disabling imbued fire cake would result in world corruption due to shifting item ids.
