### ISSUE TITLE
Enviromine physics not working properly, especially with Reika's mods

### ISSUE THREAD

**Issue by DaMachinator** [Haggle1996/RevolutionPack#130]
Especially with blocks from Reika's mods, and probably other mods that use metadata to distinguish between blocks.
All tileentities should probably be set to "none", as moving tileentities, especially ones that store world position data, can cause world corruption.

Adding a list of mods that need updating:
- [ ] AE2 Stuff
- [ ] Applied Energistics 2
- [ ] Automagy
- [ ] Bibliocraft
- [ ] Big Doors
- [x] Botania
- [ ] BuildCraft
- [ ] Carpenter's Blocks
- [ ] Catwalks 2
- [ ] Chisel
- [ ] Chisel Tones
- [x] Chromaticraft
- [ ] Electricraft
- [ ] Ender IO
- [ ] Enhanced Inventories
- [ ] Expanded Inventory
- [ ] Expanded Redstone
- [ ] Extra Utilities
- [ ] Forbidden Magic
- [ ] Forestry
- [ ] Galacticraft
- [ ] Garden Stuff
- [ ] GenDustry
- [ ] Immersive Engineering
- [ ] Immersive Integration
- [ ] Jabba
- [ ] JurassiCraft
- [ ] Logistics Pipes
- [ ] More Planets
- [ ] Matter Overdrive
- [ ] Natura
- [ ] OpenBlocks
- [ ] OpenComputers
- [ ] Open Modular Turrets
- [ ] Pam's Harvestcraft
- [ ] Project Red
- [ ] Railcraft
- [ ] Random Things
- [ ] ReactorCraft
- [ ] Refined Relocation
- [ ] Remain in Motion
- [ ] RFTools
- [ ] RotaryCraft
- [ ] SecurityCraft
- [ ] Stacks on Stacks!
- [ ] Storage Drawers
- [ ] Thaumcraft
- [ ] Thaumcraft Gates
- [ ] Thaumic Energistics
- [ ] Thaumic Horizons
- [ ] Thaumic Tinkerer
- [ ] ZTones

**Comment by ren-** [comment]
Is this critical enough to prevent me from hosting a long term server?

**Comment by Haggle1996** [comment]
This is a todo list for v2 of the pack, which will be a separately-maintained version of the pack (I may even give it a different name). V1.3 (the current version of Revolution) is fine for hosting.

**Comment by Serenitygene** [comment]
Agricrafts Channel Valves convert to Channel blocks when they fall, also suggest that those channel parts get an extension or reprieve from the fall physics. Suggest same with with Thaumcraft essentia tubes and the lamps of growth/fertility.

**Comment by Aivech** [comment]
That is an issue with blocks changing their metadata when they fall.

**Comment by Aivech** [comment]
I need the metadata on the channel valves

**Comment by Aivech** [comment]
so if you could hold one and type /mt hand, then I could fix it

**Comment by Serenitygene** [comment]
AgriCraft:channelValve

**Comment by DorinnB** [comment]
Décocraft block, when falling, will turn to 
http://imgur.com/ldlQCax
and if place on overworld after will be creeper puppet (pretty statue but not same as before)

only for  "small block" like toys but not block  likefridge or chest

**Comment by Serenitygene** [comment]
You get the item version of a block if it falls onto something like the botania flowers, smaller decocraft items ect.

**Comment by Aivech** [comment]
> You get the item version of a block if it falls onto something like the botania flowers, smaller decocraft items ect.

That's vanilla behavior, nothing we can do about that.

**Comment by Haggle1996** [comment]
I'm going to close this issue in favor of mod-specific issues, which are easier to manage.
