### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TheKingOrb** [Haggle1996/RevolutionPack#134]
Everytime i Click on the m9 at spawn the game crashes like i dunno if i have sometime downloaded wrong or but i literally cant play cause its crashing all the time can anyone help?

**Comment by TheKingOrb** [comment]
And im not quite sure how to get the code from my console i see that you can copy and upload the logs but i click it and it says its saved to clipboard but i dont even think i have clipboard.

**Comment by DaMachinator** [comment]
Run the game and crash it. Click upload log, and then paste the contents of the clipboard as a comment here.

**Comment by DaMachinator** [comment]
Even though you may have solved the problem, a crash report is still useful to us, as well as the steps you took to remedy the problem.
