### ISSUE TITLE
The buzzing of the bees

### ISSUE THREAD

**Issue by DaMachinator** [Haggle1996/RevolutionPack#139]
Given that Extra Bees has been pulled, would you like me to write all the ore bees or just some of them?

I was thinking about:
All bees will produce either metal dusts or Harder Ores clumps unless otherwise noted or requested by you.

Any names that match Extra Bees names are a coincidence. Great minds think alike.
GEOLOGIC BRANCH: Base breeding bees, but not entirely without use.
* Fossilized Bees - Jurassiccraft Fossil
* Earthen Bees - Dirt and compost
* Carbonized Bees - Coal (harder ores? Does harder ores even have coal?)
* Alluvial Bees - Clay, sand
* Subterranean Bees - Gravel, apatite

METALLIC BRANCH: Metals
Metallic Bees: Base breeding bee, will have a useful trait for breeding
* Cuprous bees - Copper
* Stannic bees - Tin
* Stainless bees - Nickel
* Bauxite bees - Aluminum
* Aurous bees - Gold
* Argent bees - Silver
* Ferrous bees - Iron
* Plumbic bees - Lead
* Radiating bees - Uranium Clumps (harder ores) or Pitchblende Flakes in addition to appropriate nuclear waste
* Mercuric Bees - Quicksilver droplets
* Strengthened Bees - Tungsten Flakes (rare)
* Attractive bees - Magnetite (or lodestones)

Crystalline Branch - Anything that could be remotely called a crystal
Crystalline Bee: Same as metallic bee, but with a different trait
* Energetic bees - Redstone, low chance of special RoC aluminium dust
* Diamantine bees - Diamond
* Halogenic Bees - Fluorite
* Ammonic Bees - Ammonium Chloride (dusts or ore)
* Amber Bees - Amber, from Jurassiccraft or Thaumcraft (higher chance at Thaumcraft)
* Verdant Bees - Emerald (rare)
* Electrified Bees - Certus Quartz Dust
* Luminous Bees - Glowstone dust
* Indigo bees - Lapis Lazuli
* Quartzite Bees - Nether Quartz Dust
* Silicate Bees - Silicon

UNNATURAL BRANCH: Mob drops and a few other things from the Nether
* Unnatural Bees - Multiple epic traits, but with some crippling side effects.
* Soulful bees - Tar, chance of soulsand
* Blazing bees - Blaze powder
* Magmatic bees - Magma cream
* Decayed bees - Withering dust, VERY VERY VERY (very x100) rare chance of wither skull
* Tortured bees - Netherrack dust
* Explosive Bees - Gunpowder
* Fuzzy bees - String (or cotton)

ABNORMAL BRANCH: The top tier. Cool stuff.
* Strange Bees - Base breeding bee with very desirable traits
* Primal bees - Infused shards
* Quantum Bees - RFTools dimensional shards :stuck_out_tongue: 
* Gaudy bees - Random chance of a dye
* Fractured bees - Chromaticcraft crystal shards
* Lucky bees - HQM Loot bags
* Unusual bees - Vanilla dungeon loot
* Questing bees - An amazing bee that requires a lot of effort to make for the sole purpose of making the player get one for a quest. Produces something awesome. 

Feel free to suggest more bees or restrain my insanity.

Breeding Progression:
[moar beez - Copy.docx](https://github.com/Haggle1996/RevolutionPack/files/66210/moar.beez.-.Copy.docx)

**Comment by DaMachinator** [comment]
Coming Soon: A breeding tree that makes some little amount of sense.

**Comment by DaMachinator** [comment]
If you want me to duplicate the Beyond Reality tree there will need to be more.

**Comment by Haggle1996** [comment]
No, your insanity is spot on. As far as bee names, there's no reason not to duplicate their names with other mods.

**Comment by DaMachinator** [comment]
Most of these names are original.

**Comment by DaMachinator** [comment]
And most of the names are actual words.

**Comment by DaMachinator** [comment]
Updated with a complete bee list and a progreesion chart.
If something is on the progression chart but not the list, it should be on the list under the appropriate header.

File is a Word 2013 document.

**Comment by DaMachinator** [comment]
Starting JSON file authoring

    Authority = BDEW
hmm, is that the discovered by thing?

    Authority = DaMachinator

**Comment by DaMachinator** [comment]
Started actual bee coding

**Comment by DaMachinator** [comment]
[alleles.txt](https://github.com/Haggle1996/RevolutionPack/files/67038/alleles.txt)

**Comment by mtesseracttech** [comment]
I noticed this issue, and recently Chocohead (from the IC2 forums) has released a compatibility patch for binnies mods. I don't know if it's completely out of the question for it to be added (probably, seeing that Gendustry is chosen), but regardless, something that could maybe be possible is:

Use Gendustry for the missing bee types (since I think you can't create new bees in Binnies Mods), disable the machines from Gendustry, and make players use the Binnies mods machines instead to do things with the bees.
To me, binnies mod seems much more polished than Gendustry and it would make the bee breeding less of a boring thing. (and it looks better, but maybe there are texture packs that would make Gendustry less ugly)
Also, Magic bees could be a nice addition, giving more integration from TC/botania to the rest of the pack.

Also, one last thing(but probably the most important): Beehives are attacked by zombies all the time since they emit light. Seeing how difficult traveling large distances is in the pack, it would be a good idea to make zombies not attack the hives.

**Comment by Aivech** [comment]
I am aware of the patch for Binnie's Mods. If this is implemented, I am not looking forward to progressing through the entire vanilla forestry progression to get the alveary before I can use the genetics machines.

**Comment by mtesseracttech** [comment]
That usually takes a day or 3 (if you spend a decent amount of time and on it), but it would suit the pack in a way, especially around the first moments in the pack, where everything is very manual. Around that time doing bees manually would fit right in with looking for veins of ores, manually digging ores and processing most things by hand.
In other packs I played that were balanced, they usually gated Gendustry behind the final bees from vanilla (requiring alveary parts for Industrial Apiaries), and it's really not as bad as you would think if you have ways to store your drones (filing cabinets) and such things.
I also think that many of the things added by binnies really help you in progressing through vanilla bees (like the chocolate frames). Don't forget those things, they make vanilla bee breeding much much easier and faster) and of course there is a lot one could use from Magic bees to speed things up.

And last, some bee related quests are always nice. ;)

**Comment by Haggle1996** [comment]
For the time being, I'm removing the partially implemented custom bees and replacing them with patched Binnie's. If/when the custom bees are finished, we can replace it then.
