### ISSUE TITLE
World not starting

### ISSUE THREAD

**Issue by Alex678** [Haggle1996/RevolutionPack#140]
Hello, I was very excited to start playing a new modpack and did everything as recommended on the Your First Day in Revolution page. But, the world, once started, does not load and just stays on the loading screen for a long time and then crashes. Here is my log: http://paste.atlauncher.com/view/45c50d71

Thank you in advance

**Comment by NachtRaben** [comment]
Allocate more memory to your minecraft via the java tab in the ATLauncher settings menu. The pack needs 2.5-3GB of ram.

"java.lang.OutOfMemoryError: Java heap space"

**Comment by Alex678** [comment]
Thank you, it works now :)
