### ISSUE TITLE
Suggestion : Replace Advanced System Manager

### ISSUE THREAD

**Issue by arnoleo** [Haggle1996/RevolutionPack#141]
Hi,

Advanced System Manager causes server crashes each time I break a block from this mod. As the author does not update his mod, due to problem with his computer, I suggest the replacement of it with the original Steve Factory manager, as it is not really usable in theses conditions.

**Comment by Haggle1996** [comment]
Thank you for the feedback. Unfortunately, SFM suffers from world-corrupting bugs. We had more than one player kill their save and have to go back to a backup. ASM is slightly better in that it only causes frequent world crashes. As neither mod is updated, and the mods in general make item, fluid, and power transport trivial, they're pulled entirely from the pack in version 2.
