### ISSUE TITLE
Update 3.1.0 & 3.1.1 resets all HQM quest data.

### ISSUE THREAD

**Issue by mctynp** [Haggle1996/RevolutionPack#142]
All HQM quest data was reset by the 3.1.0 update (from 3.0.0). All quest data was reset again from 3.1.0 to 3.1.1. At a minimum, there should be some kind of warning to notify users prior to the update; some of the quests that require crafting items are very expensive to have to repeat, and cheating them completed using /hqm edit isn't an option for quests that were mostly completed.

**Comment by Haggle1996** [comment]
I've added warnings and instructions for re-completing tasks to both the change notes and the warning pop up on the launcher. Fortunately, the upgrade should have made a backup for you if you want to go back.
