### ISSUE TITLE
Flan's Mod Causing Crash

### ISSUE THREAD

**Issue by CaptainSisko** [Haggle1996/RevolutionPack#143]
Clicking on the [lower green box](http://puu.sh/m3xgE/e5bdde7884.png) on the Vehicle Crafting Table causes my client to crash in both MP and SP.

I have a crashlog here:

http://pastebin.com/09qr8zYV

Any idea what would be causing this?

**Comment by Haggle1996** [comment]
The vehicle table is not craftable, nor is it intended to be used in this pack.
