### ISSUE TITLE
Having Flansmod Gun in hand crashes game

### ISSUE THREAD

**Issue by PokemonInLua** [Haggle1996/RevolutionPack#144]
So everytime I have a Flansmod gun in my hand my game crashes. This only seems to affect a player who JOINS a LAN world.

http://pastebin.com/G8QZW3nr

Also, I have disabled mods and added other mods.

**Comment by Haggle1996** [comment]
Unfortunately, I can't support players using non-standard versions of the pack. You're welcome to reach out to the author of Flan's mod for support.

**Comment by PokemonInLua** [comment]
Retried with the standard version, Still happens. Reporting to flans author now.
