### ISSUE TITLE
Packmodifications.cfg empty

### ISSUE THREAD

**Issue by Astinasha** [Haggle1996/RevolutionPack#148]
Almost every [MOD]_PackModifications.cfg file in Reika's mod folder is empty. While I'm aware not all of them have been modified from the defaults, some have, even if innociously. Still, for the sake of complying with mod author's wishes, these should be distributed with up-to-date tweaks and changes listed for the player's benefit.

**Comment by Haggle1996** [comment]
Can you give me an example of something that should be in there? I was under the impression only changes to Reika's mods that wouldn't be reflected within the default configuration (and therefore, visible in the manual) need to be listed here.

**Comment by Astinasha** [comment]
From reading it I was under the impression that all changes from the default *period* should be listed for completeness, so that there's no risk of someone meandering over to Reika and asking why something they looked up is wrong without looking in the configs first.

For example, the listed changes of rainbow forest biomes not forming in chromaticraft, electricraft's oregen being off (or altered in location). Same goes for reactorcraft's orespawn levels being altered. Anything different from the default should be documented when requested.

**Comment by Haggle1996** [comment]
Verified with Reika on teamspeak, that it's only for things not described by his config files. E.g., changing one of his recipes with minetweaker. As I don't change any of his mods, except through his configuration options, these are okay to stay blank.

**Comment by NachtRaben** [comment]
Also for the record any configuration changes made(for roc at least) is reflected as a new entry in the handbook as the very top most entry showing what is changed from default values and an explanation of how it affects gameplay. At least I've noticed this when connected to a server
