### ISSUE TITLE
Crash Report - Modular Armor

### ISSUE THREAD

**Issue by Astinasha** [Haggle1996/RevolutionPack#149]
http://pastebin.com/TEeX1THC

Just made a modular armor chestplate, got a tablet(?) with a missing name and texture. Using it opens up a broken gui.

Right clicking with the chestpalte itself to start modifying it causes consistent CTDs with no alteration to cfg files, and after reinstallation. Issue persistent in 1.3.1.0 and 1.3.1.1 (Didn't make one before then).

**Comment by Haggle1996** [comment]
Please report this directly to the mod author on their tracker.
