### ISSUE TITLE
Death Grave

### ISSUE THREAD

**Issue by LordIconMC** [Haggle1996/RevolutionPack#15]
On death all items go into the skull grave stone, except for bobbles those go in to a headstone grave next to the other grave.

**Comment by ShadowXx** [comment]
Erebus.cfg > B:"Block O' Bones Inventory Save"=true
Change to false. Openblocks graves will be default and store everything.

**Comment by Haggle1996** [comment]
Azanor/Baubles#81

Made config change, but see above issue.
