### ISSUE TITLE
Can't Open On ATLauncher

### ISSUE THREAD

**Issue by OoDaShadowTheft** [Haggle1996/RevolutionPack#150]
Can't download Revolution, here is the log.
http://paste.atlauncher.com/view/2fa3d129

**Comment by DaMachinator** [comment]
Does any other pack launch properly?

**Comment by DaMachinator** [comment]
>org.lwjgl.LWJGLException: Pixel format not accelerated

Maybe try reinstalling your GFX drivers?

**Comment by Haggle1996** [comment]
Or try reinstalling the pack again. lwjgl is copied from a shared location underneath the atlauncher folder.
