### ISSUE TITLE
Short mead, among a few other things, should not rot.

### ISSUE THREAD

**Issue by DaMachinator** [Haggle1996/RevolutionPack#151]
But it is. :stuck_out_tongue: 
I made a mead factory and the conveyor belts storing bottles in JABBA barrels started to overflow.
Not because they were full, but because the mead bottles were at different stages of decay.

Since it is alcohol, it should not rot.

Also, according to the AE2 lore about how an ME system works, food in an ME system, being stored as energy, should not rot either. But this may be more difficult to do.

EDIT: Blacklisting storage mediums from rotting food is currently not possible
https://github.com/Funwayguy/EnviroMine/issues/168

**Comment by DaMachinator** [comment]
And that issue is from the 1.6.4 version where their wiki is :angry: But I looked thru the 1.7.10 config options and it is still impossible.

**Comment by DaMachinator** [comment]
I think I can do non-rotting items, or greatly increase the spoilage period of specific items.

Will do ASAP:

Zombie brain (Thaumcraft) - never rots
Short mead and other alchohol - Takes forever or doesnt rot at all
Pam's Harvestcraft Jerky - Rots much slower

**Comment by Serenitygene** [comment]
Thaumcraft Gluttony shards

**Comment by DaMachinator** [comment]
Thanks, Serenitygene

**Comment by Solego** [comment]
It should be possible on some level, although it might take digging around in mod code.  The freezer prevents food rot.  This is definitely a mod author request, but adding other containers shouldn't take a whole lot of recoding, if the code is properly compartmented.

**Comment by Haggle1996** [comment]
It's actually really easy to do. Enviromine has a configuration just for this. I was thinking of doing a whole pass on foods in the pack -- meat-based foods rot faster, dry foods slower or not at all. The last section, outlined [here](https://github.com/Funwayguy/EnviroMine/wiki/Custom-Configs) discusses how to make items rot faster/slower.

**Comment by Serenitygene** [comment]
Mana beans

**Comment by Aivech** [comment]
Mana beans are magical. They probably shouldn't rot either.

**Comment by oxinabox** [comment]
While listing thing that should have rot time adjusted:
- Matter Overload: Emergency Rations (found them in a chest)

**Comment by Haggle1996** [comment]
It's on my list for the next patch to do a food pass.

**Comment by Haggle1996** [comment]
Replacing with a new issue.
