### ISSUE TITLE
Server lag

### ISSUE THREAD

**Issue by taze57050** [Haggle1996/RevolutionPack#152]
My serv lag with new chunk discovered : 
[15:24:43] [Server thread/INFO]: Dim 0 : Mean tick time: 200,767 ms. Mean TPS: 4,981

it's unplayable for all players !

Help please, my host is omgserv

**Comment by NachtRaben** [comment]
This isn't nearly enough information. Please provide logs containing GC and TPS information along with some worldgen.

**Comment by DaMachinator** [comment]
Did you remember to pregenerate?

**Comment by Haggle1996** [comment]
Closing since no additional info provided. Please reopen if you continue to have the problem and can provide the information.
