### ISSUE TITLE
Thaumcraft Nodes falling

### ISSUE THREAD

**Issue by Serenitygene** [Haggle1996/RevolutionPack#156]
Thaumcraft nodes are being effected by the fall physics when they get updated

**Comment by DaMachinator** [comment]
Middle-mouse over a node in creative, hold it, type /mt hand, and tell me what it says

**Comment by DaMachinator** [comment]
https://github.com/Haggle1996/RevolutionPack/commit/5211e1b3e9bbf5fb1056c0dd95892b9cef13ad2c

Should fix this issue.

**Comment by Haggle1996** [comment]
This was deployed in 2.0.1.0. Thanks for the fix, DaMachinator

**Comment by DaMachinator** [comment]
You are most welcome.

**Comment by Serenitygene** [comment]
Still falling btw

**Comment by Aivech** [comment]
grr....

I have no idea what to change.

**Comment by Haggle1996** [comment]
Figured this out. The block section in the thaumcraft.cfg was block {...}. The correct label is blocks {...}. :D Fixed and will be deployed in the next update.
