### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by mine4shist** [Haggle1996/RevolutionPack#158]
I've installed the pack using the suggested mods, but when I try to run the pack it crashes.
Here's the crash report, I hope someone can help me.
[crash-2016-01-03_23.04.40-client.txt](https://github.com/Haggle1996/RevolutionPack/files/76866/crash-2016-01-03_23.04.40-client.txt)

**Comment by NachtRaben** [comment]
Please make sure you have installed your most recent vga drivers and try again.

**Comment by Haggle1996** [comment]
You'll also have a hard time running the pack with only 2GB of RAM. Try for 3.5GB or 4GB.

**Comment by Haggle1996** [comment]
Please comment here again if you're still experiencing the issue.
