### ISSUE TITLE
Entitys stop moving for short times in Revolution v2

### ISSUE THREAD

**Issue by Benedikt20** [Haggle1996/RevolutionPack#159]
Today I started a new World in revolution 2, but I noticed that everytime after a few seconds the world ist freezing. After a short while all is back to normal but then it happens again. In the hole process I can go and walk through the world but I can't pick up Items or break blocks and set them. Here is my log, I hope you can help me.

http://paste.atlauncher.com/view/22503680

**Comment by DaMachinator** [comment]
I have a few suggestions, as I had this before, but not as bad as you are describing.

1: Save and reload the world.
2. Pregenerate at least a little bit.
3. Disable minimap radar(s).

**Comment by Benedikt20** [comment]
I did this already before I reported the bug.

**Comment by Haggle1996** [comment]
I can't read the log on my phone, but sounds like you're running out of RAM. You could test this by pressing F3 in game and watching the memory counter in the top right.

-----Original Message-----

**Comment by NachtRaben** [comment]
If you look at your f3 there is a section in the top left for memory management. 
If you watch the "allocation" part, if its above 90% you don't have enough memory allocated to minecraft. (This value uses up to the amount of memory you assigned it in the launcher, it doesn't allocate all at once).

also if this value is frequently bouncing from mid 60's straight to mid 90's this means that you have a combination of not enough memory and an issue with your garbage collection. There isn't really a fix to this other than giving it more memory and not using any resource packs as forge doesn't handle them very well for resolutions that are not x32.

**Comment by Benedikt20** [comment]
I have allocated 4.5 gb ram, but it looks like Rev.2 uses a lot more than rev.1

**Comment by Benedikt20** [comment]
I removed enviromine, looks lile there was to mich physiks and worldgeneration.

**Comment by Benedikt20** [comment]
Problem fixed, I close the issue.

**Comment by DaMachinator** [comment]
Hmmm, odd.

I run on only 4GB and have no problem.

In addition, increasing the RAM was the only change I made to the default ATLauncher settings.

**Comment by Haggle1996** [comment]
On a related note, @DaMachinator, I've been doing memory profiling. RTG uses a lot of RAM when doing world gen. I've seen it occasionally spike as high as 12GB, but more commonly between 5 and 6 GB (this is with pregenerating a lot of chunks; just walking for a short while it's typically in the 3-4 range). Switching to a BoP-only world reduces the memory use significantly, down to the 2.5-3.5 range. I'm keeping an eye on this and I'll mention it to @whichonespink44

**Comment by NachtRaben** [comment]
I was doing that memory profiling before you added it back and mentioned that to you :stuck_out_tongue:

**Comment by DaMachinator** [comment]
I only have 8 GB, and I gave slightly over half to MC
That way I can still do other things in the background, like recording.

**Comment by DaMachinator** [comment]
I must admit I subjectively like BoP more than RTG.

Objectively it also runs faster while I am exploring.
