### ISSUE TITLE
Crash in Twilight Forest

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#162]
Rev2 latest alpha

In the twilight forest, headed the same direction 4 times, each time a crash to launcher.

[crash-2016-01-05_10.45.37-client.txt](https://github.com/Haggle1996/RevolutionPack/files/78877/crash-2016-01-05_10.45.37-client.txt)
[crash-2016-01-05_10.51.51-client.txt](https://github.com/Haggle1996/RevolutionPack/files/78874/crash-2016-01-05_10.51.51-client.txt)
[crash-2016-01-05_10.56.24-client.txt](https://github.com/Haggle1996/RevolutionPack/files/78876/crash-2016-01-05_10.56.24-client.txt)
[crash-2016-01-05_10.37.37-client.txt](https://github.com/Haggle1996/RevolutionPack/files/78875/crash-2016-01-05_10.37.37-client.txt)

**Comment by Haggle1996** [comment]
Benimatic/twilightforest#33

Interaction with Reasonable Realism. If I can't get an update to TF or a way to prevent the argument from going out of range, may have to pull TF.

**Comment by Haggle1996** [comment]
Pulling Twilight Forest from REV|2 for the next update. It is really there only to support ChromatiCraft, and is by no means an important mod.

**Comment by DaMachinator** [comment]
Should we delete the appropriate dimension file before reinstalling?

**Comment by Haggle1996** [comment]
To reclaim disk space, sure. It won't cause problems with the game if it's present.
