### ISSUE TITLE
Crash on server when teleported to

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#164]
Rev1 on server

when someone teleports to me using essentials basic.

[crash-2016-01-05_11.22.44-client.txt](https://github.com/Haggle1996/RevolutionPack/files/78934/crash-2016-01-05_11.22.44-client.txt)

**Comment by DaMachinator** [comment]
Uploaded to pastebin, for mobile users, etc.

http://pastebin.com/3aAnH56U

**Comment by Haggle1996** [comment]
I assume you're referring to ForgeEssentials? If so, have your server admin download the latest Forge Essentials build: http://ci.forgeessentials.com/job/FE/

**Comment by RaineAndrews** [comment]
Sure thing, as an add-on, I'm the only one this is happening to out of the 5 people this has been tested on.  I tried reinstalling the pack, but it did not improve the situation.  Just waiting on which version we are using.

**Comment by Haggle1996** [comment]
I also noticed you're on an older version of Java (1.8-25). You should be on the same version of your server, and I highly recommend you all update to 1.8-66 if the server isn't already.

**Comment by RaineAndrews** [comment]
Thank you, I will report back after I work on these avenues of approach!

**Comment by RaineAndrews** [comment]
Updated Java.  The server removed Void Monster though.  In either case, the problem is solved!  Thanks!

**Comment by Haggle1996** [comment]
Glad it's better. Thanks for updating the issue.
