### ISSUE TITLE
CfB Fridge not preventing food rot

### ISSUE THREAD

**Issue by Solego** [Haggle1996/RevolutionPack#168]
Food is rotting whether in the fridge, or not, at the normal pace.  Fridge does not prevent, halt, or slow food rot.  This applies to the single fridge and double tall fridge.

**Comment by DaMachinator** [comment]
Was it supposed to? IIRC you need the enviromine freezer.

**Comment by Haggle1996** [comment]
Haggle had a misunderstanding. The CFB fridge does not slow down food decay. However, the enviromine Freezer can be used in the CFB multiblock, per blay09/CookingForBlockheads#66
