### ISSUE TITLE
Lack of Kitten pictures,

### ISSUE THREAD

**Issue by snowmanninja** [Haggle1996/RevolutionPack#169]
I have played a few worlds now of Revolution 2 Alpha and have not seen the expected pictures of kittens as promised with pack

**Comment by DaMachinator** [comment]
![](https://i.ytimg.com/vi/NtgtMQwr3Ko/maxresdefault.jpg)

**Comment by DaMachinator** [comment]
![](http://ochumanesociety.com/clients/3697/images/kittens.jpg)

**Comment by DaMachinator** [comment]
![You asked for it.](http://www.washingtonpost.com/blogs/local/files/2014/10/4-kittens1.jpg)

**Comment by DaMachinator** [comment]
Kitten pictures, as promised.

**Comment by Haggle1996** [comment]
+1, my friend. +1

**Comment by DaMachinator** [comment]
He did ask for kittens...

**Comment by DaMachinator** [comment]
And perhaps, if you had looked in a jungle biome, you would have seen...

![an ocelot kitten](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS2zVnpyjqT0nhV05NHVFfWdMJSL2nb0K-7GIu37fWyv96stVes6w)

**Comment by DorinnB** [comment]
now, look at this http://motherboard.vice.com/blog/toxo-terror-are-our-brains-controlled-by-cat-loving-parasites
and you won't look at internet's cat in the same point of view...
