### ISSUE TITLE
Huge lack of Copper in R2 2.0.1.0

### ISSUE THREAD

**Issue by mamykin** [Haggle1996/RevolutionPack#170]
Hello,

we have now tried this pack in both Multiplayer and Single Player, dug deep and everywhere, even where the copper indication flowers are. We seriously can't find any copper. And this hinders us from getting anywhere.

Are we missing something here?

**Comment by DaMachinator** [comment]
Have an admin clear all the non-ore blocks in a 30 block radius centered on an ore flower. Or do it yourself in a creative world.

**Comment by DaMachinator** [comment]
Try the "/cofh clearblocks" command.

Also, another player has reported that copper does indeed generate, but not in pregenerated areas.

**Comment by mamykin** [comment]
Alrighty, I'll try that @DaMachinator , thanks!

**Comment by DaMachinator** [comment]
Use it to clear away all the smooth stone and stuff, and send me a screenshot please :smiley:

**Comment by mamykin** [comment]
Alright @DaMachinator , we found copper a long way out from the starting point. So what's the issue with no copper in the pregenerated areas? It's kinda hard to travel that far early in the game.

**Comment by DaMachinator** [comment]
I have no idea. For now, I suggest making an RFTools custom dimension with all missing ores. I'll leave it to you to judge how to structure the dimension.

And yes, there are RFTools dimlets for hard ores.

**Comment by mamykin** [comment]
Oki, thank you! I'll look into this.

**Comment by Haggle1996** [comment]
Copper veins, like all other ores, are subject to the whims of the Random Number Generator. Ore flowers have a range of nearly two chunks (30 blocks, to be precise), so you will need to narrow down the area further.

http://reasonable-realism.wikia.com/wiki/Prospecting has some interesting details about how to locate ores with Harder Ores.

If you aren't ready to go exploring, once you find the ore flowers, you can set up a sluice to pull ores out without mining. There are several other mid- and late-game methods for obtaining ore. Botania's OreChid, Enviromine's Cave Dimension, RFTools, etc.

**Comment by Serenitygene** [comment]
After 4 worlds and thousands of chunks loaded, i would say that 90% of the time the ore indicators for copper are wrong. Not that the ore is far away 2-10 chunks, but flat out no where. It is Very rare for it to spawn at all. Other ores that i have tested are working fine.

**Comment by sassenach1** [comment]
I have found a single copper ore vein on a fairly long search using the default settings and cofh countblocks HarderOres:ore_copper, so it seems to still spawn very rarely.

**Comment by ghost** [comment]
I played around /cofh clearblocks in a fresh RTG world. I tried doing a 50x50 area around multiple copper ore flowers and never found a single block of copper. I tried countblocks afterwards and it came up empty in a 50x50 area around multiple ore flowers. The only way countblocks came up with anything was doing a 200x200 search standing on a flower.

**Comment by sassenach1** [comment]
IDoes anyone know how the flower spawning works? I've been trying to investigate why copper specifically may be not spawning but it's indicators are. The problem might be considered from two perspectives:

1) Copper generation is broken
2) Copper generation is correct but ore flower spawning is broken

Iron, bauxite, gold and copper veins are all entirely dependent on the COG preset 'PresetHugeVeins' for spawning, and yet iron and gold both spawn far more abundantly than copper, so if this is a config issue any problem should be in the inherited vein definitions.

**Comment by Haggle1996** [comment]
I finally have time to take a look at this issue. Sorry for the delay.

**Comment by Haggle1996** [comment]
It's also affecting lead. I've been working on this for two days now, and I'm not significantly closer to a resolution...if anything, I've gone backwards, as no copper or lead generate, but their flowers do.

**Comment by sassenach1** [comment]
To clarify, that's after changes to the live version yes? Lead has definitely spawned for me.

**Comment by Haggle1996** [comment]
No, this is all in my development environment; there were updates to several mods that are affecting it. I actually think I have it resolved now, just doing some more testing.

**Comment by Haggle1996** [comment]
This should be fixed in the next release; however, ore and ore flowers do not spawn in expected locations when using the RTG world type. BoP world types appear to function correctly.

Draco18s/HarderStuff#13
Team-RTG/Realistic-Terrain-Generation#419

**Comment by Draco18s** [comment]
> Does anyone know how the flower spawning works?

Flower spawning works like this:
1. After a chunk is generated, the chunk is examined from the bottom up.
2. Every block in that chunk that matches a registered ore (that is, registered with the flower mechanics) a counter is incremented (it's slightly more complicated than this, but it works for now)
3. Every y8 blocks scanned a random determination is made to spawn flowers
4. If it passes, it attempts to spawn some flowers ("attempt" is important here, as the flowers need grass underneath them to be planted on)

There's three points of failure possible here, the first is that the chunk generation event does not fire for some reason.  The second is that the ores are not identified correctly.  The third is that there is no valid placement for the flowers.

**Comment by Toksyuryel** [comment]
Sounds possible that the problem then is just the high amount of ground cover being generated by RTG is crowding out the indicator plants? I was noticing this issue with ATG as well back in Rev1, waaaaay too many plants and tall grass being spawned, like the worldgen just did a bonemeal pass or something. It's less extreme in RTG but still very noticeable in several areas.

**Comment by Draco18s** [comment]
Flower spawning will replace tall grass and double tall grass, as well as leaves1 and leaves2.

Edit:
Flower placement is _slightly_ different for my own blocks, as they can individually decide whether or not to spawn flowers, rather than using the chunk-counter system.  So the flowers will spawn in step 0 outlined above (`onBlockAddedToWorld()`).  This cuts out failure point 2.

Full list of blocks that flowers can replace:
- Material.leaves
- any block that `isReplaceable()` (that is, when you try to place a block on top of it, the block already there is destroyed, this includes snow_layer)
- Does _not_ replace fluids (fluids are replaceable)

**Comment by sassenach1** [comment]
As I follow the method, then, I fear I cannot see how false positives might be generated. i.e. flowers without ore. 

All I can think of is either ore blocks are being replaced entirely post flower generation. Alternatively, the COG configs defined two vein types using "HarderOres:ore_copper:0", plausibly this is recognised as being copper by the flower algorithm but as stone by the game?

In any case, thank you for the response.

**Comment by Draco18s** [comment]
ore:0 is still ore.  It has 1 nugget left.

**Comment by Haggle1996** [comment]
Just to sum up the issue: Harder Ores copper ore flowers are generating for ReactorCraft ores. This leads to many false-positives as these ores are relatively common and copper is relatively rare. At the time, there is no good workaround for locating copper, other than to enable COG debugging using /cogEnableDebugging. This will show ore vein wireframes; copper is a bright brown color (versus dark brown, which is iron). Copper is relatively rare, so it's not unusual to have no veins in the immediate area. You can use '/cogEnableDebugging false' to remove the wireframes.

**Comment by fwsGonzo** [comment]
"Harder Ores copper ore flowers are generating for ReactorCraft ores. This leads to many false-positives as these ores are relatively common and copper is relatively rare."

I am having the issue everyone is experiencing with copper. It's unfortunate that it's hard to solve. Hoping for a resolution. :+1:

**Comment by Haggle1996** [comment]
It is already fixed in the forthcoming beta; however, you will need to start a new world in order to get the updated world gen.
