### ISSUE TITLE
No crafting recipes 

### ISSUE THREAD

**Issue by pronky** [Haggle1996/RevolutionPack#171]
Forestry farm blocks , thermionic fabricator , centrifuge in forestry dont show crafting recipe in latest download update how do i get them to show in revolution 1

**Comment by DaMachinator** [comment]
[Revolution 1 gameplay changes](http://revolutionpack.info/article/rev1-gameplay-changes/)

>Forestry engines are disabled.

@Haggle1996 Could you have accidentally removed all Forestry machines this way?

**Comment by pronky** [comment]
I have thought of this so i saved all files deleted atl launcher and revolution ,,downloaded all again and started a new game unlocked challenges up to carpenter but recipes dont show it says client therad error error loading recipes out of bounds exception :9

**Comment by pronky** [comment]
How can you do the automated farming challenge if forestry engines are disabled

**Comment by DaMachinator** [comment]
There are other farming machines.

**Comment by pronky** [comment]
I understand but the quest cannot be claimed until items are crafted and the three next quests cant be started until automated farming quest is completed

**Comment by Haggle1996** [comment]
NEI Integration needs to be updated, but I have not yet released an update to 1.3.1.1. You can obtain the updated mod here: http://minecraft.curseforge.com/projects/nei-integration/files/2272481

This will restore the missing Forestry recipes.

**Comment by Time6628** [comment]
This has been fixed since https://github.com/Tonius/NEI-Integration/commit/dce634ed533832ef1e8ea665735de9f0c8f0e16f please update this mod :smiley_cat:
