### ISSUE TITLE
Rotarycraft and torches

### ISSUE THREAD

**Issue by lebagvondouche** [Haggle1996/RevolutionPack#172]
If I rightclick a Rotarycraft machine with a torch in hand the client crashes with a "Internal Server Error".

https://gist.github.com/mamykin/c0b3731b0a7319a89703

Can't decide if its R2 or Rotarycraft that's the issue.

**Comment by Aivech** [comment]
We need the whole log. There is no crash report there, just Forge telling mods the game stopped.

If you have modified the pack, I will still try to help to the best of my abilities, but I need the complete logs and the crash report.

**Comment by mamykin** [comment]
Edited in the whole log from logging in to rightclick.

**Comment by Aivech** [comment]
That is odd, it still looks like most of the log is missing. Also, unless there is some still missing, the crash report is still gone, by which I mean that MC did not crash, it merely killed the server somehow.

Did it CTD or to the menu?

**Comment by lebagvondouche** [comment]
Trying to get better logs.

**Comment by Aivech** [comment]
It should be in your instance folder under logs.

Any crash reports should be there, along with FML-client-latest (very useful, but it does contain the name of your user directory)

**Comment by mamykin** [comment]
I pasted the FML-client-lates, but no crash reports I'm afraid. Updated the Gist with the server log.

**Comment by Haggle1996** [comment]
Crash reports are in the instance/crash-reports folder.

If you're not getting a crash report, it usually means the Java Virtual Machine crashed talking to the operating system -- most commonly this is caused by out of date video drivers, but YMMV.

As DaMachinator said, we unfortunately need a complete log from start through crash.

**Comment by Aivech** [comment]
We have it. He had a server error which disconnected him.

**Comment by Aivech** [comment]
At least we have the server error, he seems to be having trouble finding logs.

**Comment by Aivech** [comment]
https://gist.github.com/mamykin/c0b3731b0a7319a89703

**Comment by lebagvondouche** [comment]
@Haggle1996 I don't have any crash-reports folder within my instance folder I'm afraid.

**Comment by Aivech** [comment]
The folder is called "logs" and everything is in it - crash reports, fml logs, gibberish files noone can read.

**Comment by Aivech** [comment]
The gibberish files you will know because nothing on your computer can open them.

**Comment by lebagvondouche** [comment]
I have the crash report now: https://gist.github.com/mamykin/a201ba803a938fbdfd2f

**Comment by NachtRaben** [comment]
OH, I know exactly what this is.

**Comment by NachtRaben** [comment]
Its a desync issue between what the client determines is in his inventory, and what the server has for the player inventory. 

eg how items replaced by inventorytweaks don't render on your hotbar until you update your inventory.

rightclicking reikas machines with these invisible items causes this crash.

**Comment by Aivech** [comment]
So, how do we fix this?

**Comment by NachtRaben** [comment]
He has to make sure his "empty" hand is actually empty.

**Comment by lebagvondouche** [comment]
So the server thinks my hand is empty and my client thinks it has a torch?

**Comment by Haggle1996** [comment]
Interesting. This may be a report-worthy bug with either enviromine or Reika's mod. Enviromine dynamically replaces torches in the players inventory with Enviromine-brand torches (which burn out, set fires, etc.) when the player interacts with things. For some reason, this explodes on the server.

**Comment by NachtRaben** [comment]
Try loggin in, and moving the torch to a different inventory slot, then place it back in your hand and right clicking.

If you still crash, this needs further investigation.

**Comment by Aivech** [comment]
Chisel torches work fine - glad I use them for my entire base

**Comment by lebagvondouche** [comment]
@NachtRaben the issue persists if I put it in a different slot then place it back and right clicking.

**Comment by Haggle1996** [comment]
Yes, I believe it's crashing because the torches haven't been converted yet to Enviromine torches.

**Comment by Aivech** [comment]
Will we have to disable burning out torches?

**Comment by Haggle1996** [comment]
No, I'll just leave this as a known bug if it can't be fixed.

**Comment by Haggle1996** [comment]
Reika thinks this is a world corruption issue; I'll need to test and see if I can replicate it.

**Comment by Aivech** [comment]
that...is odd

Never had world corruption myself
