### ISSUE TITLE
Electricraft falling blocks change metadata

### ISSUE THREAD

**Issue by taze57050** [Haggle1996/RevolutionPack#173]
All insulated cable , at falling , change in simple wire not insulated ,

**Comment by Aivech** [comment]
So when an insulated cable falls it turns into the same kind of cable, just not insulated?

**Comment by taze57050** [comment]
Example : 
Insulated tin wire fall = tin wire

**Comment by Aivech** [comment]
Time for /mt hand of every single Electricraft wire...

**Comment by taze57050** [comment]
Insulted cable : 
ElectriCraft:electricraft_item_wire:16
ElectriCraft:electricraft_item_wire:17
ElectriCraft:electricraft_item_wire:18
ElectriCraft:electricraft_item_wire:19
ElectriCraft:electricraft_item_wire:20
ElectriCraft:electricraft_item_wire:21
ElectriCraft:electricraft_item_wire:22
ElectriCraft:electricraft_item_wire:23
ElectriCraft:electricraft_item_wire:24 withTag({lvl: 25, fluid: 1 as byte})

**Comment by Aivech** [comment]
Thanks, man! Now I just have to enter these in, and they should come with the next update.

**Comment by Haggle1996** [comment]
These fixes were published in 2.0.2.0.

**Comment by Serenitygene** [comment]
Still changes to uninsulated version when you break the supporting block, also insulated redstone conduit from Ender io becomes conduit connector when they fall.

**Comment by Aivech** [comment]
Well, unless the metadata he gave me was wrong, that should have fixed it.

@Haggle1996 Would you mind checking my work? A second pair of eyes always helps.

**Comment by Haggle1996** [comment]
Fixed in 2.1.3.0
