### ISSUE TITLE
Game Freeze

### ISSUE THREAD

**Issue by taze57050** [Haggle1996/RevolutionPack#175]
My game freeze when searching nei, I am forced to close game

**Comment by Haggle1996** [comment]
You must post full logs to receive support, and generally comply with [guidelines for reporting issues](https://github.com/Haggle1996/RevolutionPack/blob/master/CONTRIBUTING.MD). As you've repeatedly opened issues in the past without logs, issued pull requests, and we know from what log snippets you've provided that you run a modified pack, consider this your final warning: failing to comply with the guidelines above will result in you being blocked from this repository.

Please provide full logs and I will reopen this issue.
