### ISSUE TITLE
I think my game is caught in the middle of me dying

### ISSUE THREAD

**Issue by J-Fulton** [Haggle1996/RevolutionPack#176]
Game appears to think I am dead, but has yet to process that I am dead. It is like the game logic is stuck between this player is dead and the player is dead we should respawn them. I have full mobility with some odd symptoms. I understand you may not be able to help, but I am hoping you can save me the trouble of losing a full day's work clearing out a dungeon.

Symptoms:
- Screen is stuck at slight tilt and shaking, like being on water and colliding with terrain.
- I have no health bar (not an empty health bar, but the health bar completely gone) there is still an armor and a hunger bar
- I cannot pick up a pile of items at my feet
- My inventory won't stay open
- Can't activate chests/beds/etc

Debug steps
- I have tried refreshing chunks, exiting, restarting my world
- I have loaded a previous backup from about 24hrs before issue started and it shows no symptoms, restoring the latest world shows all symptoms.
- I have used the /kill command to try and trigger some kind of reset
- I have tried to sleep in a bed, I can't activate things in the world

![cant_die_bug_screenshot](https://cloud.githubusercontent.com/assets/12940142/12228272/a85ae2f6-b7ed-11e5-9fb1-05f8f5d73317.png)

**Comment by Aivech** [comment]
We need full game logs.

**Comment by J-Fulton** [comment]
[Bug_Report_176_Logs.zip](https://github.com/Haggle1996/RevolutionPack/files/88056/Bug_Report_176_Logs.zip)

I'v attached the Zip with the logs from 1/10/16 when the issue started, and 1/9/16 which is the last day it was working normally.

**Comment by Aivech** [comment]
Reuploaded the FML_Client_Latest and latest.txt to Gist

https://gist.github.com/DaMachinator/7a2e29df43a9b85cb190

**Comment by J-Fulton** [comment]
Hi, I've noticed the Revolution 2 has gone live so I will be switching to that modpack. This is no longer a major issue for me so if you want to work on it feel free and I will provide whatever info I can that you might need from me (in case there is a bug that might affect others) but if you have more important tasks at hand feel free to close the bug.

Thank you for your hard work maintaining a great game.

**Comment by Haggle1996** [comment]
Thank you for reporting and posting logs. I'm going to close this for now, as it's not generally reported as a pack issue and you indicated it's not so much of a problem anymore. :) If this comes up again for you or anyone else, please post a note here and we'll reopen the issue.
