### ISSUE TITLE
Revolution 1 randomly freezes but does not crash to desktop

### ISSUE THREAD

**Issue by 1John5vs7** [Haggle1996/RevolutionPack#178]
First of all, here is a complete dump of my latest log that comes from the most recent instance of this freeze issue:
http://pastebin.com/nGZNy9se

The issue I'm experiencing is that I'm trucking along having a jolly time in the overworld either hoofing it over land or striking the earth (Dwarf Fortress ref ftw!) in a cave underground. Everything is running fine, I have more or less stable FPS, and all of a sudden I'll round a corner and WHAM, freeze. The whole game seizes up, my inventory disappears, my hotbar disappears, I don't see Steve's hands anymore, my minimap disappears...everything vanishes as if I've hit F1, but I haven't hit F1.

The game no longer responds to WASD or other keystrokes, but interestingly I continue to hear sound in realtime. So, for example, if a partner is fighting a mob, I hear the exchange of melee: damage being dealt, spells, that sort of thing. Moreover, if I push the Esc key, I hear the menu pop up even though I can't see it, and if I take my mouse and hover over where the buttons would normally be, I can click where "Quit Game" should be and the game will dutifully close, though instead of going to the load screen, it continues to show me the frozen screen until I manually kill the process either with a "Kill Minecraft" button in the AT console or with ctrl+alt+del.

Initially, I thought this might be a mob but the most recent crash was a log in about an hour after I initially froze in this location. I was able to take 2 steps farther forward before the game froze again. No one else had been on in that time or in that chunk so I'm 100% positive any mobs would be long gone. As such, I must assume it's a STATIC causing this, and if I had to guess, I'd blame Chromaticraft because I've heard some things.

Anyway, I should let you know I'm running Windows 10, I have 4GB of RAM allocated, I have an ATI Radeon HD 4300/4500 Series graphics card with 4GB of video RAM. Basically, my system is able to handle Minecraft, but not with shaders and fancy texturepacks and that sort of thing.

I'm running BetterFPS, Optifine, and Fastcraft, and I have just about everything set to minimum. That's enough to get me ~20FPS most of the time and sometimes as much as 40FPS.

Let me know if you need any other info to help me troubleshoot. Oh, and thank you for the mod. I love it aside from this issue. Must be a lot of work to maintain, but it's so fun, so thank you for doing that on behalf of us MC gamers! :)

Sincerely,

Rancho_Cucamunga

**Comment by Aivech** [comment]
Did you try removing Optifine? I have worse specs than you and I can run without it.

**Comment by 1John5vs7** [comment]
Yes, I've tried "running" it without Optifine. It's more like "limping" it. Seriously, not even walking, limping. Like I got mauled by a bear and the bear died, but the infection in my leg is going to kill me before I can build a raft and float down the river to civilization. Just...liiiiiiiiiimping along. Why did I agree to go on that trip in the first place? It was insane to go into big bear country with just a pen-knife and my wits. Graaar!

**Comment by Aivech** [comment]
On Revolution|1, I got what I considered to be a decent framerate, running ATG+Streams world (pregenerated of course), with five chunks render distance, fast graphics, advanced OpenGL on, no clouds, no view bobbing, FoV 90.

4.5 GB allocated, AMD four-core 3.7 GHZ processor, 1GB video card (GeForce GT 730)

**Comment by 1John5vs7** [comment]
Well, I mean, I'm happy that worked for you, but it does not work for me. What I'm interested in finding out is what is it that caused me to freeze suddenly. I've never encountered that in any modpack before and I've played with just about all of these mods before in Regrowth and elsewhere. Is there nothing in the log that indicates what might be out of place? Was there any kind of Chromaticraft entity present? Maybe something from Grimoire of Gaia 3? Those are 2 I haven't used much before.

**Comment by Aivech** [comment]
Optifine troubleshooting is a bear. I don't have the whole log - I need all of it.

**Comment by 1John5vs7** [comment]
I'm trying to upload the whole thing but it's too long for Pastebin so it's truncating it. :\

**Comment by 1John5vs7** [comment]
Here's a link for the upload log from ATLauncher...

http://paste.atlauncher.com/view/9b3e036b

**Comment by Haggle1996** [comment]
I've had this exact issue reported with other OptiFine users -- UI blanks out and you're still playing, but you can't see or do anything. 

Some players have had luck with just pressing F3 + T, others have been able to get it to work with these EXACT steps; however, many mods have an explicit 'does not work with Optifine' policy. The pack won't even load for me with OptiFine, but fortunately, I don't need it. Here's how they've gotten it to work:

1). Make sure you have the latest video driver (in your case, you have an older card; the latest driver is included with Windows 10, so skip this step).
2). Install a fresh instance of the pack (do not reinstall over the existing instance) -- DO NOT include OptiFine at this point. Make sure you include the exact set of optional mods you want.
3). Start the pack up once and load up a map, then save, quit, and close Minecraft.
4). Add OptiFine and restart the pack -- at this point everything should work okay.
5). If you need to add/remove mods, repeat from step 2.

**Comment by 1John5vs7** [comment]
Thanks Haggle. I will try this if it happens again and let you know how it goes!

**Comment by 1John5vs7** [comment]
Also I should note that the steps 1-5 method is exactly what I did when I first installed ;) I always add optifine after an initial launch (because it's always needed on my machine >.< )

**Comment by 1John5vs7** [comment]
Updated log...this time it did throw an error. http://paste.atlauncher.com/view/9838ce0b

**Comment by NachtRaben** [comment]
OpenGL errors are common from the intel drivers provided from windows updates. They shouldn't have any significant problems though.

**Comment by Haggle1996** [comment]
This appears to be an out of date video card issue.
