### ISSUE TITLE
Player skin is corrupted after dying.

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#179]
Maybe related to Et Futurum bug. Appeared in last alpha. I can replicate on my machine as well as others. Sorry, no logs. :P

**Comment by Aivech** [comment]
Does Et Futurum add some kind of hacky support for 1.8 full body hat layer?

**Comment by Haggle1996** [comment]
Actually, it does. :P

**Comment by Aivech** [comment]
Well, I think we found our culprit.

**Comment by Aivech** [comment]
I just made a 1.8 full overlay skin.

In plain 1.7 it looks decent.

**Comment by Aivech** [comment]
![skin for 1 8](https://cloud.githubusercontent.com/assets/16143392/12268880/ba3775d6-b91c-11e5-87a0-f549d5bdef7b.png)

**Comment by Aivech** [comment]
You can test it if you want.

**Comment by Aivech** [comment]
I am going to change my skin to that (once I find where I put my current skin) and test it for myself.

**Comment by Aivech** [comment]
@Haggle1996 Is your skin 32x64 or 64x64?

If it is 32x64, that might be the problem.

**Comment by Toksyuryel** [comment]
I'm getting this error with a 64x32 skin.

**Comment by Aivech** [comment]
I just changed my player to a 64^2 skin, I will test ASAP.

Type of death does not matter, right?

**Comment by Aivech** [comment]
For anyone who wishes to try to convert their skin to 64x64, here is the official template (4px Steve arms) ![It would be interesting for someone to actually use this for a skin.](https://minecraft.net/images/4px_reference.png)

**Comment by Haggle1996** [comment]
This should be fixed in the next release.

**Comment by Haggle1996** [comment]
Also, if you're still having problems, try setting B:"Skin overlays"=false in the /config/etfuturum.cfg file.
