### ISSUE TITLE
Custom ore generation copper veins not generating correctly 2.0.2.0

### ISSUE THREAD

**Issue by sassenach1** [Haggle1996/RevolutionPack#181]
Apologies if this is incorrect procedure, the previous copper spawning issue was closed. 

Fresh install of Revolution 2 2.0.2.0-Alpha. Harder ores copper generates only when using the 'cluster' type generation option, the default 'veins' option produces copper indicator flowers but no harder ores copper ore blocks. 

This suggests to me that the veins are being produced but with a quantity of 0, thus a config issue.

**Comment by Haggle1996** [comment]
Reopening #170. I'll track the issue there. Thank you for reporting; this was the appropriate venue. :)
