### ISSUE TITLE
Crash to Desktop [Rev2 2.2.0.2.0]

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#182]
While in LAN play.  Crash while exploring.  Maybe you know about it, maybe you don't.

http://pastebin.com/jCgQ5b9J
[crash-2016-01-15_09.45.11-server.txt](https://github.com/Haggle1996/RevolutionPack/files/92270/crash-2016-01-15_09.45.11-server.txt)

**Comment by NachtRaben** [comment]
For the record using modded minecraft over the built in LAN is an incredibly bad idea and you should always have a machine run a dedicated server for both of you to connect to.

also, there is not enough information in the crash-report. Go to your instance folder and upload a copy of your latest.log and fml-server-latest.log's

**Comment by NachtRaben** [comment]
Also please attempt to recreate this issue without fastcraft/betterfps enabled.
Any optimization/fps enhancing mods hinders the debugging process significantly.

**Comment by RaineAndrews** [comment]
Can't duplicate crash

**Comment by AEnterprise** [comment]
looking at the crashlog it's due to fastcraft doing non threadsafe stuff from another thread
