### ISSUE TITLE
Mobius Unstable Ingot not craftable

### ISSUE THREAD

**Issue by jonathan-ng** [Haggle1996/RevolutionPack#183]
Crafting with the pseudo inversion sigil produces regular unstable ingots. (Rev 1.3.1.1) This issue is apparently due to a mod conflict, see [issue #706](https://github.com/rwtema/extrautilities/issues/782) of Extra Utilities. Confirmed that downgrading to XU 1.2.10 as recommended fixes the issue.

**Comment by Haggle1996** [comment]
I'll revert XU in the next update.

**Comment by Haggle1996** [comment]
Resolved in the next update.
