### ISSUE TITLE
Crashing on looking up a recipe with NEI

### ISSUE THREAD

**Issue by ZeldaNeeChan** [Haggle1996/RevolutionPack#185]
[crash-2016-01-18_19.49.06-client.txt](https://github.com/Haggle1996/RevolutionPack/files/94033/crash-2016-01-18_19.49.06-client.txt)

Not much more I can say. Doesn't happen with every single item. But majority do. 

Thanks xx

**Comment by Aivech** [comment]
Reuploaded to Gist:

https://gist.github.com/DaMachinator/6e9222d044ce22e8f250

**Comment by Aivech** [comment]
We need to know:
1. Is this from Revolution|1 or Revolution|2?
2. What is the pack version?

**Comment by Haggle1996** [comment]
It's Rev2 version 2.0.3.0. I believe it's related to the same open issue on Reika's tracker.

-----Original Message-----

**Comment by Haggle1996** [comment]
ReikaKalseki/Reika_Mods_Issues#488

Expect a fix when Reika's mods update.
