### ISSUE TITLE
Character Model Corruption on Death

### ISSUE THREAD

**Issue by foxyv** [Haggle1996/RevolutionPack#186]
Version: 2.020-ALPHA

When a character dies on our server, their character model becomes corrupted and garbled. Tried using different character textures to no avail. This is appears to be due to the mod that leaves skeletons behind when you die.
# Before Death

![before death](https://cloud.githubusercontent.com/assets/1401384/12493994/ba68d294-c03c-11e5-97e5-ac2d3246bd90.png)
# After Death

![after death](https://cloud.githubusercontent.com/assets/1401384/12493997/bcb0685a-c03c-11e5-97d0-4a75038d80b9.png)

**Comment by foxyv** [comment]
Note: Only way to fix this is to shutdown the client and start it back up.

**Comment by foxyv** [comment]
Nevermind just found this issue description. Issue #179

Trying:
Also, if you're still having problems, try setting B:"Skin overlays"=false in the /config/etfuturum.cfg file.

**Comment by Haggle1996** [comment]
No worries; the option is being set false as default in the next update. Also, looks like you have the dreaded Gun customization texture issue on linux machines; see #180

**Comment by foxyv** [comment]
Cool! Thank you!

**Comment by foxyv** [comment]
Yeah I think it's because I'm running Linux. Something to do with the file system.

**Comment by Haggle1996** [comment]
The fix is as the bottom of that issue; I still have it open because I need to test incorporating it into a later update.
