### ISSUE TITLE
Aluminum

### ISSUE THREAD

**Issue by DarkScott1** [Haggle1996/RevolutionPack#187]
I have been searching for aluminum ore for 2 days, and havent find any... Can anyone help or say what Y is best to search and which biome is important while searching . ?

**Comment by Solego** [comment]
This is not a "needs help" forum. It is only for bugs in the pack. Please refer to the Revolution 2 homepage for info about ore gen, or ask in the irc channel.  The following is copy/pasted from the homepage. 

Aluminum - Flat Clouds found near the surface. Only found in mesa, swamp, and jungle biomes.
