### ISSUE TITLE
thaumcraft minigame ...revolution 1

### ISSUE THREAD

**Issue by pronky** [Haggle1996/RevolutionPack#188]
cannot complete the minigame of joining aspects for research notes ... the aspects do not highlight and link  (rev1  1.3.1.1)  also tried to update outdated mods to new versions which I am prompted to do upon starting , game does all the loading then crashes.  these are the updated mods which I cant get to work;   dragon api v10d, chromaticraft v10d, rotarycraft v10d, electricraft v10b, expanded redstone v10b,  reactorcraft v10d, voidmonster v10d, when old mod is replaced game crashes

**Comment by Haggle1996** [comment]
Unfortunately, you will need to restore your world from backup. V10 of Reika's mods are not compatible with 1.3.1.1 in its present state.

As far as not being able to complete Thaumcraft research, maybe you can post a screenshot that shows the problem? I'm certain thaumcraft is working, as I've heard from several players recently who've gone deep into the mod and it's addon.

**Comment by pronky** [comment]
All new mods removed and re-downloaded modpack, thaumcraft is working... Thanks
