### ISSUE TITLE
Lexica Botania from chest doesn't complete quest

### ISSUE THREAD

**Issue by foxoftheasterisk** [Haggle1996/RevolutionPack#190]
I received a Lexica Botania from a dungeon chest.  For whatever reason, that version does not complete the "Book Learner" quest.  I had to craft a duplicate.

**Comment by Aivech** [comment]
The quest is probably a crafting task and requires you to actually craft a lexicon, hence why you had to craft a lexicon. Either that or it is something wierd with extra data on an item.

@Haggle1996, how bad would it be if we made the task a detection task?

**Comment by foxoftheasterisk** [comment]
It is not a crafting task - I made sure to check that, or I wouldn't have reported it as a bug.  (It has to be a detection task, in fact, due to the odd means of creating the thaumonomicon.)

**Comment by Aivech** [comment]
I forgot that making the thaumonomicon, making sure you still had your Chromatic Lexicon, and obtaining a Lexica Botania were all in the same section.

Do you still have the Lexica you obtained from a dungeon chest?
If so, do "/mt hand" with it in hand. Paste the results here.
Then repeat with the crafted lexicon.

**Comment by foxoftheasterisk** [comment]
They each gave an identical result:
Botania:lexicon.withTag({})
Is in ore:lexicaBotania

**Comment by Aivech** [comment]
I have no idea then

I will summon the @Haggle1996

**Comment by Haggle1996** [comment]
If I get more HQM bugs, I may fix this, but otherwise you'll need to craft a new one. Changing the HQM book resets everyone progress, which is very annoying.
