### ISSUE TITLE
Mine Tweaker crash with KCauldron

### ISSUE THREAD

**Issue by badgernz** [Haggle1996/RevolutionPack#191]
Just started up the Dev Build of Rev2 and got this error

http://pastebin.com/YYpCyvb2

**Comment by Aivech** [comment]
How bad would it be to use ForgeEssentials instead of KCauldron?

Also, this looks like a mod compatibility bug with KCauldron rather than a pack issue.

Summoning the @Haggle1996 as this is beyond my capabilities.

**Comment by Haggle1996** [comment]
KCauldron is something that I can't keep up with supporting, as it changes near daily and so many mods frequently go in and out of compatibility with it by the hour (slight exaggeration).

That said, it looks like the error with FastCraft 1.22-ctest18 included in the latest dev version. You can try disabling FastCraft, but clients connecting will also need to disable FastCraft.

**Comment by badgernz** [comment]
I understand that, I dont have fastcraft on the server :/

**Comment by Haggle1996** [comment]
Your best bet is to post the crashes to the Kcauldron issue tracker and work with them directly. Once the beta is released, mod updates will slow down and we can probably get a stable kcauldron/REV|2 solution soon.

**Comment by Haggle1996** [comment]
Also, if you're bored, read the kcauldron issues on reika's tracker...lots of angst because kcauldron doesn't support v10 of Reika's mods yet.

**Comment by Haggle1996** [comment]
I'm going to close this issue -- there's nothing I can do about it. It's up to kcauldron and other mods to address.

**Comment by Haggle1996** [comment]
Also, you may want to look here for some better info: https://gitlab.prok.pw/KCauldron/KCauldron/issues/272
