### ISSUE TITLE
Structures Spawning under deep Ocean

### ISSUE THREAD

**Issue by imkSushi** [Haggle1996/RevolutionPack#196]
Structures have been spawning in the Deep Ocean in Realistic Generation:
![2016-01-31_17 11 02](https://cloud.githubusercontent.com/assets/16558336/12703559/0820dcbc-c83e-11e5-9f98-ea162de4fe2c.png)

**Comment by Haggle1996** [comment]
This is intentional. They should be limited from the deep ocean, but I'm not certain if we can filter down that far.

**Comment by Aivech** [comment]
Is the Deep Ocean its' own biome? 

I am also fairly certain you can set y-level constraints for structures.

**Comment by DorinnB** [comment]
Structure spawn everywhere. After the massive fallout, ocean raised, new montains or sand hill raised over structures.

**Comment by imkSushi** [comment]
Good point.
