### ISSUE TITLE
The only indicator is Redstone, and its in a lot of places.

### ISSUE THREAD

**Issue by imkSushi** [Haggle1996/RevolutionPack#197]
There is only the Redstone indicator in the Realistic world gen for the world I generated. It is a frequent indicator.

**Comment by Aivech** [comment]
On the dev server I have not explored much and I have seen almost every indicator that exists. Also, indicators are biome-dependant - you are probably in a redstone-heavy biome.

**Comment by Haggle1996** [comment]
Can you provide the level seed?

**Comment by imkSushi** [comment]
The seed is:
-8772029445924037552
on 'Realistic' in survival. You spawn near or in snow.

**Comment by Haggle1996** [comment]
Just at the initial spawn. That's copper and tin flowers right below.

![2016-01-31_13 48 16](https://cloud.githubusercontent.com/assets/11808184/12704863/8ce48eca-c821-11e5-9ef0-cf9a0628a5a8.png)

Have you tried doing /cogEnableDebugging to see the ore wireframes? See if anything lines up with where it's supposed to go?

EDIT: In actually exploring the wireframe of your ore, all redstone on the island makes sense, as it's the only ore nearby that makes it up to the higher elevations of the island. Everything else is just off shore. I'd recommend you make a world, this is just luck of the RNG. I've heard good things about the 'Good Morning' seed.
