### ISSUE TITLE
Angel Blocks

### ISSUE THREAD

**Issue by imkSushi** [Haggle1996/RevolutionPack#198]
There is both a crafting recipe, and gravity for Extra Utilities Angel Blocks. I suggest that either the recipe or the blocks gravity should be removed.

**Comment by Aivech** [comment]
I'll do gravity.

**Comment by imkSushi** [comment]
Good, I always liked angel blocks, and in a pack with gravity, they will be useful.

**Comment by Aivech** [comment]
Should be fixed by https://github.com/Haggle1996/RevolutionPack/commit/34007c07d5da0df7839838751680ca607389ecf1

Fix should be released in the next update.
