### ISSUE TITLE
Feature request, Xaero's Minimap

### ISSUE THREAD

**Issue by lebagvondouche** [Haggle1996/RevolutionPack#200]
Hello,

just giving a tip for a minimap, Xaero's Minimap. It's super smooth and runs better performance wise for me at least. A fullscreen map is coming in February.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2379024-xaeros-minimap
http://www.minecraft-downloads.com/xaeros-minimap/

**Comment by Aivech** [comment]
Mapwriter is already available as an alternative to Journeymap, as well as OPIS. If you want to add Xaero's minimap yourself until this is confirmed or denied by @Haggle1996, it is very easy to do so.

**Comment by Haggle1996** [comment]
It looks interesting. I'll certainly take a look at it.

**Comment by Haggle1996** [comment]
This crashed repeatedly today while testing it along with some other minimap options. I may look at it again another time, but closing for now.
