### ISSUE TITLE
Freeze/Crash when opening Quest Book

### ISSUE THREAD

**Issue by metanerd3ooo** [Haggle1996/RevolutionPack#201]
I have v2101, playing SMP.  Memory usage at about 40% of 4gb.  Try to open quest book. Nothing happens for a short time, then it just freezes.  Then the memory usage climbs up to 100%, at which point it seems to unfreeze without opening the book (memory usage now at ~80%) or it crashes altogether.

Here's the log uploaded by ATLauncher:

http://paste.atlauncher.com/view/ef0a651f

**Comment by metanerd3ooo** [comment]
Just for an update: I noticed in chat that the guy running the server (Krysommor) was running v2100, not v2101.  Since the v2101 update mentions the quest book, I suspected that might be connected.  When I created a new v2100 instance, I can now apparently open the quest book like normal.

**Comment by Haggle1996** [comment]
Yes, the quest book between the server and client must match or it will cause issues. Glad's it's resolved.
