### ISSUE TITLE
Rev2: Tps issue

### ISSUE THREAD

**Issue by Krysommor** [Haggle1996/RevolutionPack#202]
There is a big issue with Tps during and after a red moon. i have server running with 4gb via Nodecraft with the pack at 2.1.0.0

**Comment by Haggle1996** [comment]
Most likely the server couldn't handle the number of entities spawned by a blood moon. I recommend you go into your /config/RandomThings.cfg file and set the following to 2 or 1 (default is 3):

```
    # With which number should the default entity limit be multiplicated on a blood moon
    I:BloodMoonSpawnLimitMult=1
```

I would try it at 1 first and see if your problem goes away. If it does, you can try increasing it to 2, to see if that's satisfactory.

**Comment by Haggle1996** [comment]
If you still encounter the issue with the multiplier set to 1, please comment here and I'll reopen the issue.

**Comment by Krysommor** [comment]
from  my server last night, i was in a rainbow forest, and the amount of cows,pigs and sheep that that was also making tps issues thanks to the streams mod gathering them up. i tryed to use the command /kill @e[type=Creeper] or other entities it would kill me instead of the entity noted, even /butcher would not work.

**Comment by Haggle1996** [comment]
The command is /cofh killall <entityName>. For example, `/cofh killall` kills all hostile mobs. `/cofh killall Creeper` kills all Creepers and `/cofh killall pig` would kill all pigs. You can also do `/cofh killall *` to KILL ALL LIVING THINGS!!! Mwuhahahahah!

**Comment by Krysommor** [comment]
Thank you, i will bare that in mine, as committing suicide using the command /kill @e[type:idiot] was getting boring =)
