### ISSUE TITLE
Rev2: v2.1.1.0 new world crash

### ISSUE THREAD

**Issue by Krysommor** [Haggle1996/RevolutionPack#204]
I was just going to play in a single player world and set up a new world when this happened.
http://paste.ee/e/SYyVX
I was trying to load a world that was realistic and i have from 8Gb to 10Gb dedicated to play with Java 1.8.0_71. please can you look into the crash. the share code i was using was:  uLatK53n

**Comment by Haggle1996** [comment]
Try rebooting the machine. It looks like the GalactiCraft bug many of us are experiencing at the moment, where GalactiCraft fails to unload a dimension upon restart and leaves a copy of itself running. We're patiently awaiting a fix from the GC folks.

**Comment by Haggle1996** [comment]
@Krysommor, if you'd like, I can give you access to the dev server. It will help us narrow down where the bottleneck is in your situation. I know the dev server works well.

**Comment by Krysommor** [comment]
It would help,  Thank you
