### ISSUE TITLE
Rev 2 server: Ore gen 2.1.1.0

### ISSUE THREAD

**Issue by Krysommor** [Haggle1996/RevolutionPack#206]
while Nodecraft was trying to get my server back online they said in the ticket i sent in that the Ore generation was Crashing the server.
[crash-2016-02-03.txt](https://github.com/Haggle1996/RevolutionPack/files/116230/crash-2016-02-03.txt)
Here is the crash log to see what is going on there.

**Comment by Haggle1996** [comment]
The error indicates you ran out of RAM. The stack trace does look suspiciously like a recursion issue, but COG ore gen is known to have complex stacks while generating its veins. Is it possible to upgrade the Java version?

**Comment by Krysommor** [comment]
it has to be updated via the server download files as Nodecraft does not support ftp and me uploading files could corrupt them.

**Comment by Haggle1996** [comment]
Closing this, since I need the level seed to test further. If you or someone else encounters this again, please post a new issue.
