### ISSUE TITLE
Galaxy Space Crash Solution

### ISSUE THREAD

**Issue by Joshi120** [Haggle1996/RevolutionPack#209]
o/ Haggle after some research i found a solution for the crash 

Galacticraft Core Config:  http://pastebin.com/s9Dgetj0

Galaxy Space Dimensions Config : http://pastebin.com/0EdSfQS3

**Comment by Haggle1996** [comment]
Awesome! Thank you very much for tracking that down. I will get it into the next update.

**Comment by Joshi120** [comment]
Np :) i made a pull request but i am not sure if i did it right :D first time working with github

**Comment by Haggle1996** [comment]
Looks right. I'll merge the request when I'm back home. Thank you very much for doing this as a pull request. Saves me a bunch of time.

**Comment by Haggle1996** [comment]
Fixed.
