### ISSUE TITLE
No seeds from Harvest Craft plants (default config)

### ISSUE THREAD

**Issue by sassenach1** [Haggle1996/RevolutionPack#211]
Is it intentional that in harvestcraft.cfg that B:enablecroptoseedRecipe is set to false by default? It seems neither intuitive nor engaging to require one to mutate all of ones seed stocks past the starting set of vanilla plants.

**Comment by Solego** [comment]
Yes it is intentional, and we are sorry you feel that way.  If you like, please modify the config file to your taste, but understand that any problems that arise from this change may not be supported.  Thank you.

**Comment by sassenach1** [comment]
That's fair enough. For the sake of documenting this aspect, I can report that modifying the line in question achieves the desired change with no immediately obvious side effects

**Comment by Haggle1996** [comment]
While it may seem like a good idea to make seeds from crops, instead of from agricraft clippings, if you understand how seeds work in Agricraft, why would you want to lose out on higher value seeds? If I grow an 8/8/8 soy plant, harvest it, then turn the crop into a seed, I have a 1/1/1 soy seed instead of another 8/8/8. Having the option off prevents confusion.

**Comment by sassenach1** [comment]
I fear there may be something I'm missing in the agricraft system regarding propagation. Something to look into. 

Ah yes, apologies, neither had I followed the mechanic of spreading of crops to it's logical conclusion or realised one could use clippers. Sorry to have been a nuisance.

**Comment by sassenach1** [comment]
Ah yes, apologies, neither had I followed the mechanic of spreading of crops to it's logical conclusion or realised one could use clippers. Sorry to have been a nuisance.

**Comment by Haggle1996** [comment]
No worries! :)
