### ISSUE TITLE
ForgeEssentials World Border

### ISSUE THREAD

**Issue by DannyIsAJoo** [Haggle1996/RevolutionPack#213]
Tried following the [Pregenerating a World](http://revolutionpack.info/article/rev2-tips/) but kept getting errors. Looks like Forge Essentials build [1146 ](http://ci.forgeessentials.com/job/FE/1146/changes)changed worldborder and it broke. I downgraded to [1145 ](http://ci.forgeessentials.com/job/FE/1145/changes) and it seems to be working.

**Comment by NachtRaben** [comment]
Somewhere on the ForgeEssentials wiki there is a section saying that configs usually don't survive between updates and that when updating ForgeEssentials you should regenerate all your configs and reconfigure your custom settings, like your world border.

**Comment by Haggle1996** [comment]
Fixed in next update by reverting to 1145.
