### ISSUE TITLE
Fence crafting recipe conflict

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#214]
Playing Rev2.  There are two spruce gates recipes.  Right now, the game prefers malasis doors, which doesn't connect to et futurum spruce fences.

**Comment by Aivech** [comment]
Fences should connect to any adjacent block.

**Comment by RaineAndrews** [comment]
Except things like cobblestone walls, iron bars, and Malasis door spruce gates

**Comment by Haggle1996** [comment]
I've addressed this by removing et futurum fences and gates. Will be in the next patch.

**Comment by Haggle1996** [comment]
Nevermind, I've decided to address this by changing the recipe for et futurum to require et futurum fences instead of planks.

**Comment by Toksyuryel** [comment]
Thank you for changing your mind about disabling them :) I'm using et futurum fences in the outpost I'm building XD

**Comment by Haggle1996** [comment]
Feel free to disagree with me. Sometimes I have a thought and it's not a good one. :)
