### ISSUE TITLE
Questbook Mistake

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#216]
Tilting Spears at Windmills: has you craft wind vanes 8 times, but you only need to craft it 4 times for the 8 wind vanes you need.  In essence, you have twice the amount of vanes you need if you follow the quest book.

**Comment by Haggle1996** [comment]
Depends on how you do it. It counts it differently depending on whether or not you click or shift click.

What was worse, it was set to 6 in the previous update. :D

**Comment by Haggle1996** [comment]
This is fixed in the next update.
