### ISSUE TITLE
Obelisk issue

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#217]
Thaumcraft issue, obelisks collapse on themselves when blocks are updated, the floating part of the obelisk doesn't "attach" to adjacent blocks, so accessing the Outer lands will be impossible, as eldritch eyes need to be placed upon the central altar which causes a block update, causing the obelisk to collapse and preventing its use.

This means the primordial pearl (end game thaumcraft) is not accessible.

**Comment by Haggle1996** [comment]
I'll get this fixed in tomorrow's patch.

**Comment by Haggle1996** [comment]
And I appreciate all the issues you're logging. Makes it easy to play bug whackamole.

**Comment by RaineAndrews** [comment]
No problem.  I have your GitHub open ready for the next one (its a beta after all)

**Comment by Haggle1996** [comment]
Fixed in 2.1.3.0
