### ISSUE TITLE
Rockhounding Mod related Crashes

### ISSUE THREAD

**Issue by GrandmasterJax** [Haggle1996/RevolutionPack#218]
Several various problems and crashes are occurring while working with the rockhounding mod. as well as a few related bugs: https://gyazo.com/6b3eb4b4e3c8122dbbb54f378938497b
[crash-2016-02-06_17.45.25-client.txt](https://github.com/Haggle1996/RevolutionPack/files/120515/crash-2016-02-06_17.45.25-client.txt)
[crash-2016-02-07_01.02.05-server.txt](https://github.com/Haggle1996/RevolutionPack/files/120517/crash-2016-02-07_01.02.05-server.txt)
All within the Frozensoul server

**Comment by Haggle1996** [comment]
Reported at http://minecraft.curseforge.com/projects/rockhounding-mod/issues/1490

@GrandmasterJax, if you can please work with the author to resolve this, that would be appreciated. There's not much I can do about mod bugs except to shovel them over the wall to the mod author, and then they typically have questions that I don't necessarily have the answers to (but you would).

**Comment by badgernz** [comment]
Ill give him a hand with this

**Comment by Haggle1996** [comment]
Fixed in the next update.
