### ISSUE TITLE
Update Magical crops

### ISSUE THREAD

**Issue by ShadowXx** [Haggle1996/RevolutionPack#22]
Zivicio armor's flight is stupidly broken and unreliable. This is fixed in beta 3

Yes i realise this will delete any vanilla crops in world, but theyre not hard to replace are they, just more of an inconvenience.

**Comment by Haggle1996** [comment]
The author renamed all of the IDs in his update to beta 3. Unfortunately,
in 1.7.10, what this does is shift all the ID's above the original magical
crops IDs and then re-adds them to the end of the list. Usually, when you
delete a mod, you get the 'yes' to continue anyway warning. With magical
crops 3, forge just responded with 'your world is too corrupt to continue -
delete the offending mod to continue';.

I'm working to find a resolution that will work for everyone (not just on
our server) -- but after 12+ hours on this update, I wanted to push what
was working.

**Comment by Haggle1996** [comment]
Updating magical crops. Users will need to click 'yes' to update the map, or run their server map once in SSP to update it.

**Comment by ShadowXx** [comment]
Woot,!!
