### ISSUE TITLE
Crash to desktop while right clicking a pear in agricraft

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#220]
http://paste.atlauncher.com/view/f5ed0f72

**Comment by OmegaCenti** [comment]
I was physically right clicking on a pear in a tree with an iron sword in hand

**Comment by Haggle1996** [comment]
It's an inventorytweaks error. Nothing I can do about it. Not sure which option is altered, but it looks like you got auto sort turned on and it couldn't find a space for the item.
