### ISSUE TITLE
CustomOreGen Memory Leak

### ISSUE THREAD

**Issue by devryb** [Haggle1996/RevolutionPack#222]
This is causing the pack to be unplayable.
Is there a reason you aren't using cofh to generate the ores instead of this?

http://puu.sh/mYBK3/cb47ec33e0.png

Pack version: 2.1.2.0

**Comment by Toksyuryel** [comment]
COG is required by Harder Ores, and Harder Ores is awesome. You can restart the server periodically to help with the memory issue, and it won't be such a problem once players aren't generating as many chunks.

**Comment by Aivech** [comment]
For this kind of oregen, CoFH Core would make the game unplayable.

The reason worldgen on Rev|1 was 1/3 Plant Mega Pack, 1\3 ATG, and 1\3 CoFH Core oregen.

**Comment by Haggle1996** [comment]
If you can, allocate more RAM to Minecraft. I recommend 6GB for SSP, 4 is really minimal and requires frequent restarts. At 6GB, it's rare to go out of memory, unless you're generating a huge number of chunks.

Also, please be aware, that the memory usage is only high during world generation. Once chunks are generated, pack memory is relatively low.

Closing this issue. As others pointed out, we cannot use CoFH, as COG is a hard dependency of Harder Ores.

**Comment by devryb** [comment]
It's a server set to 8GB
Even with 3 people on the issue is pretty bad.
I set its restarts to hourly, hopefully that helps
