### ISSUE TITLE
Dirt and stone keep falling???

### ISSUE THREAD

**Issue by zakman9797** [Haggle1996/RevolutionPack#224]
Why is my dirt and stone blocks falling? when there suppose to be floating??? i even had my stone fall and turn into cobblestone?? after i just smelt them???

**Comment by Toksyuryel** [comment]
Perhaps before playing a new modpack you should learn about it and read through its modlist?

**Comment by zakman9797** [comment]
i checked the modlist? idk 1/4 of the mods? the rest i knew... i just wana know whats it called... its cool... makes minecraft more realistic?

**Comment by Toksyuryel** [comment]
This place is for reporting issues with the pack- mostly bugs, sometimes feature requests. To have a discussion about the pack, try the forum thread or the irc channel. The pack comes with a built-in IRC client that automatically connects to the irc channel, if you haven't disabled it just open the chatbox and press shift+tab to start chatting to it.

For reference, the mod that adds the physics is enviromine. It's also the mod that rots your food.

**Comment by zakman9797** [comment]
thank you... for the help for the issue.. also eiraic is broken for me... idk why... it just never wants to load... and i don't know where the forum thread is...

**Comment by Toksyuryel** [comment]
Forum thread is here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mod-packs/2411393-revolution-2-an-hqm-rotarycraft-themed-progression
