### ISSUE TITLE
Shaft Power to RF conversion rate in Energy Acceptor incorrect, and not receiving bonus

### ISSUE THREAD

**Issue by Toksyuryel** [Haggle1996/RevolutionPack#225]
Feeding 65kW into an energy acceptor is reading as 116.44 RF/t and 58.22 AE/t.
Feeding 126 RF/t into an energy acceptor is reading as 70.91kW and 63 AE/t.

**Comment by Aivech** [comment]
What about the ME controller?

**Comment by Toksyuryel** [comment]
Powering the ME controller is nearly identical to powering the energy acceptor. The rounding is a little different but not by a meaningful amount.

**Comment by Haggle1996** [comment]
Something is up with the ratio, so I'll get it fixed today.

**Comment by Haggle1996** [comment]
Something is wrong with this on AE's side. Increasing the ratio decreases the amount of AE/t. Decreasing the ratio decreases the amount of AE/t. Seems like it's dividing the default instead of replacing it.

**Comment by Haggle1996** [comment]
Fixed this by nerfing RF, instead of buffing RoC
