### ISSUE TITLE
Worktable Quest issue

### ISSUE THREAD

**Issue by Joshi120** [Haggle1996/RevolutionPack#226]
Crafted items inside the worktable won't count for the quest progress tested with a Copper wire coil

**Comment by Haggle1996** [comment]
This is going to be ugly. Need to change all of the crafting quests to detection quests.

**Comment by Joshi120** [comment]
sry D: so just to make sure i tried it with another quest too: same result :/

**Comment by Haggle1996** [comment]
Noted this issue on the welcome screen known issues list. I may delay it's implementation until I add another chapter to the quest book.

**Comment by Haggle1996** [comment]
Changed them all. :(
