### ISSUE TITLE
Crash to ATLauncher

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#227]
MissAmyPenguin was exploring a beach when it suddenly crashed.  Has been happening a lot with her.  Had her reinstall and verified pack code to match server's modlist.  I don't even know where to begin with crash logs, so I hope these help.

[crash-2016-02-07_08.46.02-client.txt](https://github.com/Haggle1996/RevolutionPack/files/120776/crash-2016-02-07_08.46.02-client.txt)

[fml-client-latest.txt](https://github.com/Haggle1996/RevolutionPack/files/120778/fml-client-latest.txt)

**Comment by Haggle1996** [comment]
Is this a similar case, @RaineAndrews? SleepyTrousers/EnderZoo#103

**Comment by RaineAndrews** [comment]
Highly unlikely, we don't have ender mobs installed

**Comment by Haggle1996** [comment]
The client log shows EnderZoo is enabled. If your server doesn't have it, this is the exact issue. The installed mod list must match the server's mod list -- particularly mods that add mobs, as their ID mismatches are not handled gracefully like items in Forge.

**Comment by Haggle1996** [comment]
Feel free to comment here if this is not the case, and I'll reopen.

**Comment by RaineAndrews** [comment]
confirmed, her mods were all jacked up.  Share code must have been put in wrong.
