### ISSUE TITLE
Tried updating the server to 2130, added galaxy space to it, crashes on attemted launch of server. 

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#229]
https://gist.github.com/anonymous/da61b699904faee3f00c

**Comment by Haggle1996** [comment]
I assume this is an existing map you're adding GS to? Out of question, does it launch fine with a new map?

**Comment by Haggle1996** [comment]
You need to delete your previously existing Galaxy Space folders, as the dimension ID's needed to be changed. The list of folders to delete from your save folder are:
- DIM-45
- DIM-23
- DIM-31
- DIM-24
- DIM-21
- DIM-11
- DIM-12
- DIM-16
- DIM-14
- DIM-15
- DIM-25
- DIM-13
- DIM-33
- DIM-43
- DIM-44
- DIM-9
- DIM-10
- DIM-41
- DIM-40
- DIM-5
- DIM-18
- DIM-31
- DIM-8
- DIM-32
- DIM-17
- DIM-20
- DIM-6

EDIT: This will, of course, delete anything you made on those planets.

**Comment by fearmig** [comment]
I have deleted every dimension other than DIM-1 and DIM-112 and I'm still getting the same issue.

**Comment by Haggle1996** [comment]
Reinstall the pack. There's an alternative version of Galaxy Space in there that I just swapped in.

**Comment by fearmig** [comment]
Its a server.. are u saying just keep the world file and reinstall the rest?

**Comment by Haggle1996** [comment]
Yes, just a pack reinstall, leave the world folder there. There's an updated Galaxy Space (version 1.0.6.1) that will download instead of the crashing version.
