### ISSUE TITLE
Entity Error 

### ISSUE THREAD

**Issue by LordIconMC** [Haggle1996/RevolutionPack#23]
When right clicking a RotaryCraft Steam Engine with any item in your hand a message appears to the user. Might take more then 1 click. I think rotary craft is trying to see if it will go into the fluid slot as if i was holding a bucket of water. 
![screen](https://cloud.githubusercontent.com/assets/10004239/7558612/ec169e9a-f76d-11e4-9f12-3856fdb04a00.png)

**Comment by LordIconMC** [comment]
Also i noted that the slot number changes on 2nd testing i was getting slot 19

**Comment by Haggle1996** [comment]
I can't reproduce this problem. Whenever I right click on a RotaryCraft Steam Engine, I get the steam engine gui.

**Comment by LordIconMC** [comment]
here is a short vid showing 

https://youtu.be/gEz-vFKVG30

**Comment by Haggle1996** [comment]
This is probably caused by you having inventory tweaks set to auto-sort inventories on open...if not, its probably another mod providing similar functionality.
