### ISSUE TITLE
Buckets too easy?

### ISSUE THREAD

**Issue by jkuball** [Haggle1996/RevolutionPack#230]
Hey! I just started Revolution 2 and I'm some hours in. In the `Personal Log-Day 1`-Questline is the second last quest `My Kingdom for a Bucket!` which states you can finally make a bucket (after building a rolling machine).

But now, with Immersive Engineering you can make a Bucket just with an Engineer's Hammer and three Iron Ingots - and you get the hammer in the middle of the questline. I don't think that's intentional, so you might want to deactivate the Iron Ingot + Engineer's Hammer recipe?

(Edit: Playing Revolution 2, just updated today to `2.1.3.0-BETA`)

**Comment by Aivech** [comment]
Looking thru MineTweaker scripts...

**Comment by Aivech** [comment]
I don't see a recipe specifically indicating the ability to make iron plates with the Engineer's Hammer, so this may be unintended.

**Comment by jkuball** [comment]
Yeah, I should've specified the exact way of crafting it. In this pack you can make a bucket with 3 `plateIron`, but you can make one with the Engineer's Hammer + Iron Ingot. So, you can make the bucket recipe exclusively use the Railcraft Iron Plates or just deactivate the making of the Immersive Engineering's Iron Plates.

(By the way, the same thing applies to hoppers, cauldrons, IE fluid pipes.. Disabling the recipe might be the best way. The IE Iron Plates don't seem to have an exclusive recipe, everything can be built with the Railcraft Iron Plates instead.)

**Comment by Aivech** [comment]
@Haggle1996 I should have forewarned you about this because I knew about the upcoming change, but I forgot :P

**Comment by Haggle1996** [comment]
I didn't get to it in yesterday's release, but I already have a task to remove all plate creation from the hammer. That said, buckets are common in chest loot.

EDIT: I have a whole slew of changes around the new plate machine in IE. Mwuhahahahahaha!

**Comment by Aivech** [comment]
> EDIT: I have a whole slew of changes around the new plate machine in IE. Mwuhahahahahaha!

[NOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!!!!!!!!!!](http://www.nooooooooooooooo.com/)

**Comment by Aivech** [comment]
Oops

**Comment by Haggle1996** [comment]
So I've settled on a less dramatic solution. You can still make plates with the hammer, but they take 2 ingots instead of 1 and you can only make 10 plates before the hammer breaks. The Metal Press gives you 1 plate per ingot, so it's a good cost savings. I've also removed plate creation from the rolling mill. If you need a railcraft plate, just put a single IE plate in the crafting grid and it converts back and forth for free.

This will be in the next update. I also modified the Rolling Mill quest to have you make an IE metal press instead.
