### ISSUE TITLE
SPAS-12 textures still broken

### ISSUE THREAD

**Issue by Toksyuryel** [Haggle1996/RevolutionPack#231]
Fix was provided in #180; repeating here.

In file GunCus/WholyGunCustom/guns/SPAS12.cfg, change `S:Texture=spas12` to `S:Texture=SPAS12`

**Comment by LemADEC** [comment]
This is fixed in next update, thanks for the reminder :).

**Comment by Haggle1996** [comment]
Added and fixed.
