### ISSUE TITLE
Harder Ores in crusher give wrong amounts

### ISSUE THREAD

**Issue by Taraxus** [Haggle1996/RevolutionPack#235]
As title says, in an Immersive Engineering Crusher all Hard Iron Ore is giving 8 raw ore, regardless of metadata or remaining ore in block. Will check other ores as I find them.

**Comment by Haggle1996** [comment]
It's slightly more nefarious...whatever the first metadata item is, the crusher will return that amount of that ore regardless of the metadata of subsequent items. For example, if the first ore you place in the crusher has a metadata of 4, it will return 20 raw ore for all subsequent ore, regardless of metadata. It varies per ore type, meaning the first copper ore processed affects all copper; the first iron ore processed affects all iron, etc.

**Comment by Haggle1996** [comment]
BluSunrize/ImmersiveEngineering#952

**Comment by Haggle1996** [comment]
Fixed in hotfix. Will apply a permanent fix later.
