### ISSUE TITLE
Mana pylons should probably be exempt from gravity.

### ISSUE THREAD

**Issue by Taraxus** [Haggle1996/RevolutionPack#236]
Mana pylons, while functioning correctly with support, look a bit strange. As they are intended to float by Botania, they should probably be exempt from falling.
![pylons](https://cloud.githubusercontent.com/assets/16113299/12960613/ccffde3c-d001-11e5-80af-0fb70ec3ac39.png)

**Comment by Aivech** [comment]
I exempted them, let me go check for syntax errors...

**Comment by Aivech** [comment]
And...the config is completely empty.

**Comment by Aivech** [comment]
Fixed it with https://github.com/Haggle1996/RevolutionPack/commit/cbc98f9fdbfbdee3dfbe09ae81f10801bcdd0465

#BlameHaggle https://github.com/Haggle1996/RevolutionPack/commit/2b39d6a5e635619aa32d4c48fe4f4b7dbfeaade4
