### ISSUE TITLE
Food reward on "juiced sapplings" quest rot

### ISSUE THREAD

**Issue by DorinnB** [Haggle1996/RevolutionPack#238]
Food reward from juiced sappling rot instantly.
quest give 3 differents fruits. Next quest ask 7 sapplings (3 come from those fruits). I don't think it's intended or should be specify on quest "so bad those reward rot ... you have to find fresh one."

other's quest reward do not rot.

**Comment by Aivech** [comment]
IMHO it would be better to just give the saplings.

**Comment by Haggle1996** [comment]
Fixed in the next update.
