### ISSUE TITLE
VAT crash on healing chicken

### ISSUE THREAD

**Issue by fwsGonzo** [Haggle1996/RevolutionPack#239]
https://gist.github.com/fwsGonzo/d91ddd451854cf188e34

Chicken is vanilla mob. Crash when trying to heal chicken in VAT. All relevant parts are of the same mod.
Unfortunate, as it crashes on startup now. I guess there is a forge option to remove erroring entities.

**Comment by Aivech** [comment]
Something is going awry when Dynamic Surroundings tries to do the heal splash for the chicken.

**Comment by fwsGonzo** [comment]
https://github.com/OreCruncher/BetterRain/issues/71

**Comment by Aivech** [comment]
Now we wait for updates.

**Comment by Aivech** [comment]
From the linked issue: 

> Set "Damage Popoffs" to false in your config - should do the trick. Looks like the event coming through the event system has bad data in it.  -OreCruncher

This should work as a temp fix for anyone else who is having this problem.

**Comment by Aivech** [comment]
Leaving this open so anyone else with this crash can see the workaround.

**Comment by Haggle1996** [comment]
I will either deploy the temp fix or the update, whichever comes first, this weekend.

**Comment by Haggle1996** [comment]
Fixed in next update.
