### ISSUE TITLE
Blast furnace executes incorrect recipes.

### ISSUE THREAD

**Issue by NachtRaben** [Haggle1996/RevolutionPack#244]
MineTweaker entry:
`mods.immersiveengineering.BlastFurnace.addRecipe(<minecraft:iron_ore>,<HarderOres:ore_chunk:8> * 4, 1200, <minecraft:cobblestone>);`
Expected behavior:
When the furnace contains 4 raw iron ore chunks the recipe will start and produce 1 iron ore.

Actual behavior:
When the furnace contains 1 raw iron ore chunk the recipe will start and produce 1 iron ore.

Note:
Any input amount (1-4) will produce 1. Input values exceeding 4 will process 4 at a time as intented.

**Comment by Haggle1996** [comment]
Fixed in the next update.
