### ISSUE TITLE
When I walked into a new desert area "HarderWildlifes" lizards seem to cause instant crash

### ISSUE THREAD

**Issue by zachaqsw** [Haggle1996/RevolutionPack#245]
[Crash Report](http://pastebin.com/YywtnzhQ)
I walked into unloaded desert area and crashed, when reloading it would instantly crash. After some time of disabling mods i found when disabling lizards in HarderWildlifes config it fixed the issue. So from the same save/crash point enabling lizards would cause crash and disabling lizards would fix it.

**Comment by NachtRaben** [comment]
We need a crash log to help you.

**Comment by zachaqsw** [comment]
I think I have the link posted let me know if i messed up. Also this is a similar problem to closed issue #192. This maybe a known issue with lizard spawns or something but still seems to be causing problems in the pack.

**Comment by Haggle1996** [comment]
There's option in forge configuration to delete errored entities.

**Comment by NachtRaben** [comment]
I was viewing on mobile, the log link didn't form on my phone. Sorry about that.

**Comment by Haggle1996** [comment]
@Draco18s, can you comment on this and/or #192? This appears to be releated to Harder Wildlife lizards, as I've not seen it with other mobs, but this is subjective.

**Comment by Draco18s** [comment]
Interesting. If I could get a world save (with mod list or an entire MultiMC instance) that could help. I'll be taking a look at this this evening, so I may not need it.

**Comment by Haggle1996** [comment]
Modpack is here: https://www.atlauncher.com/pack/Revolution2

@zachaqsw may have a world save they're willing to zip and send to you.

**Comment by zachaqsw** [comment]
@Draco18s [World Save](https://mega.nz/#!mkJSwBAR!qhLsT69V19BekcZk6h1TX-5-KRY91Mkn3qZ2dTez0oo) That's the world save that just crashes when loading the world and its the Revolution 2 modpack version 2.1.3.0-BETA-HOTFIX2 with the default mods

**Comment by Draco18s** [comment]
Oh fsk.
I know what's going on here.  And it's _really god damn annoying._  I may not be able to fix it.  It has to do with multiple animals being targeted and trying to pick the better one based on how much meat will drop.  But that value is random, so the comparison method is non-transitive. :\
(That is, if A > B, and B > C, then A > C.  But it is turning out that C > A)
I'll see what I can do.

**Comment by Haggle1996** [comment]
Possibly fixed in the next update.
