### ISSUE TITLE
Activation Ritual for Division Sigil in Extra Utilities seems to be broken.

### ISSUE THREAD

**Issue by Taraxus** [Haggle1996/RevolutionPack#247]
Shift-right-clicking on an Enchantment Table gives no information, and attempting to execute the ritual results in nothing happening when you kill a mob.

**Comment by Aivech** [comment]
Pack version?

**Comment by Taraxus** [comment]
Dev server, 2.1.3

**Comment by Haggle1996** [comment]
rwtema/extrautilities#783

**Comment by Haggle1996** [comment]
Fixed by removing the Et Futurum enchanting table. This is not the preferred solution, but there are many ways to enchant gear in REV|2, but only one way to activate the division sigil
