### ISSUE TITLE
Modular Powersuits missing recipes.

### ISSUE THREAD

**Issue by Taraxus** [Haggle1996/RevolutionPack#250]
Modular Powersuits is missing recipes for the following items:
Carbon Myofiber 6749:13
Myofiber Gel 6749:15
Artificial Muscle 6749:16
Solar Panel 6749:17
Magnet 6749:18
Computer Chip 6749:19
Insulated Rubber Hose 6749:20
Liquid Nitrogen Bucket 6749:21

**Comment by Haggle1996** [comment]
Thanks, I'll get these worked on.

**Comment by Haggle1996** [comment]
Resolved by Haggle1996/RevolutionPack#261
