### ISSUE TITLE
Pneumaticraft PCBs should be crafted in a machine like the Assembly Table

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#251]
Pneumaticraft content needs to be gated past early game. A suggestion was to use the BC table, but I'm open to other suggestions.

**Comment by Aivech** [comment]
Make the initial compressed iron require the Rotarycraft compactor instead of TNT (is such a thing possible with MineTweaker or Reika's mod API?)

PCB's are already enough of a pain to make.

**Comment by Haggle1996** [comment]
Compressed iron is already gated -- you have to make it on the Ender IO Alloy Smelter until you can make it with Pneumaticraft machines. Making it with TNT results in 100% ingot loss. :)

**Comment by Aivech** [comment]
Look at the UV Light box for PCB gating, then.

**Comment by Aivech** [comment]
> DaMachinator 21:39
> For PCB gating, I suggest using the UV Light Box. If my information is correct, it requires 1 PCB Blueprint (ordered from Amadron), four Compressed Iron, one tier 0 Pressure Tube, and 3 Redstone Lamps.
> I suggest replacing 1 or 2 of the redstone lamps with Inductive Ingots.

My revised suggestion in better wording from Gitter

**Comment by Aivech** [comment]
This has been open for a few months, I assume what needed to be done has been done.
