### ISSUE TITLE
Headcrumbs heads should work as Endermen heads for Ender IO recipes.

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#252]
As the Ender IO-compatible endermen heads are relatively rare, it's been suggested to make the headcrumb mob heads also work for Ender IO recipes, as though they were EIO Endermen heads. As the mobs are fairly rare, it shouldn't unbalance EIO.

**Comment by Aivech** [comment]
This is also a problem in v1.0. I made a cleaver to get the heads and was...disappointed...at the result.

**Comment by Haggle1996** [comment]
They're already usable as zombie heads, which means they're good for Z-logic controllers, etc. This would be a lot of work to remove and re-add them as Endermen heads. Leaving as is, as it's pretty easy to kill endermen en-masse. I went to the ender spawner in a roguelike dungeon and got 4 using my M9 (since endermen don't teleport when shot).
