### ISSUE TITLE
Crop sluice guide images

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#253]
The images @Solego took for the sluice's in-game noob guide need to be cropped, so it's not obvious they were taken on linux. The images for the windmill chapter are sized properly, for reference.

**Comment by Aivech** [comment]
I would do this if I had any idea how to download them properly...

**Comment by Haggle1996** [comment]
They're stored on disk in the modpack folder.

**Comment by Aivech** [comment]
I don't have the modpack folder downloaded.

**Comment by Aivech** [comment]
I'll try the "save image as" trick.

**Comment by Aivech** [comment]
It worked, but the GitHub web interface isn't enjoying my attempts to upload an image.
