### ISSUE TITLE
Immersive Engineering metal parts should be made on the Metal Press

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#254]
Suggested by Toksyurel, IE metal parts should be made on the Metal Press. Obviously, care should be taken so that the press isn't rendered uncraftable.

**Comment by Taraxus** [comment]
Seems that perhaps removing the rolling machine would be the solution here. It looks like you'd have to change quite a bit to make the press craftable without the hammer, but this would require the Metal Press for automation. Maybe bump up the damage done to hammer by crafting plates, if that's possible?

**Comment by Haggle1996** [comment]
I removed plates from the rolling machine, so they can only be crafted on the IE metal press. You can still make plates with the IE hammer, however, I changed it to use two ingots instead of one, and the hammer can only be used to make 10 plates instead of the default 100. I believe it makes using the hammer inconvenient enough that someone would want to build the Metal Press, without having to change a lot of recipes.

Also, I've increased the number of items that use metal plates, so there's even more demand for them.

**Comment by Haggle1996** [comment]
I should clarify that these changes are forthcoming in the next update. They're not in place yet.

**Comment by Taraxus** [comment]
Sounds like a winner to me. The extra efficiency definitely encourages moving to the Metal Press, instead of just sacrificing hammers to the Steel Plate God.

**Comment by Haggle1996** [comment]
OmegaCenti has made remaining items more expensive when crafted by hand. Metal press saves you ore.
