### ISSUE TITLE
Food rots at appropriate speeds

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#255]
Go over all the food in the pack and apply 'makes sense' rules to Enviromine's rotting speed. For example, alcohol should not rot, emergency rations should rot slowly, and fresh fruit and veg around a week, and meat around a few days. Meals and Feasts should rot faster. If necessary, add a custom profile to HarvestCraft if food values need to be adjusted.

You can add blocks to Enviromine's configuration files (located in config/enviromine/profiles/default/CustomProperties/<modname>.cfg by unbinding all non-enviromine commands from the J key, then holding the food in your hand and pressing SHIFT+J. In the following menu, choose the option for just items (not blocks -- you would use blocks for adjusting physics). Then open the related config file and alter the values.

Do not make any superfoods -- e.g., an easy to craft, slow or non-rotting foods. While realism is important, it's better to keep food balanced.

And, as always, look for gating opportunities that encourage progression and infrastructure. See #151 for earlier details.

**Comment by Aivech** [comment]
I think I'll do some of this while /mt hand-ing for bees.

Also, pretty sure root vegetables like potatoes and beets and carrots can last several months in the right conditions.

**Comment by Haggle1996** [comment]
Root vegetables are usually a few weeks at most, depending on environment. They are used for winter food storage, but they're kept in cool, dry places for that -- like a fridge or freezer. No more than two or three weeks, I'd say, but definitely the right direction.

**Comment by Aivech** [comment]
According to this, white potatoes last around a month (4 weeks, 30 days) in the pantry: 

http://shelflifeadvice.com/vegetables/fresh-vegetables/potatoes

As white potatoes are the kind most commonly called "baked potatoes" when prepared in that manner, I am assuming MC potatoes are white potatoes.

**Comment by Aivech** [comment]
Carrots, beets, radishes, turnips: 2 weeks when refrigerated.

What is the fridge decay slowdown multiplier?

**Comment by Haggle1996** [comment]
I was referring to the in-game fridge/freezer blocks. IRL, it's the moisture in the fridge that kills them.

**Comment by Aivech** [comment]
General rule for freezers is 6 months vintage freezer, 1 year modern freezer or vintage deep freezer.

**Comment by RaineAndrews** [comment]
I should note that Pam's Harvestcraft Honey should not spoil.  Honey is one of the only edible foods that can't spoil, due to its low water content and high acidity.

**Comment by Haggle1996** [comment]
I've done a first pass on this. Honey, Mead, Mana Beans, Jerky, Emergency Rations, Zombie Brains, Gluttony Shards. If there's anything important I missed, create a new issue. For the most part, as long as rotting is enabled at all, there's no huge enjoyment for the player to have something last 2 weeks instead of 1.
