### ISSUE TITLE
Rod of the Plentiful Mantle doesn't see Harder Ores

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#256]
This is due to how IE and Botania handle Ore Dictionary Items. I'm working on this issue already with the respective mod authors (involves some amount of begging).

**Comment by Aivech** [comment]
Yay! I recently discovered the awesomeness of this item in a different pack :grinning:

**Comment by NachtRaben** [comment]
Based off what I've seen vaskii say, only ores with a metadata of :0 will be detected, and that it will not be considered in a fix. Another way around this is to create an oreDic entry containing all the HarderOres ores, but inadvertently this can cause conversion(Jabba, StorageDrawers Autoconversion) issues unless we specify an orDic entry for every mine-able level of every individual ore either through HaggleTweaks or MT.

**Comment by Haggle1996** [comment]
By default, the harder ores are already in an ore dictionary entry. The problem is that Immersive Engineering caches recipes based on their presence in an ore dictionary. This is what led to the blast furnace problems with whatever metadata was tossed in first, all subsequent ore was treated as having that metadata. I can't add just a single metadata to the ore dictionary because the world generates with different metas. I suppose I could create a separate ore dictionary for each variant of each ore...e.g., oreHardIron0, oreHardIron1, oreHardIron2, etc...

**Comment by NachtRaben** [comment]
That was what i was implying earlier.

**Comment by Aivech** [comment]
That sounds like a pain...

**Comment by Haggle1996** [comment]
Fixed in the next update.
