### ISSUE TITLE
Immersive Engineering connectors fall to the ground

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#257]
When placed on the bottom of machines, they fall to the ground. They need custom physics entries (set to none). See #255 for instructions or adding items to Enviromine's custom profiles. Note that you'll select the Block entry, instead of item.

**Comment by Aivech** [comment]
Didn't we set physics to a whitelist rather than a blacklist?

**Comment by Haggle1996** [comment]
We did, and the default stability type is 'none'. I didn't observe or test this behavior, it was just reported in IRC. They may have been on an older version.

**Comment by devanchya** [comment]
This was on Hotfix2, so latest release.  can reproduce.

If you put a item NEXT to the attachment, it will stay in the air.   Under and item with no other blocks on the sides will fall.

**Comment by Haggle1996** [comment]
Fixed in the next update.
