### ISSUE TITLE
RotaryCraft Book Error

### ISSUE THREAD

**Issue by LordIconMC** [Haggle1996/RevolutionPack#26]
If you look at an item that is crafted using planks. There is 1 plan that is not skinned correctly see image 1. if you click on that image it will output an error to the user. see screenshot 2 

![screen3](https://cloud.githubusercontent.com/assets/10004239/7558856/ce7cfe60-f772-11e4-9e98-0435ebe4e9a0.png)

![screen2](https://cloud.githubusercontent.com/assets/10004239/7558845/ca30ef38-f772-11e4-86b0-1307495731d2.png)

**Comment by Haggle1996** [comment]
If I find the missing texture, I'll add a dummy one in (or remove the item from the oredict). In the mean time, don't click on purple/black-boxed things. :)
