### ISSUE TITLE
Review mod blocks for which ones should fall.

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#260]
Go through the list of blocks and add Enviromine entries for blocks that should fall. By default, they have physics of 'none', which mean they will fall if directly unsupported (no touching blocks), but otherwise stick.

Some examples: Chisel cobblestone blocks should be set to 'average'. Stone blocks should be set to 'strong'.

**Comment by Aivech** [comment]
Some blocks, namely ones designed to go on all sides of a block, may need "glowstone" physics type.

**Comment by oxinabox** [comment]
Off the top of my head: anything from the Catwalks mod should be set to 'strong'.
(or at least stronger than they are. It is odd having them collapse)

Channels from Agricraft should be stronger (or really, much lighter, but idk if that is defined).
Otherwise you have to support your sprinker system every 4 blocks or so

Its may be worth tweaking things so that no generated structures are weak enough to collapse.
On the otherhand that does go with the 500years vibe.

**Comment by RaineAndrews** [comment]
The Frozensoul spawn uses floors exclusively made of Carpenter's Blocks since they seem to have no physics at all ^.^

Probably not intended though...

**Comment by RaineAndrews** [comment]
I was looking into stabilities, and Agricraft Channels need their own stability category.  Maybe something like:

```
    stuctural {
        B:"01.Enable Physics"=true
        I:"02.Max Support Distance"=6
        I:"03.Min Missing Blocks To Fall"=22 'honestly, not sure what this is'
        I:"04.Max Missing Blocks To Fall"=25 'or this'
        B:"05.Can Hang"=true
        B:"06.Holds Others Up"=true
    }
```

The alternative would be to use glowstone, but by nature disables physics

**Comment by AMartinie** [comment]
Also, prevent openblock elevators from falling due to physics. By jumping on an elevator, both the elevator you are jumping from and the one you are jumping to will update and cause them to fall.

**Comment by Aivech** [comment]
> Also, prevent openblock elevators from falling due to physics. By jumping on an elevator, both the elevator you are jumping from and the one you are jumping to will update and cause them to fall.

Nonissue because elevators can jump thru up to 4 solid blocks.

**Comment by AMartinie** [comment]
> Also, prevent openblock elevators from falling due to physics. By jumping on an elevator, both the elevator you are jumping from and the one you are jumping to will update and cause them to fall.
> Nonissue because elevators can jump thru up to 4 solid blocks.

eh, personal preference I guess.

**Comment by Aivech** [comment]
Are they falling in the latest update?

When I said it was a nonissue I meant you could put support blocks underneath without interfering with tis functionality.

**Comment by AMartinie** [comment]
I'll have to try later, I put slabs under them and stopped worrying about
it

**Comment by Haggle1996** [comment]
All mods in here (with the exception of elevators) have been addressed in the next update.
