### ISSUE TITLE
Concrete - Immersive Engineering vs Chisel

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#263]
The Immersive Engineering recipe is 4 Slag, 2 Clay Ball, 2 Gravel, 1 water bucket.   Chisel concrete is a smelted Gravel.

Granted Concrete is used mostly for cosmetics, but it gives a speed boost when walking on it.

Low Priority Recipe sync.

**Comment by Toksyuryel** [comment]
These are not the same kind of concrete.

**Comment by devanchya** [comment]
The forge ore table treats them the same as far as the Chisel mod is concerned.   The IE Concrete does not have the speed boost, and is harder to make.    It appears to have a higher blast level though...

**Comment by devanchya** [comment]
Note:  I know different recipes have different uses for mod.  Haggle has mentioned in the past of wanting to know about them, but don't know what extent.

**Comment by NachtRaben** [comment]
I can understand having multiple types, I was not aware of the chisel treating them equally though.
Should have said that in the IRC after i joined :P

**Comment by Haggle1996** [comment]
If I were to do anything with this, it would be to make the IE concrete cheaper. As you can Chisel other concrete to get it, I'm fine doing nothing with it.
