### ISSUE TITLE
Make it easier to make and edit custom recipies with MineTweaker

### ISSUE THREAD

**Issue by Aivech** [Haggle1996/RevolutionPack#264]
http://minecraft.curseforge.com/projects/minetweaker-recipemaker

Suggest adding this to development version of pack.

**Comment by Haggle1996** [comment]
I tried it a while back. It's more cumbersome than editing the .zs files directly, and was (at least back then) missing a lot of the functionality. I suppose it might be useful for someone who truly has a hard time learning to write zscript, but as a software engineer, it slowed me down. It's clientside only, so anyone is welcome to use it.

**Comment by imkSushi** [comment]
Actually, in stead of Minetweaker, I use Loot++

**Comment by Aivech** [comment]
Weel, we use Minetweaker and Modtweaker for nearly everything recipe-related. (NOTE: "Recipe" also includes things not usually done on the crafting table, like Thaumcraft infusion and EnderIO alloying)
