### ISSUE TITLE
Various Moon-related issues v2.0

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#266]
Three issues found thus far:
The gravity on the Moon seems to be Earth-strength for the player with relation to jump height and fall time.
The Galacticraft oxygen meter does not appear when on the Moon.
When using night-vision on the Moon, everything is pitch-black.

**Comment by Aivech** [comment]
When using night vision in the End, its like using a color inverter, in the Nether, everything is red. That's a vanilla effect caused by the skybox and the fog color.

**Comment by Haggle1996** [comment]
Gravity and Night Vision should both be reported on the GalactiCraft issue tracker. I've moved the oxygen meter to the bottom left corner, so it's not overwritten by JourneyMap.
