### ISSUE TITLE
Immersive Engineering Steel -> Railcraft Steel, not Oredict commpatible

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#267]
Trying to build a Arc Furnace, and took my Immersive Engineering Steel and put it into crafting table to make a block (3x3 block recipe).  This creates a RAILCRAFT Steel Block.   This cannot be used to make the Arc Furnace.
Putting into a JABBA barrel with a cheated in Immersive Engineering Steel Block does not allow it to be changed.  Appears the OreDict sees them as separate products.

**Comment by NachtRaben** [comment]
Have you checked for a shapeless 1 to 1 conversion in the crafting grid of the steel block? We've had many people build arc furnaces already on the dev server that haven't said anything about this.

**Comment by devanchya** [comment]
I've checked and the Blast Furnace can create IE Steel blocks.   I am testing to see if this was the problem for sure...

**Comment by NachtRaben** [comment]
Thats what i ended up doing was converting blocks of iron in an improved blast furnace.

**Comment by devanchya** [comment]
Created the steel using the Blast Furnace, and put them into the Arc build and it worked right away.
So this is confirmed, the IE Arc Furnace does not recognize Railcraft Steel.

**Comment by NachtRaben** [comment]
I wouldn't expect the recipe to check the oredic.

**Comment by Haggle1996** [comment]
Tested and fixed.
