### ISSUE TITLE
Placing vanilla anvil damages it?

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#268]
Is this intended?  I crafted an anvil, placed it, (it switched to et futura anvil if that is relevant) and it is already slightly damaged with no use!

**Comment by Aivech** [comment]
Let me load up a vanilla 1.9 instance and place some anvils, and I'll tell you.

**Comment by Aivech** [comment]
I don't think this is intended, I placed a stack or so of anvils and none of them were damaged unless they fell several blocks first.

**Comment by RaineAndrews** [comment]
Every iron anvil I placed vanilla or otherwise is placed as slightly damaged, something is going down!  Enviromine physics?  It doesn't fall, but maybe it logs the placement as a fall?

**Comment by Haggle1996** [comment]
If you can figure out what causes it, I'll see if it's fixable.

**Comment by Haggle1996** [comment]
Most likely et futurum. Regardless, turned off et futurum anvils fixes the problem.
