### ISSUE TITLE
Mod pack wont allow me to mine blocks

### ISSUE THREAD

**Issue by GingerSnapples** [Haggle1996/RevolutionPack#269]
I just started a new game and when I go to mine using anything (my hand, book, wood pickaxe, ect.) the block will break but it doesn't produce anything for me to pick up. I have checked and I know  I am not in cheat mode so I don't know what else could be the issue or how to fix it.

**Comment by Haggle1996** [comment]
Try restarting Minecraft. If the issue persists, try reinstalling the instance.
