### ISSUE TITLE
Rotarycraft Extractor ignoring mod ores.

### ISSUE THREAD

**Issue by Muddel** [Haggle1996/RevolutionPack#27]
Well, our RC Extractor is ignoring all mod ores(even Electricraft ones). and i think it used to work before in this Modpack. 

-Muddel

**Comment by Haggle1996** [comment]
I've confirmed this is happening in the latest version of the pack. I will get a fix out soon.

**Comment by Haggle1996** [comment]
Looks like we are waiting on a fix from Reika cf ReikaKalseki/Reika_Mods_Issues#48 and ganymedes01/Another-One-Bites-the-Dust#46

As soon as RoC v7 releases, I'll update the pack.

**Comment by Haggle1996** [comment]
Another option is to remove AOBD. This restores the original functionality of the grinder.

**Comment by Haggle1996** [comment]
I've gone ahead and removed AOBD from 0.6.3 (the only change). AOBD is a convenience mod, and since it interferes with RoC, I'm just going to pull it for now.

**Comment by ganymedes01** [comment]
You could leave AOBD and just turn off the RotaryCrash integration in its config file :3

**Comment by Haggle1996** [comment]
True... pushing 0.6.4 with AOBD. Thanks gany!

**Comment by ganymedes01** [comment]
my pleasure :)
