### ISSUE TITLE
wooden bucket's of creosate can't make treated wood

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#270]
Is this intended?

**Comment by NachtRaben** [comment]
The wooden bucket equivalents of like water/milk/etc aren't ordictionary with their iron bucket counterparts. For what you're suggesting, i use glass bottles because they're reusable and stack in the crafting table.

**Comment by Haggle1996** [comment]
It's intended. You're only supposed to be able to make milk and water with the bucket.
