### ISSUE TITLE
Server Installation

### ISSUE THREAD

**Issue by boxkiteboy1** [Haggle1996/RevolutionPack#272]
Hello my name is boxkiteboy1 and I am trying to install your pack on my server but it isn't working I need your help if possible.

**Comment by Haggle1996** [comment]
You need to provide a log, crash log, error report, or description of the problem.

**Comment by boxkiteboy1** [comment]
The Problem is that I can't get the Forge server jar to work I use AKLIZ interface to load it but when I start it up it encounter some problem and won't work so Oh and I got no crash report either. I just got some players who are really want to play this pack on our server but I can't get it to run.

**Comment by boxkiteboy1** [comment]
I can tell the interface to use the minecraft jar but that causes other issue and I believe doing so makes it not load mods right anyways because you need the forge for that.

**Comment by boxkiteboy1** [comment]
I look at all the other modpack I had installed on akliz and all them them use the Forge Jar as the base installed jar

**Comment by boxkiteboy1** [comment]
Oh and a lot of the other packs don't have Launcher bats when it runs them.

**Comment by Haggle1996** [comment]
You'll need to talk to Akliz for information on setting up AT Launcher packs on their servers. REV|2 doesn't do anything different when it comes to Forge server installations.
