### ISSUE TITLE
Physics complicate horizontal crystal repeater construction

### ISSUE THREAD

**Issue by Toksyuryel** [Haggle1996/RevolutionPack#275]
The crystalline stone is fine, it's the runes that are the problem. Their stability (or maybe it's the support capacity of the crystalline stone? or the weight of the runes? I have no idea how this works) needs to be increased slightly to prevent them from falling when placed against the second crystalline stone block. The crystal repeater block itself does not seem to have physics, but it might be good to doublecheck and verify that it absolutely cannot fall under any circumstances since if it does that will likely lead to world corruption.

**Comment by Aivech** [comment]
This should be fixed now that physics only applies when we tell it to.
But if it isn't...

**Comment by Haggle1996** [comment]
Yeah, I asked Tok to add this. I'll add a special exception for them.

**Comment by Haggle1996** [comment]
This is fixed in the next update.
