### ISSUE TITLE
Rev 2 Crash

### ISSUE THREAD

**Issue by mrdomrocks** [Haggle1996/RevolutionPack#276]
When you click on the required aspect in nei for thaumcraft recipe the whole game crashes to desktop.

**Comment by Haggle1996** [comment]
I need a crash log, but probably a duplicate of #205.

You can find the crash log in your crash-logs folder inside your REVOLUTION|2 instance folder.

**Comment by mrdomrocks** [comment]
Here is the crash log.

http://pastebin.com/V1EvaUYN

**Comment by Haggle1996** [comment]
Was this an upgrade from a previous version of REVOLUTION?

If so, delete your \saves\NEI folder (this just clears the NEI cache).

**Comment by mrdomrocks** [comment]
Yeah installed the latest beta this evening. Will remove the cache and update this thread.

**Comment by Haggle1996** [comment]
Closing. Comment here again if you're still encountering the problem.
