### ISSUE TITLE
Treecapitator should not trigger for Natura redwoods

### ISSUE THREAD

**Issue by Toksyuryel** [Haggle1996/RevolutionPack#277]
These are a popular choice for building treehouses but currently chopping at them with an axe has... consequences.

**Comment by Haggle1996** [comment]
Holding shift while chopping should only chop the current block.

**Comment by Toksyuryel** [comment]
Didn't know that! Probably makes this issue invalid, though I'd like to suggest that this feature should be noted down in the quest that wants you to chop down a tree.

**Comment by Haggle1996** [comment]
I'll add it to my note list. :)
