### ISSUE TITLE
Add IE heater compatibility with modded furnaces

### ISSUE THREAD

**Issue by AMartinie** [Haggle1996/RevolutionPack#278]
Immersive Engineering does not have the compatibility to power furnaces that are inside Ewy's Workshop. I [submitted](https://github.com/BluSunrize/ImmersiveEngineering/issues/971) a request to Immersive Engineering's Issue tracker to get him to add compatibility in future updates, but currently if we want the issue resolved we have to allow it manually and patch it again every time that we update IE, which will become a huge pain.

**Comment by Haggle1996** [comment]
You can also power the tables with RF, or install the solar cell.

**Comment by NachtRaben** [comment]
BlueSunrize has already stated that he is going to leave it up to Ewy to add the support him/herself through his api, that it isn't his priority.

**Comment by Haggle1996** [comment]
Closing, as this isn't something I can change, it would need to be implemented by either Ewy or BluSunrize.
