### ISSUE TITLE
Quest Book Chapter 3 issue

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#280]
Quest Book Chapter 3: Personal Log Day 38
Quest: Is Your Steel Dark?

There is no completion parameter available for the second detection task, thus making the quest impossible to complete.  From the context, it seems having some dark steel should complete it; however holding 32 dark steel ingots does not trigger the quest detection.

**Comment by Haggle1996** [comment]
This is fixed in the update.
