### ISSUE TITLE
Server can't keep up with ticks

### ISSUE THREAD

**Issue by cmann21** [Haggle1996/RevolutionPack#283]
Just wanting to know why a server I run can't keep up with ticks...The cpu usage is average well over 85% and even after removing the optional plugins, it will not stabilize. can someone help or should I just not run a server for this modpack?

**Comment by Aivech** [comment]
Revolution|1 or Revolution|2? Pack version? World type?

**Comment by Haggle1996** [comment]
Also, server details? RAM allocated? CPU? Are you hosting with a 3rd party provider? Have you tried just restarting it?

**Comment by IceT2000** [comment]
Hi there, greetings from Germany, just startet in this "Awesome" Modpack........
......regardless of the Server Hardware, I had the same Problem. 
AMD A10 7850K 16GB Ram 256GB SSD, 6GB alloc. to java !
The Server skipped about 2000 to 2500ms every 20 Seconds.
The fallowing Java args. made my Day (and my Server) ;)

java -Xmx%mem% -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui

all this in the same Line

Keep up your serverticks ;)
IceT

**Comment by cmann21** [comment]
Revolution 2 and I do use a third party (beastnode) ram is 4900 mb and cpu is just the java software. not sure what hard ware they use for cpu. I did restart it a dozen times but still runs very high...Hope this help I really want to run this modpack on a personal server. Thank you for any help

**Comment by cmann21** [comment]
since i run a third party server host im not sure how I would enter this argument?

**Comment by Aivech** [comment]
Call their support and ask them to do it for you.

**Comment by Haggle1996** [comment]
@IceT2000 if you have more RAM available than 6GB, I would allocate it, at least while chunks are generating. World generation is very expensive in REV|2. The 7850K is a somewhat underpowered [CPU ](http://www.cpubenchmark.net/cpu.php?cpu=AMD+A10-7850K+APU&id=2133), so I wouldn't expect you to be able to support more than a few players.

@cmann21 you're even more limited on RAM. You may want to explore a world in creative mode on single player (with as much RAM as you can allocate to Minecraft) to pregenerate chunks, then upload the map to your server.

In the end, you'll need to get support from your server host, as there are far too many unique situations and configurations. REVOLUTION (both versions) are heavy packs -- I run and test them on my own server with players, and that's about the best I can do to support server environments.

**Comment by cmann21** [comment]
@Haggle1996  Thank you for you response and help!

**Comment by Haggle1996** [comment]
Sorry I can't be of more help. :)
