### ISSUE TITLE
grip recipe not working

### ISSUE THREAD

**Issue by DFAReaper** [Haggle1996/RevolutionPack#284]
playing on the at launcher server going through the "clearing the lands" quests and now i have to craft 1000 ak 47's.... i have the resources, but the NEI says "recipe changed due to conflicts with 5373:5" (steel rod) but the recipe the NEI lists is the one for steel rods... i can purchase the grips from the server market, but i don't want to spend 20K.... help with the recipe?

**Comment by Aivech** [comment]
Did you try crafting just one with the ~~normal~~ given recipe?

**Comment by DFAReaper** [comment]
i've tried multiple recipes with no luck. the base recipes that i can find, the pattern for the wooden grip with iron and steel. no luck

**Comment by Aivech** [comment]
Did you try the recipe that NEI tells you?

**Comment by DFAReaper** [comment]
yup, it crafts "steel rod 5375:15" from immersive engineering

**Comment by DFAReaper** [comment]
just for kicks tried using a wooden grip in place of the metal grip. no love

**Comment by Aivech** [comment]
Revolution|1, correct?

**Comment by DFAReaper** [comment]
yup

**Comment by Aivech** [comment]
I thought @Haggle1996 fixed this some time back...

**Comment by Haggle1996** [comment]
No, this is still on my bug list for REV|1. The last Immersive Engineering update broke the minetweaker script.

**Comment by DFAReaper** [comment]
any workaround at the moment?

**Comment by Haggle1996** [comment]
If you're playing on a server you don't control, not really. You'll need to contact your admin to either offer an alternative recipe or another mechanism for obtaining the item in-game. If you're in single player, you can modify the minetweaker script to use an alternative recipe.

**Comment by Haggle1996** [comment]
Fixed in the next update.
