### ISSUE TITLE
Revolution 1 crashing

### ISSUE THREAD

**Issue by Legoman6500** [Haggle1996/RevolutionPack#285]
So I'm playing like normal and my game crashed. Now it wont let me into my world, some dimension error. Please help, I've restarted minecraft and ATLauncher so many times and ive even restarted my pc

**Comment by Haggle1996** [comment]
Assuming you didn't disable AromaBackup, you should have backups of your game in the \backups folder in your Revolution instance (click Open Folder from the AT Launcher instances list). Just unzip the last one to a new folder in your instance's \saves folder and load it. Outside of that, there's nothing I can do about corrupted worlds.
