### ISSUE TITLE
Some Chromaticraft Blocks become Unmineable after they Fall

### ISSUE THREAD

**Issue by RemedialTester** [Haggle1996/RevolutionPack#288]
Certain Blocks in Chromaticraft after they fall, from being unsupported, become unminealbe.The blocks I've had this happen to are; the Casting table, Casting stand and the Chroma Collecter. Each one reacts differently as well:The Casting Table will lose it's levels, Casting stands seem to not have additional effects and the Chroma Collecter fails to work after falling.

**Comment by Haggle1996** [comment]
Unfortunately, I can't do anything about this specific series of blocks. They're implemented in a non-traditional way by the author. General rule of thumb: if it's expensive, don't drop it.

**Comment by Haggle1996** [comment]
I figured out how to handle these. My apologies. This is fixed in the next update.
