### ISSUE TITLE
Rotarycraft v11b Cant charge the Industrial Coils

### ISSUE THREAD

**Issue by t3rraz** [Haggle1996/RevolutionPack#289]
After the update from Rev 2.2.0.0 Beta to 2.3.0.0 the industrial Coils doesnt Charge, before it was fine. they stop around 13k.

**Comment by oxinabox** [comment]
I'm using an industrial coil, without issue.
I think I built it after the update to 2.3.0.0.
Try deconstructing it, and re-placing it down.

**Comment by Haggle1996** [comment]
This behavior is correct. As of v11, the industrial coils maximum charge is based off of the amount of torque supplied.

**Comment by Aivech** [comment]
I thought it was always that way :D

**Comment by Haggle1996** [comment]
It was always _supposed_ to be that way. It's been broken for a while.
