### ISSUE TITLE
BigTrees generating logs with bad metadata

### ISSUE THREAD

**Issue by Melakion** [Haggle1996/RevolutionPack#29]
I've come across several BigTrees with Dark Oak wood named Acacia Wood. This makes the logs unusable for any crafting, and only lets you smelt them to charcoal. (And also confuses my axe which won't take the whole tree at once.)

Looking in the bigtrees/treeconfigs/GreatOakDark.cfg shows that they are using log2 with a meta of 3, which is invalid.

Haven't looked through the other tree configs to see if there are other incorrect entries.

**Comment by Haggle1996** [comment]
Thanks for reporting! This is fixed and will be released in the next version of the pack. The fix will only address new trees. Existing trees will remain with their invalid metadata values.

**Comment by Haggle1996** [comment]
Note, you can fix this in your world by running the following command:
/cofh replaceblocks Haggle1996 500 100 500 162#1 162#3

Replace 'Haggle1996' with your IGN. Please note, the 500 100 500 indicates a cuboid 500x100x500 blocks. This will take a few minutes on a decent machine. If you select a radius outside with ungenerated chunks, this process will generate them, so use with caution. It will severely lag minecraft while performing this operation.
