### ISSUE TITLE
Breaking a decobench deletes blocks

### ISSUE THREAD

**Issue by steviej1801** [Haggle1996/RevolutionPack#291]
To reproduce:
Place a decobench in the world and then break it. Place some blocks in the same place where the decobench used to be. Place the decobench somewhere else and then break it. It will delete blocks from where it was originally placed and broken. Also, the area where you placed the bench the 2nd time (and anywhere else) is now vulnerable to the same bug.

Lost a few chests full of things after sprucing up the base due to this, thought I was going crazy!
Tested in multiplayer server on survival as well as single player in creative.

**Comment by Aivech** [comment]
Revolution|1 or Revolution|2? Pack version?

**Comment by Haggle1996** [comment]
It's REV|2, and after a good night's sleep, I think I know how to fix these errors. HOTFIX tonight!

**Comment by Haggle1996** [comment]
This should be fixed in the 2.3.0.1 HOTFIX. Note that previously stuck blocks may or may not be perma-stuck. Try building something underneath it, then remove it to get them to fall again.
