### ISSUE TITLE
Iron ingot to Pneumaticraft Compressed Iron Ingot in the alloy smelter (EIO)

### ISSUE THREAD

**Issue by b0bst3r** [Haggle1996/RevolutionPack#292]
Please please please for the love of god change the recipe so when you put iron in the alloy smelter it doesn't just grab it and make compressed.  

Consider adding gunpowder to the recipe (which kinda makes sense from how you make it initially).

**Comment by Haggle1996** [comment]
Will implement using tnt.

**Comment by Aivech** [comment]
You can make as many stacks of compressed iron as you can place before they start despawning with 1 TNT...

**Comment by Haggle1996** [comment]
That's turned off. You can't make compressed iron by exploding iron.

**Comment by Aivech** [comment]
I know, I meant normally.

**Comment by Haggle1996** [comment]
I wanted to gate Pneumaticraft behind steel, but there's no way to change the recipe for compressed iron, except to turn it off.

**Comment by Aivech** [comment]
I know, its annoying...

Where's my flying car?

**Comment by Haggle1996** [comment]
This is fixed in the next update.
