### ISSUE TITLE
I know haggle's tight but

### ISSUE THREAD

**Issue by b0bst3r** [Haggle1996/RevolutionPack#293]
Come on, no rewards?

http://postimg.org/image/vx3gslu4p/
http://imgur.com/2ZPUxny

![screenshot_633](https://cloud.githubusercontent.com/assets/2760085/13399812/02465526-defd-11e5-98a2-9ddf8e422472.jpg)

**Comment by Aivech** [comment]
I can't see the picture...

**Comment by Haggle1996** [comment]
Neither can I. You tease!

**Comment by b0bst3r** [comment]
added a 2nd imgur image lol

**Comment by Aivech** [comment]
Pretty sure you can upload images directly by dragging and dropping them directly onto the comment box.

**Comment by b0bst3r** [comment]
oooh snazzy so you can

**Comment by Haggle1996** [comment]
![image](https://cloud.githubusercontent.com/assets/11808184/13556661/c41879ce-e39c-11e5-9f75-e57c55c0e8d9.png)

This is fixed in the next update.
