### ISSUE TITLE
revolution2 - v2.3.0  worldgen is missing all harder ores.

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#294]
Generating a new world (RTG) doesn't include any of the extra harder ores (copper, silver etc..)
A work around is to use the COG options at world creation time to force the extra ores.

Limonite looks broken as well.

Vanilla, Chisel, AE, Forestry generate.

Did not confirm that ReactorCraft generates as expected

**Comment by Haggle1996** [comment]
Try reinstalling the pack. Occasionally, ATLauncher errors out when downloading the configurations (it says this in the log window, but unfortunately doesn't say any further messages). I'm 100% certain the configurations are there to generate the ore.

**Comment by romanticjo** [comment]
Same issue after a re-install.

**Comment by NachtRaben** [comment]
Purge your ATL Cache and downloads folder.

**Comment by romanticjo** [comment]
I've removed the downloads folder and installed a new instance, with the same result.

**Comment by Haggle1996** [comment]
I will be pushing a hotfix for this in a couple of hours.

**Comment by Haggle1996** [comment]
My development zip has the right values, but the one I'm pulling from github and atlauncher is missing the settings. I will fix this as soon as I'm onsite.

**Comment by romanticjo** [comment]
With 2.3.1-hotfix, I see the extra ores along with copper flowers.
