### ISSUE TITLE
Blast Furnace makes slag instead of cobblestone

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#295]

**Comment by Aivech** [comment]
Hasn't it always? You use slag to make IE concrete :grinning: 

Also, realism.

**Comment by Haggle1996** [comment]
With raw ores, it makes cobblestone, not slag.

**Comment by Aivech** [comment]
Oh. Well, that sounds cool.

**Comment by Haggle1996** [comment]
Changed in the next update.
