### ISSUE TITLE
/home set command no longer works in single player no cheat mode

### ISSUE THREAD

**Issue by AMartinie** [Haggle1996/RevolutionPack#296]
returns a "set is not a valid home!" error or whatever. Patch notes don't mention any change so I can't see why it would be removed.  

edit: also "/home del" doesn't work either. /home list works though..

**Comment by Haggle1996** [comment]
The command is `/sethome <name>` and `/delhome <name>`. Both work fine for me.

**Comment by AMartinie** [comment]
Weird. I have 15+ homes set using /home set XXX. I also tried sethome and the command didn't work, granted I'm on single player no cheat.

**Comment by Haggle1996** [comment]
`/home set` is added by ForgeEssentials, which is no longer included in single player due to the map corruption problems with SSP (it was only intended for pregeneration). 

FTB Utilities adds the /sethome command, but it does require cheats enabled.

**Comment by AMartinie** [comment]
Damn. Thanks for clarification.

**Comment by Haggle1996** [comment]
The Player Relocator from refined relocation is a relative inexpensive way to provide /home-like teleportation without cheats. Requires iron, redstone, and a bit of diamond, but no RF.
