### ISSUE TITLE
Malisis Trapdoors don't work for crafting Enhanced Inventories locker

### ISSUE THREAD

**Issue by jesmores** [Haggle1996/RevolutionPack#297]
Mildly annoying, started with some spruce logs, spruce planks recipe makes the malisis trapdoor, which isn't mapped to the recipe for lockers. Have to find an oak tree.

**Comment by Haggle1996** [comment]
This is a huge amount of script to add all the trapdoors to the ore dictionary and modify all the items that don't use the trapdoor ore dictionary. As many non-vanilla woods make an oak trapdoor, this isn't a big deal to work around. Won't fix.
