### ISSUE TITLE
Hard freeze, couldn't get a crash log off of it I think. Repeatability test: Have an ME system, search for mill with NEI synchronization auto on, then search for axle, hard freeze ensues 

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#299]
https://gist.github.com/OmegaCenti/cbf8931ca1f9e5af1693

**Comment by OmegaCenti** [comment]
I found that it is actually x that crashes me
typing x in nei
confirmed on two different computers in ME with nei synchronization

**Comment by OmegaCenti** [comment]
T3rraz  "i had the same prob. too, was when a item with the letter x in the name was in the me"

**Comment by Haggle1996** [comment]
You ran out of memory:
`java.lang.OutOfMemoryError: Java heap space`

**Comment by OmegaCenti** [comment]
Haggle, it is immediately triggerable

**Comment by OmegaCenti** [comment]
I've now allocated 10 gigabytes to minecraft, lets find out!

**Comment by Haggle1996** [comment]
You snipped all the important parts of the log out, all I'm left with is the out of memory error from exhausting the heap, not what caused it to loop infinitely.

**Comment by Aivech** [comment]
Does it happen with NEI synchronized standard?
