### ISSUE TITLE
BiblioCraft Oak Bookcases NEI

### ISSUE THREAD

**Issue by LordIconMC** [Haggle1996/RevolutionPack#3]
there are Bibliocraft oak bookshelf that don't have a recipe. There are 3 that show up in a search ID:763 is creative mode only and should not be displayed in NEI

**Comment by Haggle1996** [comment]
After sleeping on this one, I'm going to leave it in place. Hiding a creative-mode item means someone in creative mode will have to manually lookup the item's name or ID to add it to their inventory. However, I opened a ticket at Nuchaz/BiblioCraft#279
