### ISSUE TITLE
Looking in achievements, looking at immersive integration, Crash to desktop

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#301]
https://gist.github.com/OmegaCenti/9667d40a20cdcab3ca82

crash log:
[crash-2016-03-03_11.19.35-client.txt](https://github.com/Haggle1996/RevolutionPack/files/157293/crash-2016-03-03_11.19.35-client.txt)

**Comment by Haggle1996** [comment]
Please report these to the mod author. I can't do anything about them.
