### ISSUE TITLE
Rockhounding decorative blocks can be made with Chisel

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#302]
Instead of needing to craft the grinder, simply allow Rockhounding decorative blocks to be placed into the Chisel UI and craft their respective blocks.

**Comment by Aivech** [comment]
Sounds cool.

**Comment by oxinabox** [comment]
As someone who is using a lot of rockhounding blocks. I would actually say no. (which is unusual as normally I am pro-integration and promaking things easy).
The rockhounding rock cutter has its own distinct and interesting set up. It uses resources which do take effort to get. I've almost wornout my first cutting disc, and it is a slight worry for me where I am going to get the resource for another. (Harder ores is hard yo, and I need that metal for rotorycraft).

Sure Chisel does get expended too, but it doesn't have the complexity of also needing fuel, and gridding grit.

I use blocks, Barriers, tiles (/carpets really), and stairs  (Sidenote never use Rockhounding slabs, they do not behave like any other kind of slab, I can open another issue for this).
The cutting statation would i assume still be needed for moving beyond the plain block, I guess.

On the other hand having all blocks interact consistently is a good thing.
So might be worth depriving people of the first pressure to enter the rockhounding tech chain

**Comment by Haggle1996** [comment]
Will not implement.
