### ISSUE TITLE
Crash breaking agricraft tank

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#305]
https://gist.github.com/romanticjo/aee585f4169ae2ec3751

**Comment by Haggle1996** [comment]
Please report mod bugs directly to the mod author. I can't do anything about them.

**Comment by Haggle1996** [comment]
Also, same as other issue. This is not the full crash log. Crash logs are located in the crash-logs folder inside the minecraft instance.

**Comment by Haggle1996** [comment]
This may have been a result of physics causing part of a tank to fall, messing up agricraft. If so, tanks are no longer affected by physics.
