### ISSUE TITLE
Reika's donor gift not showing

### ISSUE THREAD

**Issue by DorinnB** [Haggle1996/RevolutionPack#31]
V0.7.0
While I have Reika's donor gift (gearbox/node/toroid floating above my head) with v6f, I don't have it  on Revolution modpack.

I'm currently trying to remove mods to find which one disable it, but hard without mods dependencies knowledge.

**Comment by Solego** [comment]
Same here and it's inconsistent.  Sentinal saw Haggle's doner gift, but not mine.  Haggle and I were on screen at the same time during Sentinalh's Lets Play.

**Comment by Haggle1996** [comment]
Appears to be functional again in SSP and SMP in v2.0 of the pack.
