### ISSUE TITLE
Pseudo-Stable Inversion Sigil not working

### ISSUE THREAD

**Issue by darthmichael7** [Haggle1996/RevolutionPack#310]
Normally, shift right clicking a beacon with an activated division sigil will bring up a long line of text describing what else is needed to start the ritual. When I tried there was no text at all, even after setting up the entire rest of the ritual. Not sure if this is a bug or if this was disabled, because there doesn't seem to be a config to disable it and it was not listed as disabled in the gameplay changes. If there is a mod replacing the vanilla beacon that could possibly cause issues.

Confirmed not working in single player in both survival and creative. Using 2.3.0.1-BETA-HOTFIX with share code irnF4rhP.

**Comment by Aivech** [comment]
Possibly try turning off "Beacon Colors" in the Et Futurum config?

**Comment by Haggle1996** [comment]
Yar, seems another thing to turn off in et futurum.

**Comment by Haggle1996** [comment]
Fixed in the next update.
