### ISSUE TITLE
Player takes fall damage from glider

### ISSUE THREAD

**Issue by sp823** [Haggle1996/RevolutionPack#311]
I built a glider (the leather and wood version from OpenBlocks) and if I use the glider it works, but as soon as I touch the ground I die from fall damage as if I just jumped from my original height. I haven't experienced this in other packs that use the OpenBlocks glider.

**Comment by Haggle1996** [comment]
Please report this to the mod author on their issue tracker: https://github.com/OpenMods/OpenBlocks
