### ISSUE TITLE
Bedrock Pickaxe not picking up spawners

### ISSUE THREAD

**Issue by Pandemoneus** [Haggle1996/RevolutionPack#312]
In Revolution 2, I have read (and the RotaryCraft handbook says so in the config changes section) that the bedrock pickaxe is supposed to be able to pick up spawners. However, breaking spawners with it drops the EnderIO broken spawner version.

**Comment by Pandemoneus** [comment]
Nevermind, the server admin changed the config recently, didn't notice that.

**Comment by Haggle1996** [comment]
The pack is pre-configured to prevent the bedrock pick from picking up intact spawners. Your server admin didn't change anything. A full list of pack changes can be found here: http://revolutionpack.info/article/rev2-gameplay-changes/
