### ISSUE TITLE
Forestry Apiarist chest is not craftable (and potentially other items)

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#313]
List of all forestry items I didn't see crafting recipies for: 

https://docs.google.com/spreadsheets/d/1f73b9D8A3U4_bcdd21Fx-n1bjrRo0TYusU_Clsnlocw/edit?usp=sharing

**Comment by Haggle1996** [comment]
I'll add recipes for the bee house, apiarist chest, and stamp collector.

The imprinter is a creative mode item. Proven frames are supposed to be uncraftable (they're obtained by trading with the appropriate villager). Sticky propolis is a bee byproduct to add back when we do bees.

**Comment by Haggle1996** [comment]
ReikaKalseki/Reika_Mods_Issues#674

Unfortunately, I cannot make these craftable at the moment.

**Comment by b0bst3r** [comment]
That "feature" will break all minetweaker scripts with a null in them, can't you just turn that crap off?

**Comment by Haggle1996** [comment]
It doesn't break other recipes using the minetweaker null value.

**Comment by Haggle1996** [comment]
Fixed in the next update.
