### ISSUE TITLE
For Anyone running a remote server with Rev2 2400 on it, see if falling from a great height has you freeze for a significant time and warns in remote console that player ZYX has moved too quickly

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#316]
[latest.txt](https://github.com/Haggle1996/RevolutionPack/files/161418/latest.txt)
Lines 209 to 234

[serverproperties.txt](https://github.com/Haggle1996/RevolutionPack/files/161422/serverproperties.txt)

**Comment by devanchya** [comment]
Confirmed

**Comment by Haggle1996** [comment]
This may be related to #319. Something is taking up excessive server ticks. Based on 319's log, it looks like a machine is autocrafting (or smelting) an object that no longer exists, and is just burning up CPU cycles.

GalaxySpace ores are a prime candidate, but you'll have to figure it out.

**Comment by t3rraz** [comment]
We have the sam eissue, but before we had galaxy space ores found in the galaxy.

**Comment by Haggle1996** [comment]
@OmegaCenti, are you able to determine if this is also a Ewy's Worshop table being used to autocraft items, as described in #319?

**Comment by t3rraz** [comment]
i tryd with a fresh Server and a fresh instance,. still same issue

**Comment by OmegaCenti** [comment]
no ewy workshops are on my server (sorry about late reply)

**Comment by Aivech** [comment]
#351 has same issue.

**Comment by Haggle1996** [comment]
See #351
