### ISSUE TITLE
Enhanced Inventories chests are not movable.

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#318]
Rev2's core chest mod (enhanced inventories) doesn't have dolly support.
- Consider adding  this companion mod which provides a functional dolly:
  
  http://minecraft.curseforge.com/projects/inventory-tools
  Bonus: it provides a player inventory toolbox.
- Consider replacing/adding with a storage mod that allows chests to be moved around.

**Comment by Haggle1996** [comment]
In theory, they should be movable now with the JABBA dolly.
