### ISSUE TITLE
Mod stops loading

### ISSUE THREAD

**Issue by Kayda** [Haggle1996/RevolutionPack#32]
Every time I go to load up the mod it seems to crash and stops loading up below I've attached the the pastebin link with the crash report.

http://pastebin.com/ksU7Ri5t

**Comment by Haggle1996** [comment]
The JurassiCraft authors have shifted things around on their end and this is preventing their mod from loading. We are waiting on a fix today for this issue.

If you absolutely must have your Revolution fix, you can disable the JurassiCraft mod; however, this will remove JC ores from your world and they will need to be manually readded. If you can wait a few hours, I recommend you wait for a fix. I expect to have a workaround later today.

**Comment by Kayda** [comment]
Ok brilliant thank you very much for such a quick response! I've not played it yet, so I'm happy to wait for your full version/vision :) Thank you again

**Comment by Haggle1996** [comment]
I've fixed this with a temporary version of JurassiCraft in 0.8.2. There will be an additional update as soon as the devs push a new version of JurassiCraft.
