### ISSUE TITLE
Power requirements wrong for RoC pump

### ISSUE THREAD

**Issue by sp823** [Haggle1996/RevolutionPack#320]
The RoC pump does not run off 1024W 4Nm (DC electric engine) in this pack as it shows it should in the game and on the wiki. The angular transducer shows that it has enough power to run (no "insufficient power" message) but it does not animate or pump anything until I add more power. Two DC engines connected together with a shaft junction (2048W) got it moving.

**Comment by Haggle1996** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/645

**Comment by TomeWyrm** [comment]
It's actually a torque issue. You could fix this with a 2:1 gearbox
