### ISSUE TITLE
Unable to connect to Revolution 2 from Bungeecord

### ISSUE THREAD

**Issue by Phwaa** [Haggle1996/RevolutionPack#321]
Hi, i am having some issues joining my revolution server(version 2.200BETA) from the hub.
Attempting to join it from the hub gives these errors:
From Bungee: http://pastebin.com/5ai87NVT
From Revolution: http://pastebin.com/k8zcWumU
From Client: http://pastebin.com/MVwm1NVU

This is also how i set up the Bungee config file
http://pastebin.com/uxMFf6z1

I am able to connect directly to the server when i set "bungeecord: false" on the server

**Comment by Haggle1996** [comment]
The snippets you provided don't indicate what is wrong. You will need to contact the bungee author for support.
