### ISSUE TITLE
Crash due to glass cover (forge multi block) placed in practical logistics cable block

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#322]
https://gist.github.com/anonymous/0e443fbc9570c8496897

Would also appreciate solutions that aren't MCEdit to remove a block in a world, preferably from admin command line

**Comment by Haggle1996** [comment]
Please report mod bugs to the mod author directly.

**Comment by Aivech** [comment]
There are vanilla delete commands, however, the server has to be running and the world loaded. I dont think the chunk in question does, though.
