### ISSUE TITLE
Flywheel bug

### ISSUE THREAD

**Issue by Leslie-mp-Williams** [Haggle1996/RevolutionPack#324]
I am hosting the latest revision (2.4) server for me and my friends

We get a bug that whenever you place a Flywheel next to a fuelled Gasolene Engine the server hangs. (Doesn't crash, just freezes) No error reported in the logs or anything

Any ideas?

**Comment by Haggle1996** [comment]
Yes, don't put them next to each other. :D

In past versions of RotaryCraft, we've had issues with machines 'seeing' through other machines, most notably shaft junctions seeing through other blocks like the centrifuge and counting more engines then are actually joined (and then exploding). 

You should report this on Reika's issue tracker.

**Comment by Leslie-mp-Williams** [comment]
Alright cheers :P
