### ISSUE TITLE
Enviromine: Is it just me, or does Enviromine not behave properly anymore?

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#326]
It seems that L/T-Beams from before aren't effective anymore.

Cases where it is true on my server / vanilla-Rev2 single player:

Stone bricks
Spruce Planks

Expected behavior: From central block of L, extend out +3 blocks in the L's arm/anti-arm directions.
Actual behavior: Does not extend or support past initial 3-block L shape.

Please investigate this thoroughly!

**Comment by Aivech** [comment]
In real life, Lbeams dont extend forever.

**Comment by Quantax** [comment]
I think he meant that the L-beam  doesn't support beyond the L-arm.

Expected behavior:
xxxxxx
###
#
#

Actual behavior:
xxx
###
#
#

where x is supported roof and # the L-beam

**Comment by Haggle1996** [comment]
Some of the behaviors have changed, though not intentionally. I suspect a mod interaction problem, but I have no idea what. There was no update to enviromine. In playing on the dev server, I'm not unhappy with the changes, so I'm going to leave them as is.
