### ISSUE TITLE
Clay recipe

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#327]
Consider adding a clay recipe.

There is currently no clay recipe in the pack which makes getting substantial amount of clay for crafting bricks as a building material for end of early game/midgame difficult.

Some ideas:
- Byproduct of crushing things (gravel, dirt etc)
- shaped recipe: dirt, sand, water.

It's worth noting that clay is found relatively easily in the pack because of rivers, but not in substantial enough quantity to consider as a readily available as a building material.

**Comment by Toksyuryel** [comment]
PEBKAC. There are already several methods of producing clay in the pack, including the Botania clayconia and the RotaryCraft centrifuge.

**Comment by romanticjo** [comment]
~~The centrifuge IMO requires a higher tech level than the actual material it
produces.~~
- The centrifuge gives 10% chance of clay for every dirt, that's a very low conversion ratio.

~~The clayconia is viable, although obscure.  It may be a fine solution,
although complicated to automate.~~
- The clayconia is amazing. Should there not be a non-magic way of getting clay effectively?

Stay classy.
