### ISSUE TITLE
Uranium Processor

### ISSUE THREAD

**Issue by Cantankerous-Rex** [Haggle1996/RevolutionPack#328]
Tried to craft this in both workbench and crafting table and did not work.

**Comment by Cantankerous-Rex** [comment]
Same issue with the reactorcraft turbine

**Comment by Taraxus** [comment]
I have crafted both of these items, albeit on an ME crafting interface. Are you playing single-player or multiplayer? Was it the Single-block Reactorcraft turbine?

**Comment by Aivech** [comment]
Pack version?

**Comment by Cantankerous-Rex** [comment]
Pack version 2.4.0.0

Playing Multi Player. Not tried in an AE crafting grid. This was in the vanilla and natura crafting tables and in the workbench.

**Comment by Cantankerous-Rex** [comment]
Made an AE system and tried in an AE crafting grid. No joy.

**Comment by Cantankerous-Rex** [comment]
I think I have sorted it. I am using soartex as a texture pack and the recipe did not display correctly. Got someone else on the server using a different texture pack to make it and all is fine. 

So please close this issue.
