### ISSUE TITLE
Haggle misspelled a thing

### ISSUE THREAD

**Issue by Toksyuryel** [Haggle1996/RevolutionPack#329]
![2016-03-11-140504_577x205_scrot](https://cloud.githubusercontent.com/assets/1735640/13716895/c50f4b74-e792-11e5-907a-47e9a9674e7c.png)

**Comment by Toksyuryel** [comment]
You even spelled my name wrong :P

**Comment by devanchya** [comment]
Well obviously it's your almost twin who knows all, not you.

**Comment by Aivech** [comment]
@Haggle1996 Your input is requested.

**Comment by Haggle1996** [comment]
This will be fixed in the next update.

**Comment by Toksyuryel** [comment]
I'd still like an explanation, when things calm down for you :P

**Comment by Haggle1996** [comment]
It was a token of respect in regards to your vast knowledge of mods and the pack. In many cases, it surpasses my own. If it's bothersome, I can remove it, but it was just meant as a 'thank you'.

**Comment by Toksyuryel** [comment]
Aww, that's sweet of you :) you can leave it in ^_^

**Comment by Haggle1996** [comment]
Fixed in the next update. Thanks for the pull request!
