### ISSUE TITLE
World wont load?

### ISSUE THREAD

**Issue by Kayda** [Haggle1996/RevolutionPack#33]
Hey finally got the modpack to load after the fix you've made with the jurrasicraft (Thank you for the quick update by the way) but now I can't load up a new/existing world.

Below is the pastbin link:

http://pastebin.com/463awJbx

**Comment by Haggle1996** [comment]
I've seen a similar error a couple of times when creating a brand new world -- reloading the game with the same map has always fixed it in the past. To verify, you've tried loading this map twice?

The specific error relates to a redstone comparator inside a roguelike dungeon causing an error when trying to update a neighboring block. I've noticed that SSP minecraft crashes the first time it encounters this error. SMP minecraft logs it, but keeps running. You could also try running the map in a dedicated local server, just to see if you get past the crash.

If you can't get it to work, and its an exiting map you want to save, I'd be willing to load it up in one of my test environments and try to fix the block.

Let me know.

**Comment by Haggle1996** [comment]
No response, closing.
