### ISSUE TITLE
Generation issues

### ISSUE THREAD

**Issue by Evilxor** [Haggle1996/RevolutionPack#331]
I found a few generation bugs while searching for silver flowers (which I still haven't found in a 2000x2000 area around my home by the way).
Here are some screenshots : http://imgur.com/a/qHBib
- Sometimes there are huge holes filled with fully grown carrots and they all pop out when they update (screenshots 1 and 3)
- There are also some areas without any vegetation (screenshot 2)
- I found a lot of cobblestone walls in some streams, but I also found a naturally occuring wall of enderchests and command blocks (screenshot 4)
- A swamp area was inhabited by A LOT of sharks, which caused a huge fps drop (2-3 fps, screenshot 5)
- Finally, all the structures in the pregen area (trees, villages, etc...) are cut in half when they cross a chunk border.

Note : I used "/pregenspawn 100" when starting this world 2 days ago. All those bugs were observed in the pregenerated area.

Revolution 2 version 2.4.0.0 beta

**Comment by Pandemoneus** [comment]
I can confirm that the shark spawn rate is messed up. I had 1500+ sharks in my swamp area. They also spawn in oil. My guess is that the spawn rate is messed up for any biome but oceans, apparently.

**Comment by Aivech** [comment]
For now, disable sharks in the Animals+ config

**Comment by Pandemoneus** [comment]
I would if there was a config. I don't see any config file or folder named AnimalsPlus.

**Comment by Aivech** [comment]
Let me go find where you disable it, there is definitely a way to

**Comment by Aivech** [comment]
Sorry, its in config/enderzoo/SpawnConfig_User.xml

**Comment by Haggle1996** [comment]
Actually, it's in the OpenBlocks.cfg file:

```
additional {
    # List any mob names you want disabled on the server
    S:disableMobNames <
        Whale
        Butterfly
        Cricket
        Centipede
        Moth
        Shark
     >
```
