### ISSUE TITLE
Carpenter's garage doors collapsing onto themselves/duping

### ISSUE THREAD

**Issue by mtesseracttech** [Haggle1996/RevolutionPack#333]
I was trying to make a 3x4 door with Carpenter's garage doors but the door kept collapsing when opened/closed causing the door pieces to fall on the ground (multiple ones instead of 1) and something like that often happens with Malisis' frame doors too, but the door just loses some frames from the middle.

**Comment by Haggle1996** [comment]
Try reinstalling your pack, as these blocks are explicitly exempted from gravity. Sounds like you have a missing config.
