### ISSUE TITLE
Mutant monsters bypassing protection

### ISSUE THREAD

**Issue by mtesseracttech** [Haggle1996/RevolutionPack#334]
A mutant creeper blew a huge hole in my (protected!) base while I was absent.

**Comment by Aivech** [comment]
Claiming chunks doesn't protect you from mobs. Use obsidian or warded glass or something.

**Comment by Aivech** [comment]
Securitycraft has unbreakable blocks, IIRC fairly cheap too.

Try reinforced glass.

**Comment by mtesseracttech** [comment]
Ah, okay. I thought it would be with the pack, seeing that normal creepers don't damage stuff in claimed chunks. But if it's with the server, I will talk to them about it. The admin of the server (someone who knows Haggle) said the mutant creepers bypassed the protection, so that's why I posted here.

**Comment by Haggle1996** [comment]
Yes, this is as designed.
