### ISSUE TITLE
Storage Drawers capacity upgrades aren't craftable

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#335]
![2016-03-13_16 56 41](https://cloud.githubusercontent.com/assets/14045560/13732310/c988ede4-e93c-11e5-8e7a-f24db64655f1.png)

**Comment by Toksyuryel** [comment]
The recipes work, they are just hidden from NEI for some reason. I haven't been able to figure out how to display them, but if you check the recipes in Rev1 they are the same in Rev2 and still work. Same for the drawers themselves, all the wood types that aren't being displayed in NEI are still usable they are just hidden.

**Comment by Aivech** [comment]
That is INpure Culling Engine doing its job and cutting down the number of NEI pages from 600-700 to a few hundred or so.

**Comment by romanticjo** [comment]
All upgrades
![](http://puu.sh/nGg3v/b2dcb0d583.png)

Capacity x2
![](http://puu.sh/nGfJf/128e933cc4.png)

Capacity x3
![](http://puu.sh/nGfOx/4e67e6fa2f.png)

Capacity x5
![](http://puu.sh/nGfPk/664744737a.png)

Capacity x8
![](http://puu.sh/nGfSt/9c1dfa5792.png)

Capacity x13
![](http://puu.sh/nGfTb/c1d46b84c2.png)

Shows full Storage
![](http://puu.sh/nGfW7/0d377fc1a1.png)

Shows fill level
![](http://puu.sh/nGfWY/a206802f12.png)

Void Upgrade
![](http://puu.sh/nGfYb/23e22bf9ab.png)

**Comment by Haggle1996** [comment]
This is fixed in the next update.
