### ISSUE TITLE
Suggestion:  Corpse Decay

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#336]
Currently Corpse don't decay.  a large number of them can cause TPS issue.
currently the B:enable_corpse_decay is set to false.
Recommend it set to True after X hours.  Example below keeps the default 1 hour.
At minimum i recommend empty corpses decay.

lootablebodies.cfg

`
"corpse decay" {
    # Time after death before a corpse will self-destruct (if the
    # enable_corpse_decay option is set to true).
    # The format is hours:minutes:seconds or just hours:minutes [default: 1:00:00]
    S:corpse_decay_time=1:00:00

```
# If true and enable_corpse_decay is also true, corpses will
# self-destruct after being empty for a period of time (will
# not decay if there are any items on the corpse). If using this
# option, you will probably want to also disable the
# add_bones_to_corpse option. [default: false]
B:empty_only_decay=false

# If true, corpses will self-destruct after a preiod of time. [default: false]
B:enable_corpse_decay=true
```

}
`

**Comment by Haggle1996** [comment]
Added in the next update.
