### ISSUE TITLE
Weird Recipe for Ender IO

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#337]
Strange case of putting 2 Vibrant Alloys into the craft window and getting 2 back.   Low Low priority, but its just a bit weird.

![2016-03-15_19 37 44](https://cloud.githubusercontent.com/assets/6947885/13797658/83e81a12-eae5-11e5-9ca6-b445a25c52f8.png)

**Comment by Haggle1996** [comment]
Actually, many mods have something like this for stackable items. I have no idea why. I'm not going to fix it, because it doesn't break anything and it's a can of worms with fixing every other stackable item with a recipe like this.
