### ISSUE TITLE
Mod Interaction: Automagy   *Crystals and stacks on stacks (maybe)

### ISSUE THREAD

**Issue by OmegaCenti** [Haggle1996/RevolutionPack#339]
![2016-03-17_14 43 34](https://cloud.githubusercontent.com/assets/1700516/13858954/f51fd3cc-ec4e-11e5-9a1e-a4d43de05fd0.png)

![2016-03-17_14 44 14](https://cloud.githubusercontent.com/assets/1700516/13858961/fd504c34-ec4e-11e5-9ed9-2d7fde619144.png)

The Automagy Crystals will not place, and their right click behavior is to stack a 2-dimensional tile upwards.

**Comment by OmegaCenti** [comment]
I also tried editing the Stacks on Stacks config file, but removing the string "crystal" and adding blacklists for "RedCrystal" in all categories of blacklist didn't seem to do anything.

**Comment by OmegaCenti** [comment]
![2016-03-17_14 54 18](https://cloud.githubusercontent.com/assets/1700516/13859163/0cd3455c-ec50-11e5-9755-c2fceb904001.png)

3 and a half "stacks" worth of dim red crystals. So pretty!

**Comment by Haggle1996** [comment]
Closed this by removing Stacks on Stacks
