### ISSUE TITLE
Malisis Garage crash

### ISSUE THREAD

**Issue by DorinnB** [Haggle1996/RevolutionPack#34]
I've put a garage door on server (and also tried after on SSP)
crash to desktop and crash when i try to relog.

http://pastebin.com/F4gsgfqp
i have the same crash log everytime i log on

**Comment by Haggle1996** [comment]
I will push out an update tonight for Malisis that fixes the issue. In the mean time, /cofh replaceblocks x1 y1 z1 x2 y2 z2 1#0 2472#3 can be used to fix.
