### ISSUE TITLE
Pseudo-Stable Inversion Sigil ritual still bugged

### ISSUE THREAD

**Issue by darthmichael7** [Haggle1996/RevolutionPack#340]
After updating to 2.4.0.0 I tried again to make an inversion sigil, and everything went well (the beacon fix worked) except the ritual is not accepting the cooked foods due to their enviromine spoilage data. Not sure if there is a way to fix this.
Version 2.4.0.0-BETA
Pack Code 6vY4uH26

**Comment by Haggle1996** [comment]
If this is single player, you can temporarily disable enviromine food spoilage in the config file, and reenable after you complete the ritual. There are also a few foods not subject to spoilage at all, though I forget how they're used in the ritual.
