### ISSUE TITLE
Copper ore absolutely impossible to find.

### ISSUE THREAD

**Issue by celestefox** [Haggle1996/RevolutionPack#341]
Using Revolution|2 version 2.4.0.0, I absolutely cannot find any copper ore. BOP world. I flew around all over and periodically used /cogInfo ._copper._ placedBlocks (which counts the number of blocks distributions place this time the world is open (iron, gold, etc are working and this showed it)) to make sure that no Cooper was being placed, as well as having wireframe drawing for only copper veins and I could not see anything. I've looked through lots of issues and while copper is brought up, I can't see a new issue about this, so reporting it.

**Comment by celestefox** [comment]
I would try to include screenshots but there isn't much you can show when something is missing (plus that's... Currently very awkward for me to take/upload them).

**Comment by Haggle1996** [comment]
1000% positive copper spawns in the pack; however, we've had a couple of players get bad configurations, which a reinstallation and regeneration has fixed. Note, the method you are using to find copper will not yield copper, as the pack doesn't use standard copper distributions or blocks. Use `/oredistribution 100` and look for entries that begin with oreHardCopper. These are copper ore blocks.
