### ISSUE TITLE
EnderIO weather obelisk crashes the server

### ISSUE THREAD

**Issue by Pandemoneus** [Haggle1996/RevolutionPack#342]
Directly after clicking the confirm button in the EnderIO weather obelisk GUI (using Concentrated Cloud Seed as fluid and simple Gunpowder + Paper rockets), the server crashes. Devanchya will provide the crash log.

**Comment by sapid** [comment]
Couldn't reproduce. Do you remember what biome this was in? Are you still experiencing this crash?

**Comment by Flynn1179** [comment]
I just got this as well. Launching from a magical forest (thaumcraft) biome, with 8 buckets of liquid sunshine and a plain rocket. I did get a brief animation of the rocket looking like it was 'filling' with sunshine, seemed to crash as it was due to take off.
