### ISSUE TITLE
ReactorCraft Pebble Bed Reactors do not function in v11.

### ISSUE THREAD

**Issue by Cantankerous-Rex** [Haggle1996/RevolutionPack#343]
This is to make you aware there is a bug in DragonApi that means reactocraft versions 11 cause Pebble Bed Reactors to never be able to heat up enough to actually work. Design doesn't matter, it is affecting them all. 

Reika is aware and hopes to fix this in v12. However it might be worth downgrading to v10 in the next update so we can get these things to work. 

Check Reika's main mc thread on the main forums for confirmation.

**Comment by Toksyuryel** [comment]
Downgrading is not an option and attempting it would, in addition to irrecoverably destroying everyone's world, break the agreement that allows Reika's mods to be in this pack at all. You will just have to wait for v12 along with the rest of us.

**Comment by Cantankerous-Rex** [comment]
Thank you for the reply. I was only trying to be helpful and offer a suggestion.

**Comment by Aivech** [comment]
In the meantime, you could try your hand at fission - PBR's are not necessary for progression.

**Comment by Haggle1996** [comment]
Toksyuryel is correct; downgrading is a violation of distribution terms for Reika's mods. Nothing we can do about it until v12 arrives.
