### ISSUE TITLE
MORE places to stick stuff quest issue

### ISSUE THREAD

**Issue by lensmanoz** [Haggle1996/RevolutionPack#345]
When crafting the storage drawers for the above named quest not all types of drawers count towards the quest. 
For example I made them using BOP magic wood planks which are valid to craft them in just not to hand in quest. Pressing the detect button didn't help either.

**Comment by Haggle1996** [comment]
As there's no 'OR' construct in HQM, the only fix would be to add a separate set of quests for each of the Storage Drawers content mods, which is a lot of work for little payoff. Will note it in the quest hints, but otherwise won't fix.
