### ISSUE TITLE
Crusher not processing Harder Ores properly

### ISSUE THREAD

**Issue by gwydion0917** [Haggle1996/RevolutionPack#346]
Not sure if this was a change in the pack or who I should ask about it. NEI shows Hard Copper 7 will run through the crusher for 32 Raw Copper Ore. 

![image](https://cloud.githubusercontent.com/assets/2494757/13952930/a3259e34-f00f-11e5-88f2-e2b02dc9ef2b.png)

But when I process any Hard Copper, I get 2 Raw Copper Ore.

**Comment by mtesseracttech** [comment]
The same happens for me with bonemeal, it says it will give 6 bonemeal per bone (I believe) but 2 is all I get.

**Comment by Aivech** [comment]
Something is definitely broken - the hard ore given should vary with the density of the ore.

**Comment by gwydion0917** [comment]
Problem was only on server. Re-uploaded the mods from my client install and everything now works as expected.
