### ISSUE TITLE
Golemancer's Bell uncraftable R2

### ISSUE THREAD

**Issue by crawln45** [Haggle1996/RevolutionPack#348]
Seems last update broke the golemancer's bell from being crafted.

R2 Ver: 2.4.0.0-Beta

**Comment by Aivech** [comment]
What are you crafting it in?

**Comment by crawln45** [comment]
TC ae crafting terminal. Nei shows 2 bells. One crashes client when clicked on. Other has no recipe. If you put the recipe from the book in the crafting terminal. It shows golemancer's Bell:-1 and crashes client when you try to remove it from the crafting square.

**Comment by Aivech** [comment]
Craft it in the arcane workbench.

**Comment by sapid** [comment]
Similar to #338 - looks like something is munging an item ID on crawln45's end, but I couldn't reproduce. Even crafting it worked for me in the terminal.

I do see two Golemancer's Bells in NEI, and they appear to be identical entries (4265 with matching recipes). I'm guessing there was an issue that occurred when migrating the world to 2.4. Perhaps one of your mods didn't get updated in the migration, crawln45?

**Comment by Aivech** [comment]
This bug was present in Rev|1. Crafting the bell in the ACT gives a bell with an item ID of -1, which is, as you can imagine, not a valid item ID, and thus crashes the game.

**Comment by Haggle1996** [comment]
It is craftable via the Arcane Workbench. Today's update to RV3 of AE2 may also fix the terminal crafting, but otherwise you'll need to use the workbench.

**Comment by Aivech** [comment]
As a side note, I have still noticed unrelated crashing issues with the Arcane Crafting Terminal on AE2-rev3 beta when crafting non-arcane recipies in it.

**Comment by Haggle1996** [comment]
That may also be addressed in the thaumic energistics update today.

**Comment by Aivech** [comment]
This was in a different pack which may or may not be on the latest version.
