### ISSUE TITLE
marsFlat in Overworld

### ISSUE THREAD

**Issue by PaladinOne** [Haggle1996/RevolutionPack#349]
So I loaded into a new world (did not run /pregen, just started the world and went), and I started in a desert. After exploring a while, I found a river, and decided to set up a house near it. And then I noticed that, as shown in the screenshot, the biomes had decided I was on Mars, and as such I would have to fight Evolved Zombies at night.

Revolution2, 2.4.0.0, no config changes (but added OptiFine)
![2016-03-24_00 09 15](https://cloud.githubusercontent.com/assets/7624297/14010709/f1603032-f154-11e5-9952-56e38b4b26a9.png)

**Comment by Aivech** [comment]
Is the biome ID for marsFlat exactly 128 greater than the biome ID for the desert biome you are in?

**Comment by PaladinOne** [comment]
No, actually, it appears to be exactly the same. Which does pinpoint the issue, and confirm that it's a simple ID configuration issue. (Biome ID overlap between GalactiCraft and Biomes O Plenty) Still needs to get fixed, but at least it's something simple.

**Comment by sapid** [comment]
The biome dump from NEI says marsFlat is the only one with its Biome ID (102 in DEFAULT worldtype, 103 in BIOMESOP worldtype.) What worldtype are you using? What is overlapping with it?

**Comment by PaladinOne** [comment]
I was using Realistic World Generation type; it was Oasis that overlapped.

**Comment by vagaprime** [comment]
the biome Moon is showing up as well with RTG

**Comment by PaladinOne** [comment]
I heard a rumor that this is an issue with Galaxy Space, with its biome IDs not being configurable and overriding other mods' overworld biomes

**Comment by Haggle1996** [comment]
No, it's an issue with RTG not respecting the dimension IDs.
