### ISSUE TITLE
RF API Issue - Crashing Server

### ISSUE THREAD

**Issue by Porkchopseesu2** [Haggle1996/RevolutionPack#351]
Hello,
        It appears the EnderIO mod has an issue with the RF API version being used --First issue. We have also had issues with falling from a great height has you freeze for a significant time and warns in remote console that player ZYX has moved too quickly -- Second issue. I have listed the crash reports below Any suggestions? 

Date:3/25/2016 crash - http://pastebin.com/BvZ56vYT)-- RF API
        -Related Log:  http://pastebin.com/i2WvbWqW
Date: 3/27/2016crash - http://pastebin.com/H8LBPQaf -- RF API
        -Related Log: http://pastebin.com/1ugnyTp9

**Comment by Aivech** [comment]
The EnderIO API version - if you saw that in the logs it should state the offending mod.

The crash with falling: This isn't the first time...

**Comment by Aivech** [comment]
#316

**Comment by Haggle1996** [comment]
I believe this is fixed in the next update. Let me know.
