### ISSUE TITLE
Pneumaticraft lubricant can't be crafted

### ISSUE THREAD

**Issue by Powerpin** [Haggle1996/RevolutionPack#353]
When using the thermopneumatic processing plant to make lubricant from diesel, it make Rotarycraft lubricant and then can't be used to craft speed upgrade from PneumaticCraft

Server version 2.4.0.0

**Comment by Aivech** [comment]
As I see it, there are two ways to change this.
1. Change the recipe of the Pneumaticcraft item to let it use Rotarycraft lubricant.
2. Get one or the other of the mod authors to change the internal name of their lubricant fluid (will likely break a bunch of stuff)

**Comment by Haggle1996** [comment]
This is fixed in the next update by allowing the speed upgrade to be crafted with RoC lubricant bucket.
