### ISSUE TITLE
suggestion: 

### ISSUE THREAD

**Issue by Leftorius** [Haggle1996/RevolutionPack#354]
Hi there,

I really like this modpack and I played almost a week with it so I'm really a fan of this scenario.
But could you maybe consider of adding this mod: http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ArchitectureCraft/

it's like chisel just for decoration but you can make huge things with it. I mean I added it myself but I think all of your players should have it :)

**Comment by Toksyuryel** [comment]
Well this looks gorgeous. I'll second this request!

**Comment by mtesseracttech** [comment]
Looks cool, especially since the entire pack has a less blocky style than the average MC pack

**Comment by Haggle1996** [comment]
Added in the next update.
