### ISSUE TITLE
Can't load pack past step 7

### ISSUE THREAD

**Issue by tmerc1709** [Haggle1996/RevolutionPack#355]
here is the link to the log, essentially it loads everything up to part 1/11 of step 7 and idk why. any help would be much appreciated, I believe my laptop should be able to handle the game as it could handle games such as the witcher 3 just fine so I Really just want to understand whats going on, thanks guys :)

logs: http://paste.atlauncher.com/view/72ba5636

also wanted to note that I am trying to play the rev2 pack, not rev1.

**Comment by sapid** [comment]
How much RAM did you allocate to it in the launcher?

**Comment by tmerc1709** [comment]
3072 mb as the startup/initial and then 5632 mb as the maximum

**Comment by Aivech** [comment]
Did it freeze, or what? This log appears perfectly normal.

**Comment by tmerc1709** [comment]
basically, it just runs but takes around 40 minutes to actualy load the game

**Comment by tmerc1709** [comment]
and ive tied setting splash to false and what mnot too which duidnt work

**Comment by tmerc1709** [comment]
I gave you the info, and I'm sure I'm not the only one with this problem, any new ideas or any at all about the problem? it takes roughly an hour to load and then just lags terribly so I basically can't play it. is it me or is it the computer or what? just wondering

**Comment by Aivech** [comment]
Do you have a dedicated graphics card? This probably isn't a problem but I'm curious.

**Comment by sapid** [comment]
This is almost certainly a performance problem and not a pack problem, and actually, there's a good chance that's the problem specifically, DaMachinator. 

It reminds me of an issue I saw on a friend's laptop where the computer was trying to use the laptop's onboard video processor to run that game rather than the GPU. What CPU & GPU are you using? Are you using a laptop? What model laptop?

**Comment by Aivech** [comment]
@sapid There's a known issue of that, and there are several workarounds, but it only occurs with Intel CPU's. When I saw that MC was using integrated GFX, it made me curious.

If you have a dedicated GPU, you can always disable integrated graphics in the BIOS settings.

**Comment by Haggle1996** [comment]
Closing for now. Please post more info if you're still having the problem and we'll look at reopening.
