### ISSUE TITLE
Arc Furnace Vibrant Alloy recipe wrong output

### ISSUE THREAD

**Issue by Powerpin** [Haggle1996/RevolutionPack#357]
When adding gold ingot, redstone, glowstone dust and ender pearl dust in Arc furnace, a vibrant alloy should be smelted, instead the ender dust isnt consumed and a energy alloy is smelted.

Revolution 2, 2.4.0.0

**Comment by Haggle1996** [comment]
Fixed in next update.

**Comment by Yuri4171** [comment]
Arc furnace still/again can't make vibrant alloy, ender pearl dust is ignored and energetic alloy is created.

Revolution 2, 2.6.0.0
