### ISSUE TITLE
Bibilocraft Disc Rack

### ISSUE THREAD

**Issue by lensmanoz** [Haggle1996/RevolutionPack#358]
Is it intended that this item is unavailable? I have gotten the full set of discs a few times as a quest reward and the rack would be a great tool for them. The config suggests it should be available.

**Comment by Toksyuryel** [comment]
I have noticed this issue as well, it was pretty upsetting.

**Comment by sapid** [comment]
Is this a matter of the recipe being unavailable or is the item actually uncraftable? If the former, it may be a matter of adjusting InPure's NEI culling.

**Comment by Haggle1996** [comment]
Fixed in the next update
