### ISSUE TITLE
World Stuck on Pregen with Chromaticraft and CustomOre Gen

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#360]
While pregenning a Revolution 2 world with the WorldBorder plugin, the generation will get stuck and the CPU will max out with some sort of negative interaction between Chromaticraft and CustomOreGen.

Warmroast Profile: http://i.imgur.com/ZuPPcDg.png
KCauldron Version: KCauldron-1.7.10-1614.184 (Any higher versions will cause DragonAPI to hate KCauldron)
Mod's Disabled: Admin'sToolBox, Cyano'sLootableBodies, EnviroMine, FTBLib+FTBUtilities, and Roguelike dungeons.

I have made a ticket [here](https://github.com/lawremi/CustomOreGen/issues/147) as well.

Please let me know if you need any more information! :)

**Comment by NachtRaben** [comment]
This isn't a vanilla forge environment and I don't really feel like i can put a larger emphasis on the fact that any mcpc/sponge/glowstone/kcauldron/bukkitforge issues are to be reported to the respective teams. Mod authors absolutely do NOT support these environments out of the box and there is nothing we can do here to fix this problem.

**Comment by vagaprime** [comment]
It might be worth trying to run the Pregen in a standard Forge server first then switching the world save over to to the Kcauldron server.

**Comment by Aivech** [comment]
It also might be worth trying FTBUtils and Admin'sToolBox and ForgeEssentials instead of unsupported Bukkit derivatives.

**Comment by Haggle1996** [comment]
Closing this issue since I can't do much for KCauldron. If you have additional information, post it here and I may reopen the issue; however, I would use the suggestion to pregen on a standard server then copy it over.
