### ISSUE TITLE
2.5 worldgen broken?

### ISSUE THREAD

**Issue by Leftorius** [Haggle1996/RevolutionPack#361]
got a lot of crap chunks if I create a new world (almost everychunk has AE2 meteors).... so it looks really crappy :I
EDIT: used RTG as worldgen

**Comment by Haggle1996** [comment]
Might want to try reinstalling 2.5. Sometimes the config files don't download and ATLauncher doesn't warn the player (there's a red message in the console, but nothing noticable.) Of the 8 or so worlds I generated with 2.5 using RTG, none had the problem you described.
