### ISSUE TITLE
2.4.0.0 Galaxycraft nickel ingots do not stack

### ISSUE THREAD

**Issue by RabidDave** [Haggle1996/RevolutionPack#364]
Galaxycraft nickel ingots [7123:6] do not stack they only sit there as singles, no nugget, and no block crafting.

[process to get them that way] nickel flakes (from RoC) smelted in a EIO alloy smelter, other methods of smelting results in RoC nickel ingots [5273:3] that do stack

**Comment by Haggle1996** [comment]
I can't replicate this in 2.5.0.0. It may have already been fixed. I tested that all nickel ingot variations work.
