### ISSUE TITLE
consider adding ore dictionary converter mod

### ISSUE THREAD

**Issue by RabidDave** [Haggle1996/RevolutionPack#365]
with so many mods producing compatible ores/ingots etc it would be nice to be able to convert them so you don't have 6 different types of some ore. The mod ore dictionary converter
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286974-ore-dictionary-converter
should fix this

**Comment by Aivech** [comment]
JABBA barrels and Storage Drawers can unify ore-dict equivalents. In addition, I believe the Forge Lexicon is available to use.

**Comment by Haggle1996** [comment]
There are already several ways of unifying ores in this pack (as @DaMachinator mentioned). Generally, I consider machines outputting a non-standard ingot to be a bug, and try to fix them individually.

**Comment by Aivech** [comment]
Also, automatic ore-dictionary unification can cause some problems with Rotarycraft due to its progression system.
