### ISSUE TITLE
[suggestion] Remove Mystical Flowers from Worldgen

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#366]
Hi,
I already wrote this suggestion at the MC forum, but I don't think you have read it due to your absent. 

I'm playing with mystical flowers disabled by world gen, so I need to go into agricraft for getting started. You only need to find Podzol (e.g. in a Forest). It makes things more interesting imo :)

**Comment by ghost** [comment]
To make it more interesting you could disable the spreading of AgriCraft-crops

**Comment by Aivech** [comment]
Agricraft crop spreading is probably going to stay, as disabling it means being stuck with the base tier seeds.

Also, in my experience, Podzol is one of the most difficult surface worldgen blocks to find.

**Comment by ghost** [comment]
Disabling the spreading means, that Crops won't spread without mutations. So you have to mutate all the tree every time.

Just look for a Forest ;)

Podzol is basically dirt, so it should be possible to craft Podzol with Dirt and maybe Compost?

C: Compost, D: Dirt, P: Podzol
C C C
D D D = 6*P
D D D

**Comment by Aivech** [comment]
You can still copy plants if spreading is disabled, with clippings.

**Comment by Haggle1996** [comment]
Botania is already gated behind steel, which makes it somewhat early-midgame (or late early game, if you find steel in a chest). Adding an additional gate through AgriCraft would extend the early-game even more. While this sounds fun and challenging, I've gotten mild feedback that making the early game longer isn't desirable, so I will not implement this at this time.

However, if you want a challenge, I suggest removing the flowers. Certainly fun times and balanced.

**Comment by Toksyuryel** [comment]
Dang, I'd have personally loved an extension of the early game and this sounds like a fun way to do it. Right now breeding mystical flowers with agricraft is largely pointless because the return is so good with floral fertilizer and the jaded amaranthus is highly effective once that stops being viable.
