### ISSUE TITLE
Rockhounding metals need to be disabled

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#367]
Copper, for example, collides, as does silver. Will probably fix this by disabling the Rockhounding metals, but need to test.

**Comment by Ieldra2** [comment]
How exactly do I do that. The config is confusing.

**Comment by OmegaCenti** [comment]
(only for silver at the moment)

I tested a patch I made on a single player and it appears to have fixed it. I submitted pull request #372 OmegaCenti:silver_smelting_patch
35516c1

**Comment by Haggle1996** [comment]
Fixed by adding the ore dictionary for the dusts to the furnace. Added silver, aluminum, and tin
