### ISSUE TITLE
Slow down super speed zombies.

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#369]

**Comment by Powerpin** [comment]
awesome challenge you gived to us :p

**Comment by RabidDave** [comment]
more info:
config\ZombieAwareness\General.cfg

```
# Range of extra random speed to give a zombie for extra spawns and zombie duplications, eg: 0 = no boost, 1 = up to double speed
I:zombieRandSpeedBoost=5
```

according to google/changelog previously may ot have been implemented?

default is 5

values of 0-1 make more sense with 0.5 being about right

**Comment by Haggle1996** [comment]
This has been reduced to 1 in the next update.
