### ISSUE TITLE
Rockhounding silver dust does not cook.

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#371]
Looks like there is a missing recipe to cook from silver dust to ingot.  

Tiny dust can cook to nugget, which can be combined into ingots.

**Comment by Haggle1996** [comment]
Duplicate of #367

**Comment by OmegaCenti** [comment]
I tested a patch I made on a single player and it appears to have fixed it. I submitted pull request #372 OmegaCenti:silver_smelting_patch
https://github.com/Haggle1996/RevolutionPack/pull/372/commits/35516c1ddeef1212f2ba0e78a7778e5e3f86de28
