### ISSUE TITLE
IE Blueprint Recipe

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#374]
The blueprint search is fine in SMP, but in MP it can cause issues with loot and frustration.

Add a Blueprint Minetweaker script to craft the items, should be expensive.

Here's an example from FTB Infinity Skyblock:

`recipes.addShaped(<ImmersiveEngineering:blueprint:1>, [[<ore:ingotHOPGraphite>, <ore:blockEmerald>, <ore:ingotHOPGraphite>], [<ore:ingotHOPGraphite>, <ImmersiveEngineering:blueprint>, <ore:ingotHOPGraphite>], [<ore:ingotHOPGraphite>, <ore:blockEmerald>, <ore:ingotHOPGraphite>]]);
`

Also a configuration change can be made, but the default recipe is "weak"

  B:"Arc Furnace: Craftable Blueprint"=false

**Comment by Aivech** [comment]
Use the botania loonium to get dungeon loot if its that big of an issue :)

Apart from that, it's up to Haggle.

**Comment by Haggle1996** [comment]
I've gone ahead and enabled the default recipe from Immersive Engineering. It's already a slog to get an Arc Furnace.
