### ISSUE TITLE
Ae2 Stuff

### ISSUE THREAD

**Issue by Kaelthanas** [Haggle1996/RevolutionPack#376]
Crystal Growth chamber or advanced inscribers. cannot be placed down, and disappears

**Comment by Haggle1996** [comment]
I can replicate this. I'll look into it.

**Comment by Haggle1996** [comment]
The version of AE2 Stuff in the pack is for rv2 of AE2. I'll get it replaced with the rv3 version in the next update.

**Comment by Haggle1996** [comment]
Fixed in the next update.
