### ISSUE TITLE
Move Forestry gating to pre-EIO

### ISSUE THREAD

**Issue by JMarcu** [Haggle1996/RevolutionPack#377]
Bronze is traditionally a fairly easy metal to achieve, and many tech mods assume this. Currently though its pretty heavily gated. The two ways to make it are with an Arc Furnace, fairly late game, or with an Allow Smelter. That smelter needs a Machine Chasis, which in turn needs a Basic Capacitor. That capacitor can only be made in an Assembly Table which needs to be powered by buildcraft's lasers which themselves demand a very robust RF infrastructure. The result of this is gating any Forestry multifarms behind all this tech. Now, this could be intentional, but it seems absurd to me to have forestry stuff pushed that far back into the pack. At that point you can use other mods for far more robust farming options, right?

**Comment by Aivech** [comment]
Maybe we should add a shapeless recipe of 3 copper dust and 1 tin dust for 4 bronze dust, assuming this isn't already possible.

**Comment by Haggle1996** [comment]
I agree this needs to be changed up slightly. You should be able to do Forestry right before starting the industrial era.

**Comment by Haggle1996** [comment]
I've addressed this by adding Constantin ingots to the ore dictionary for bronze ingots. Constantin/Cupronickel must be smelted in the blast furnace, though it's very inexpensive there.
