### ISSUE TITLE
matter scanner GUI (Matter Overdrive)

### ISSUE THREAD

**Issue by DorinnB** [Haggle1996/RevolutionPack#38]
When i try to open the GUI of the matter scanner ("C" by default), i crash to desktop.

http://pastebin.com/W8kuyX2Y

**Comment by DorinnB** [comment]
And btw, pickaxing pattern storage will destroy everything inside (matter scanner and drive)
May be intended but cost some diams in the process !

**Comment by Haggle1996** [comment]
I didn't see a similar issue already reported to the mod author, so I opened up another issue on their tracker. I'll keep on top of it.

**Comment by Haggle1996** [comment]
Fixed in 0.9.2. Note that Matter Overdrive requires Java 8, so not all players will be able to use Matter Overdrive after 0.9.1
