### ISSUE TITLE
Golemancer bell crafting causes CTD

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#382]
Its the darn -1 metadata thing again.

**Comment by Haggle1996** [comment]
Are you crafting it in the arcane bench?

**Comment by Yuri4171** [comment]
Speaking on Ptero's behalf, yes, he is.

**Comment by Haggle1996** [comment]
Try this again with 2.5.2.0 later today. I can't replicate it.

**Comment by Pterodactlol** [comment]
I figured out how to replicate it: place the ingredients for the bell in the bench, then leave and re-enter the GUI. The bell then has a -1 metadata.

**Comment by Haggle1996** [comment]
The solution is to have all the materials on hand before crafting the item, or remove them before attempting to craft again. This is already posted on the author's tracker, so closing here.
