### ISSUE TITLE
ChromatiCraft casting complex table doesn't draw power while crystal chargers do

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#383]
Symptom:
I have pylon casting unlocked and after placing the required items, the casting table shows the correct output item, so the recipe is correctly unlocked as well. I tested the lumen network by placing a crystal charger on top of the casting table, and it charged with energy from all colors. Still, when I attempt to actually cast, nothing happens. The casting animation starts, but no power is drawn from the network. Most of the time, anyway. In rare cases some power is drawn, so I know the casting complex is functional in principle.

I can draw elemental energy through the repeaters that are part of the casting complex using a crystal charger placed within or without the complex itself, but the casting table itself doesn't draw power. 

Also, there are places in range of repeaters where a placed crystal charger draws no power whatever I do, while placing it somewhere else in range of the same repeater makes it work correctly. I made sure there were no (visible) obstructions in both cases, and both attempts were made at the same y level.

I uninstalled Optifine for testing this. This is Revolution 2 v2.5.2.0

**Comment by Haggle1996** [comment]
Try setting `B:"Pylons Chunkload Selves Once Used"=true` in your config/Reika/Chromaticraft.cfg

The setting is off by default as most players don't go deep into Chromaticraft and, on a server, the number of loaded chunks can cripple a server.

**Comment by Haggle1996** [comment]
Closing because Crystal Lamps block the beams. :D
