### ISSUE TITLE
Make fuel require kerosene + lox, or similar progression

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#386]

**Comment by Toksyuryel** [comment]
Being that I proposed half of this, I am obviously in favor :) though I'm still questioning how one goes about obtaining the liquid oxygen- it's a good choice for realism, but if you need reactorcraft ores to get it then the need to go to space to get those ores goes out the window. I need to remind myself how one actually creates that. Let's see if I can get the game open without overheating my CPU...

**Comment by Haggle1996** [comment]
LOX is obtainable through Galacticraft -- though normally you stick it in your air tank. :D

**Comment by Toksyuryel** [comment]
Yeah I just looked it up. It requires the gas liquefier which requires meteoric iron, so it's still gated behind space travel which is an issue if we want to gate space travel behind it!

**Comment by Haggle1996** [comment]
Swapped Rocket Fuel for Kerosone (so it's now Kerosene + Oil). This gates it behind pneumaticraft. Unfortunately, LOX is not a usable fluid.
