### ISSUE TITLE
Rotarycraft flywheel causes server hang

### ISSUE THREAD

**Issue by Kreidos** [Haggle1996/RevolutionPack#395]
Already submitted upstream, [#794](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/794) but should be added to the known issues list until it's fixed.

Whenever a flywheel is used, it causes the server to hang indefinitely. CPU usage remains at 100% and java must be killed manually.

Steps to reproduce:
1. Use a flywheel.

No log output to show, as the server and client just hang, and do not generate log or console output.

**Comment by Haggle1996** [comment]
Thank you for reporting on both trackers. :) Saves me a bunch of time.

**Comment by Haggle1996** [comment]
ReikaKalseki/Reika_Mods_Issues#734
