### ISSUE TITLE
Bee House recipe not working

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#399]
The Bee House recipe is not working.  Assuming its the default 3 wood slabs on top of planks with a comb in the center (I tried spruce and oak wood with a mossy comb).  NEI doesn't show the recipe, but the FTB wiki reports it as such.

**Comment by RaineAndrews** [comment]
Just for thoroughness' sake: I'm using the most recent Revolution 2 build (2.6.0.0) with no config/mod modifications.

**Comment by OwenGr** [comment]
You can temporarily enable the recipe by turning off null stack cleanup in Reika/DragonAPI.cfg. Don't leave Minecraft running this way as you will experience a number of crashes. This was discussed in the 2.5.1.0 release notes, as well as on a previous issue.

**Comment by RaineAndrews** [comment]
Thanks!  Only the apiarist chest was mentioned in the update, but now I will try that with future issues regarding forestry recipes before posting an issue!  If it is any consolation, I did a search for bee house before posting the issue :P

**Comment by Haggle1996** [comment]
As @OwenGr pointed out, this is a duplicate of #313. I wish there was a better solution, but the cleanup code kills recipes both added through minetweaker as well as through HaggleTweaks. So in the mean time, just go into your config/Reika/DragonAPI.cfg and twiddle the `B:"Disallow Null-Item ItemStacks to Prevent Crashes"=true` setting to be false. Once they're crafted, you can restart the service. I believe this works client-side, so players on SMP servers can twiddle it, craft the items, then set it back without the server having to mess with it's recipes.
