### ISSUE TITLE
Switch to Better Questing

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#403]
http://minecraft.curseforge.com/projects/better-questing

Been playing around with it, would be willing to help make some quests, seems better than HQM for our uses

http://minecraft.curseforge.com/projects/better-questing-standard-expansion which is secondary requirement has an HQM converter.

**Comment by Haggle1996** [comment]
If someone wants to write an alternative quest line in any of my packs, I'm happy to include it. 

I'm using BQ for my next packs, though it doesn't feel any easier than HQM -- just has more features.
