### ISSUE TITLE
Enviromine "Cave Dimension" is a duplicate of the overworld.

### ISSUE THREAD

**Issue by Kreidos** [Haggle1996/RevolutionPack#405]
You maniacs! You blew it up!

The cave dimension (-2) is a copy of the overworld, and it does not generate it's own map. I don't mean it uses the same seed, I mean it's a literal copy of the state of the overworld at the time you enter the elevator. I was able to find my base and everything exactly as it was before I went into the mine. 

Obviously this is the ultimate dupe glitch, as now I could have 2 of everything all at once. On a public server, even more-so.

Since all ore and ore locations are copies from the overworld, this also affects progression, as cadmium can only be found in the cave dimension and gates the only other source of it (Planets).

**Comment by Aivech** [comment]
I am nearly certain this is not supposed to happen.

**Comment by Haggle1996** [comment]
Yah, I have absolutely no idea what's happened on your end, Kreidos. There's no provision in Forge to copy a dimension to another dimension and Enviromine doesn't scan chunks like that. I can verify entering the cave dimension in both SSP and SMP results in an actual cave dimension using 2.6 of REV|2. Try deleting your DIM-2 folder from your world save and see if it regenerates correctly. I would reinstall the pack prior to doing this, just in case it was a corrupted configuration, but I can't see how this would happen via the mod. More likely someone accidentally copied the contents of the region folder into the DIM-2 folder.
