### ISSUE TITLE
OpenGL Troubleshooting

### ISSUE THREAD

**Issue by BobSheepert** [Haggle1996/RevolutionPack#410]
Hey, so, for some reason my Revolution 2 pack isn't opening and is instead crashing on launch, which is leading me to be unable to play the modpack. I will have my pastebin link pasted below, I know this isn't much info, but I honestly don't know what else to tell you. If you need any other information, I'd be happy to tell you. Any help is appreciated!

Pastebin of crash report: http://pastebin.com/YGEDhMMV

**Comment by NachtRaben** [comment]
Make sure your drivers are up to date, this is usually a problem if you don't have drivers installed.

**Comment by Haggle1996** [comment]
First, reboot your machine. Your stack is corrupt at the moment.

Next, disable OptiFine and load the pack once without it. Then you can try loading it with OptiFine. OptiFine requires you to load each new instance of Minecraft once without Optifine enabled, as this forces OptiFine to load after all mods.

If it still doesn't function at this point, update your drivers, as Nacht said. Keeping them up to date is good practice.

**Comment by BobSheepert** [comment]
Sorry for the late reply, I went and had lunch.

Alright, so, I removed Optifine from the mods listed in the Revolution 2 pack, and then attempted to launch the pack. Sadly, I received this crash report when I tried to launch the game: http://pastebin.com/uvzw6mwk

I assume I'm going to have to update my drivers, although I'm honestly not sure how to do that. Any help with the process of that would be lovely. Thanks for the help so far though! I really appreciate your efforts :D

**Comment by Haggle1996** [comment]
You'll need to figure out the brand of video card you have, then go to the manufacturer's website and download the appropriate driver. The log says you have Windows 10, so you may have a pending driver update already queued up by Windows.

I have no idea about your system or configuration, so you'll need to figure out what you have and install it. Search google for 'Dell Latitude Video Drivers', for example, if that's what you have. If you know the brand of video card you have, you can search for that term, for example, 'ATI Video Card Drivers'

**Comment by RaineAndrews** [comment]
Not every video card is windows 10 ready.  If this is the case, you'll either need to downgrade windows or upgrade your card :(

**Comment by NachtRaben** [comment]
If you can open up your device manager, and expand "Display Adapters", show me what pops up under that submenu and I'll help you locate a driver for yourself. Along with this I'll need to know your computers make and model, and your windows version and architecture type.

For example, My computer is custom built, and my OS is Windows 10, 64-bit architecture.
Along with your screenshot of display adapters.

![ss 2016-05-14 at 10 17 01](https://cloud.githubusercontent.com/assets/4164436/15271655/a8d98034-1a21-11e6-8d05-a92ad817bbea.png)

**Comment by BobSheepert** [comment]
-Haggle1996
I spent about 4 hours last night searching for an Intel graphics display I could use, that was built for Windows 10 64-bit. Every single time I tried downloading a driver, it just told me my PC didn't meet the requirements for the driver. Also, whenever I go into my device manager, and try updating my display adapter, it says I already have the latest driver. I tried using the "Intel Driver Update Utility" and it only gave me a new driver for my chipset.

-RaineAndrews
Since I'm using an All-in-One PC, I'm not sure how to change the graphics card on my machine. I'm just going to hope I don't need  to downgrade to Windows 7 

-NachtRaben
Alright, I can do that: http://prntscr.com/b49pth <--- Display Adapters
I'm not sure what my computer's "Make and model" is, but my Windows version is Windows 10, and my PC is 64-bit. 

This is my dxdiag, if that helps at all: http://pastebin.com/NPD1LhfT

I have an i5. too, and my computer is an "HP TouchSmart7320 PC".

Right now I'm just hoping for the best. So far you guys have been a great help. This is basically why I moved from FTB to AT - You guys actually care about your users :)

**Comment by Haggle1996** [comment]
Do other 1.7.10 ATLauncher packs work okay on your machine?

**Comment by RaineAndrews** [comment]
HP doesn't have its own windows 10 driver for your computer.  I suggest you try one of intel's drivers and hope for the best.  You can use their driver update utility found at https://downloadcenter.intel.com

**Comment by BobSheepert** [comment]
-Haggle1986
Nope, they all crash. This is the message I got for Skyfactory: http://paste.atlauncher.com/view/3ac16f17

-RaineAndrews
Yep, that's the tool I was using. I tried it a million times, it only told me my chipset driver was out of date.

**Comment by Haggle1996** [comment]
Next question, do any of your FTB packs run? If they do, you probably need to reinstall the ATLauncher in a new folder and redownload a pack. ATLauncher downloads a bunch of shared libraries and one of them may be corrupted.

If you can't get an FTB pack to run, I'd try resetting Windows 10 by going to Settings...Updates & Security...Recovery...Reset this PC. This will, of course, uninstall all your applications (but keep your files) and reset Windows 10 to a clean state; hopefully resetting your video driver stack.

**Comment by NachtRaben** [comment]
Gotta love the issues with integrated drivers and driver availability.
http://download.cnet.com/DriverMax/3000-18513_4-10572602.html
Use this utility to help debug your missing drivers.
I strongly recommend uninstalling it after you get everything up to date.

It should also find your display driver for you.
(I use it personally in cases like this, just be a smart cookie while using it and uninstall afterwards, I am not liable for any issues that arise from improper use.)

**Comment by BobSheepert** [comment]
-Haggle1996
None of my FTB packs run, sadly. I'd also rather avoid resetting Windows 10 to be honest, but if I have to I may.

-NachtRaben
Ok, I got you. I've used the utility to update my graphics driver as well as my processor, although I can't update more than 2 drivers a day =P. 

I appreciate the help so far guys, I think we may actually end up solving this issue lol 

(btw thanks haggle for the title fix xP)

EDIT: I've tried opening up the modpack after updating my graphics drivers (_only my graphics drivers_), and I get this crash message: http://paste.atlauncher.com/view/a59134c1

**Comment by RaineAndrews** [comment]
Did you reset your computer after the update?

**Comment by RaineAndrews** [comment]
and if so, update your LWJGL libraries at https://www.lwjgl.org/download, then restart.

**Comment by Haggle1996** [comment]
It's the same error as before; there's no OpenGL driver installed for your video card. :(

**Comment by BobSheepert** [comment]
-RaineAndrews
No, I didn't =P

-Haggle1996
Oh. Is there a way to install an OpenGL driver onto it through the internet by any chance? .-.

**Comment by Haggle1996** [comment]
OpenGL drivers are bundled along with the video adapter driver.

It is up to the manufacturer to include them in your system's drivers. It's easy to blame the Windows 10 drivers for lack of OpenGL support, but this really is the fault of HP and/or Intel not providing appropriate drivers for older chipsets. Nvidia and AMD are really good about keeping their cards up to date.

You may be able to find someone who's cobbled together a driver solution, but you may be out of luck using Win 10.

**Comment by RaineAndrews** [comment]
You could always try HP's intel driver for windows 7, but it isn't supported for windows 10.  It may fix this problem, but bring along other issues in the long run.

**Comment by RookVsBishop** [comment]
Mine is working but it says   Internal Exception:java.lang Runtime Exception:No OpenGL context found in the current thread

**Comment by Haggle1996** [comment]
Similar issue; there's no OpenGL driver on your system.

**It's important to note that OpenGL issues are not pack issues; we're just being nice and giving some help.**

**Comment by BobSheepert** [comment]
Oh... So I can't play modpacks? .-. That sucks ;'(

Is the only way to be able to play a mod pack to get a new computer?
