### ISSUE TITLE
Milk a cow?

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#411]
Tried using normal metal bucket: Doesn't do anything.
Tried wood bucket and it disappears from hand and comes back when the hand slot attempts to be filled by another item.
Waited for cows udders to fill (because why not), but no dice.

Using latest version of of revolution 2

**Comment by Haggle1996** [comment]
Cows are no longer infinitely milkable. There's a long cooldown timer.

**Comment by Haggle1996** [comment]
If you turn on the animal helper in Zyin's HUD, it shows you if the cow is milkable.

**Comment by RaineAndrews** [comment]
Is that harder wildlife?  I couldn't find any documentation on the matter from searches of the interwebs and on the revolution 2 website!

**Comment by Haggle1996** [comment]
No, Zyin's HUD. CTRL+ALT+Z to open it's UI.

Harder Wildlife's recent update is what reduces the milking frequency.

**Comment by RaineAndrews** [comment]
I'm stalking some wild cows, but they aren't making milk.  I'll wander over to the Realism github I guess :(

**Comment by RaineAndrews** [comment]
Nope, finally got some milk after I reloaded the chunk :+1:
