### ISSUE TITLE
Move Rockhounding Back to Core Mods

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#414]
GlobbyPotato says this is their "last version creating mess with IDs and block/items. No more parts will be renamed or changed. Around 500 IDs have been removed from the mod hopefully making it lighter."

Don't give up it yet ; .;

**Comment by Haggle1996** [comment]
It's not just the ID problem...which, mind you, isn't the first time the author has suggested the ID changes are final. For example, just placing an Iron Sieve can corrupt your world.

**Comment by devanchya** [comment]
The mod has turned out to be very unstable on a server.  The Sieve, and a few other items have caused player crash issues which are a pain to fix.

**Comment by RaineAndrews** [comment]
Ack, I can see why you moved it to optional then.  Can't have a release mod pack that is plagued with instability :(

**Comment by RaineAndrews** [comment]
Aaaaand, world corrupted by latest RockHounding update.  I've finally given up hope on this mod.  It was so cool, but ultimately not worth throwing away hours of my life on :(

I really hope he gets it stable ; .;
