### ISSUE TITLE
Extra utilities Portals not working

### ISSUE THREAD

**Issue by Saereth** [Haggle1996/RevolutionPack#419]
The deep dark and last millennia portal blocks dont work, I believe this may be related to galacticraft/player api issue thats been around for ages. Currently both dims are unreachable. 

https://github.com/rwtema/extrautilities/issues/553

**Comment by Haggle1996** [comment]
I will be resolving this by disabling the blocks for these dimensions and removing the recipes. Unfortunately, playerapi causes issues, not the least of which is mobs kick your butt in  your mob farm even if your nowhere nearby. These dimensions have other issues.

**Comment by Saereth** [comment]
Makes sense, thanks for the quick reply I'll let our players know.

**Comment by RaineAndrews** [comment]
Could we just:

> This is fixed by installing Player API as -instructed- on the Galacticraft compatibility wiki page. Links:
> http://wiki.micdoodle8.com/wiki/Compatibility#Any_other_mod_with_.27Fake_Player.27_detection
> http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996

Or have you tried that?

**Comment by Haggle1996** [comment]
Adding PlayerAPI causes other issues. I use it in REV|1 to enable these dimensions and the bugs aren't worth it (particularly breaking mob farms and the surprise player deaths - ever taken random damage in REV|1 and can't figure out what from? It's the PlayerAPI addition). The Last Millennium is just a small platform in a large, dark void. The Deep Dark is replaced by the Cave dimension for mining.

**Comment by Haggle1996** [comment]
These are removed in the next update.
