### ISSUE TITLE
FTB Utilities chunk loader not functioning

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#421]
Normally, one should be able to claim a chunk, then hold control key and left-click again to set that chunk to be on chunk load duty.  Is this a feature of Rev|2 or unfortunate bug?

**Comment by DorinnB** [comment]
you have to change ftb utilities config. Default is 0 chunk loaded.

config path : \local\ftbu\config.json
you can change for each player, or for admin only

  "permissions_player": {
    "allow_creative_interact_secure": false,
    "badge": "",
    "break_whitelist": [
      "OpenBlocks:grave"
    ],
    "cross_dim_homes": true,
    "custom_config": {},
    "dimension_blacklist": [
      1
    ],
    "forced_chunk_security": "-",
    "forced_explosions": "-",
    "max_claims": 100,
    "max_homes": 1,
    **# "max_loaded_chunks": 0,**
    "show_rank": true

**Comment by Kreidos** [comment]
I assume it is disabled by default because it's not in the spirit of the pack; chunk loading should not be free.

There are chunk loaders which one can build in-game. I.E. World Anchors, and Rotarycraft chunk loaders.

**Comment by Haggle1996** [comment]
@Kreidos is correct, chunk loading through FTB is disabled on purpose, as free chunk loading is not in the spirit of the pack.
