### ISSUE TITLE
Harder Wildlife Lizard Tweaks

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#423]
IMO the lizards spawn too frequently and too numerously for their difficulty level.  They are hard to hit, poison, come in groups of 3 to 6, and have more HP than any other vanilla mob.  Maybe if they had less HP, dropped a little less leather, they would be less of a nuisance.

Also, I don't think they can climb very well, so they tend to group of multiple groups and chase you down when you get on their y level.

**Comment by Haggle1996** [comment]
I have zero control over the spawning and stats of these monsters. Honestly, there's not enough things that want to eat you. If anything, I'm more likely to add more deadly monsters than nerf the ones we have.
