### ISSUE TITLE
Make REV|2 mobs harder.

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#424]
Because too many people complain the monsters are already hard; consider adding lycanites, grimoire, etc.

**Comment by Kreidos** [comment]
Would vote nay for this one.

In my experience Grimoire just causes a lot of insta-deaths early-game and a minor inconvenience later on. It also clashes with the theming of the pack. Sure we have mutants, it's after the end of civilization. Sure, we have Thaumcraft... But Dryads and Werewolves and Valkyries? I don't know about all that.

**Comment by DorinnB** [comment]
I mainly found nether and the end really, really easy.
Something like explosive nether ore (with harder ores ? dunno if we can) and angry pigmen if we mine.
We don't have anything usefull on both dimension but blaze rod and enderpearl.

Lycanite is too much, sound like MadPack (by Kehaan and Jon Bams) We will only chain death without fun.

**Comment by RaineAndrews** [comment]
Maybe mutant creatures, and/or [Dark Menagerie](http://mods.curse.com/mc-mods/minecraft/224039-dark-menagerie).  I fear the night, but the daytime is fairly peaceful.  These can break that complacency.

You can also penalize not using the various light sources provided by the mod using [The Grue](http://minecraft.curseforge.com/projects/grue)

Or just change up the AI.  The zombies are terrifying in this pack.  Maybe something like [Stalking Creepers](http://minecraft.curseforge.com/projects/stalker-creepers)?

**Comment by RaineAndrews** [comment]
Also, greedy pigs that don't let me take their quartz would also make things... interesting

**Comment by Kreidos** [comment]
> You can also penalize not using the various light sources provided by the mod using The Grue

I believe the Enviromine cave dimension already has the Grue™.

**Comment by Haggle1996** [comment]
Mutant Creatures is already in the pack...that's where the spider pigs come from.

**Comment by Toksyuryel** [comment]
The grue's not in the cave dimension, it's in the deep dark which is unfortunately disabled in this pack.

Dark Menagerie would be cool to see in the pack. I will forever be against Grimoire though, its creatures are extremely poorly designed and badly balanced. I didn't like it at all in Rev1 and its absence in Rev2 is one of the many reasons it's a better pack.

Infernal Mobs is another one worth looking into, just remember to set the spawn chance extremely low. They should be a very rare and surprising challenge, not "every chunk in the nether has at least one infernal pigman" like it was in Blast Off.

**Comment by devanchya** [comment]
In other realms perhaps, but not the over world.
Right now the zergs are already killer.

**Comment by DragGon7601** [comment]
I'm against making the starting harder. But I do have another option for you... In Rev1 I used [Mob Properties](http://minecraft.curseforge.com/projects/mob-properties) to make the Dirt slimes always drop dirt (or garden soil sometimes). While looking through its options I seen reference to the "Apocalypse counter"... Took me a bit to find but it turned out to be something from another mod by the same guy (FatherToast). The mod made monster harder as time went on... Sounds like a good fit, but it looks like its not getting much updates. Anyway here's a link in case you still want it:

[Apocalypse Mod](http://minecraft.curseforge.com/projects/apocalypse-mod)

**Comment by Haggle1996** [comment]
I believe I've sufficiently addressed this by making sleep no longer advance time. This does make the early game a bit harder, but IMHO, it makes base defense much more relevant.

Thank you everyone for the input. Makes a big difference just to hear different thoughts.
