### ISSUE TITLE
Chroma doesn't lose it's color!

### ISSUE THREAD

**Issue by RaineAndrews** [Haggle1996/RevolutionPack#430]
After getting boosted crystals from a block of liquid chroma, the color stays!  I've done it twice with two different colors and got the same result.

**Comment by RaineAndrews** [comment]
I tried a third time, walked away in the game and came back to a clean pool of chroma with a boosted crystal.  Maybe its a rendering error?

**Comment by Haggle1996** [comment]
Possibly. Regardless, if it's still happening to you, you should post it to Reika's tracker or raise the question on his MCF forum.

**Comment by RaineAndrews** [comment]
When I sit there and watch the actually transformation occur, the chroma does not change color BUT it no longer acts as the berry saturated chroma (ie. can't be used to make more boosted chroma).  Referencing this to Reika's tracker.

**Comment by Haggle1996** [comment]
Closing per Reika's response
