### ISSUE TITLE
Wooden buckets don't fill Water Pads

### ISSUE THREAD

**Issue by McFrugal** [Haggle1996/RevolutionPack#432]
Agricraft water pads (where you right-click with a shovel on farmland) don't like wooden buckets and instead you get a block of water on top of the water pad, which then most likely floods your farm (ugh).

As a side note, I noticed that if you put down water with a wooden bucket when there's already water (flowing or not) there, you get a "pop" sound effect and some particles as if you destroyed the water.  Maybe that has something to do with this?  Or maybe Agricraft is just picky.

**Comment by DarkGuardsman** [comment]
I'll look into both of these issues, the first is most likely Agricraft using custom interaction. The other, if I recall right, may be intentional so buckets can be emptied quickly to use for other fluids.

**Comment by McFrugal** [comment]
With normal buckets, there's no pop or particles.  That's the only issue, so...  Oh, sorry, I guess I was unclear.  The water block IS placed if it's just flowing water.  It just sounds and looks like you're "breaking" the flowing water, or the source block if there was one there.

**Comment by DarkGuardsman** [comment]
I'll look into it more, thought you were saying you were placing water into a source block and consuming the water in the bucket.

**Comment by DarkGuardsman** [comment]
Oh I see what you mean, not sure why it is doing the block place particle effects. Though to be honest is rather nice but I can see about adding a config to disable it.

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/SBM-woodenBucket/issues/1

**Comment by Haggle1996** [comment]
I was confused too.

**Comment by DarkGuardsman** [comment]
You can most likely close this, I fixed the particle effect issue. Not sure why the vanilla bucket doesn't do the same effect considering it calls the same code.

**Comment by Haggle1996** [comment]
Thanks much, @DarkGuardsman

**Comment by dmodoomsirius** [comment]
new build is now live on curse. :)

**Comment by Haggle1996** [comment]
Awesome! Thank you again so much!

**Comment by dmodoomsirius** [comment]
sorry it took me so long.
