### ISSUE TITLE
The End attempts to reset endlessly

### ISSUE THREAD

**Issue by Saereth** [Haggle1996/RevolutionPack#433]
We're running rev2 on a fairly beefy dedicated server, quad core xeon 128gb ram, ssd etc. This is the only pack running on the server. Everything ran great for about 2 weeks, now the server has become nearly unplayable. <3tps.

The console is being spammed with:
"[17:24:20] [Server thread/INFO] [FML]: Unloading dimension 1
[17:24:20] [Server thread/INFO] [FML]: Loading dimension 1 (world) (net.minecraf
t.server.dedicated.DedicatedServer@130952f2)
[17:24:20] [Server thread/INFO] [CustomOreGen]: Loading config data for dimensio
n './world/DIM1' ...
"
every few seconds, and opis shows:
http://i.imgur.com/4vNBoUi.png

like the end is being spam loaded/unloaded. We aren't running cauldron/thermos or anything like that. 
Title may not be correct since the issue may not be with customOregen specifically.

**Comment by Haggle1996** [comment]
Have you tried deleting and regenerating The End? You can do this by deleting the DIM1 folder from your save.

**Comment by Saereth** [comment]
Just deleted the end to test, still doing it with a fresh end instance

**Comment by Haggle1996** [comment]
Something is definitely corrupted here. Can you zip and post full logs? fml-server-latest.log and latest.log?

Also, are you running any custom mods or configuration?

**Comment by Saereth** [comment]
Sure thing, here you go.
https://www.dropbox.com/s/41nz4vc0siof3tz/logs.zip?dl=0

**Comment by Haggle1996** [comment]
It's not Custom Ore Gen causing the problem -- it's just responding to the reload request.

When you regenerated The End, did the problem go away UNTIL you revisited The End?

If it did not, you have some force loaded chunks, either through a world anchor of some sort, or FTB Utilities claimed chunks (there's some other's, but something is forcing the dimension to load without being visited). When the dragon is defeated, there are two mods that try to delete The End as soon as the last player leaves. If they are prevented from doing this by some means, it could result in the log spam you're seeing.

If it goes away until The End is visited...not sure. I've been in and out of The End many times trying to troubleshoot other issues and I've never experienced this constant load/unload in any of my test environments. I would maybe suggest a fresh reinstall of the pack (keeping your save), just in case something weird has gotten corrupted.

**Comment by Saereth** [comment]
@I do remember someone had a railcraft anchor there, but the issue did persist after deleting the end. The chunk might have still been force loaded, I'll disable all railcraft anchors, do another reset and then see if that makes a difference

**Comment by Saereth** [comment]
ok so I unclaimed all chunks with ftbutils, I enabled the delete anchors option for railcraft then restarted, then turned off the railcraft loading option entirely. Then deleted the end again. It's still doing it. If someone is in the end which keeps it loaded, it stops.

edit: additionally, I claimed a chunk in the end and set it to keep loaded with ftb utils and its no longer doing it, but I believe this is keeping the end from resetting/dragon respawning now.

**Comment by Haggle1996** [comment]
I can't replicate the behavior, so I'm just shooting in the dark here...first thing we need to do is figure out if it's environmental or save-related. We can test this two ways:
1. Rename your world folder on the server and let it regenerate a new map, see if it occurs.
2. Copy your server map to your local client and load it up in SSP

If the problem doesn't occur in SSP or the new world regenerates The End (you may have to visit it first and kill the dragon), it's likely an environmental issue (either with the server itself -- bad java, etc., or the pack installation is corrupt). If the problem follows you to SSP and/or the new world doesn't regenerate, it's probably a save corruption.

One more option I'm willing to consider, if it doesn't take too much of my time, and you can find a way to host the archive, is to zip your server instance and I can fire it up on my test server (a known, good configuration). A quick pass with the debugging tools active can sometimes reveal a lot.

**Comment by Haggle1996** [comment]
You may also want to double-check some configuration options:

In config/etfuruturm.cfg:
`B:"Dragon respawning"=true`

In config/Reika/ChromatiCraft.cfg:

```
B:"Always Respawn EnderDragon"=true
B:"Delete End on Unload"=false
```

**Comment by Saereth** [comment]
1) I double checked all the configs, they are correct
2) The issue does NOT occur when I download the map and load it up in SSP
3) here are the server files in their entirety, warning, it's a big download, like 6+gb 
https://drive.google.com/file/d/0BwmxXoRAG3ddcGI0Y3ZzcnRZRmM/view?usp=sharing

**Comment by Haggle1996** [comment]
It's times like these that Haggle is grateful he has a gigabit connection to the internet at home. :)

**Comment by Haggle1996** [comment]
You're not going to like this. I fired up your exact server on both my Windows and Ubuntu boxes, visited The End, then left, and the behavior you describe does not happen. The only change I made was to reduce the memory to 4GB, but I can't imagine how that is affecting it. The only other difference I can see is my Windows box is on Java 74 and my Ubuntu box on Java 65.

**Comment by Saereth** [comment]
ok im gonna move this over to our other server this evening and if it doesnt happen there it'll be time to start troubleshooting hardware hah

**Comment by Haggle1996** [comment]
We've reimplemented The End in 2.7.2.0; I'm curious if this addresses your issue at all?

**Comment by Saereth** [comment]
We are updating this evening, I'll let you know!

**Comment by Haggle1996** [comment]
Any update?

**Comment by Haggle1996** [comment]
Closing this as I believe the changes to the end may have addressed this. If you continue to have issue, post a note here and I'll reopen it.

**Comment by Saereth** [comment]
Sorry for the late reply, yes it seems to be good now, thanks!
