### ISSUE TITLE
2.7.1.1 Server crashes when importing 2.6 world

### ISSUE THREAD

**Issue by Kreidos** [Haggle1996/RevolutionPack#434]
After update, the minecraft server will crash with:

> java.lang.ClassCastException: yuuto.enhancedinventories.tile.TileImprovedChest cannot be cast to Reika.DragonAPI.Base.TileEntityBase
>         at Reika.DragonAPI.Base.BlockTEBase.onNeighborChange(BlockTEBase.java:51)
> [---snip---]

I'm assuming the only option would be to remove Rotarycraft, which is obviously not an option. Full crash log attached.
[crash-2016-05-25_22.33.35-server.txt](https://github.com/Haggle1996/RevolutionPack/files/283527/crash-2016-05-25_22.33.35-server.txt)

**Comment by Haggle1996** [comment]
See #428

**Comment by Kreidos** [comment]
Thank you. I did see #428 and it describes a different issue. I performed those steps prior to even starting the server after the update.

**Comment by Haggle1996** [comment]
Okay, then you may have a legitimately corrupted chunk. If it's just one or two blocks, then it's easy to fix with an NBT editor. Look in your fml-server log for the error. Frequently it will contain the block address of the erroring block. You will need this. 

Visit [dinnerbone's coordinate tools](https://dinnerbone.com/minecraft/tools/coordinates/) and enter in the location of the block.The coordinate tool will tell you the name of the region file you need to open. Open this in your NBT editor. **MAKE SURE YOU HAVE A BACKUP BEFORE YOU PROCEED**

You will need to go to the `<chunk>/Level/TileEntities` node, where `<chunk>` is the chunk specified in the coordinate tools. Opening the TileEntities node reveals a bunch of entity entries. Search through these until you find the block at the correct x,y,z coordinate with the correct ID. In this case, it looks like you have a DragonAPI block cohabitating with an enhanced inventories chest, so I'd look for the DragonAPI block, as that's easy to refund. Versus the chest which will have contents. Anyway, delete one of the entries and save the file. Then reload.

If there are many erroring entities, you can delete just the chunk from the region file and let Minecraft regenerate it. Alternatively, if they're spread over many chunks (typically in one region only, as it's very rare to get multiple regions corrupted) you can delete the region file and let it regenerate. Obviously, this doesn't always make players happy, but it's the nuke from orbit option if you need it.

![image](https://cloud.githubusercontent.com/assets/11808184/15576133/9a0e3202-2313-11e6-9d47-a6742333db20.png)

**Comment by Kreidos** [comment]
Thank you for that very in-depth information. For now I've rolled back to the pre-2.7.1.1 backup; but I will re-attempt the upgrade later today. I'm sure given this new information I will be able to sort it out.

**Comment by Haggle1996** [comment]
If you've rolled back to 2.6, I recommend you hold off until I push 2.7.2 later today. It has a more robust upgrade process than 2.7.1.1.

**Comment by Kreidos** [comment]
Thanks, I will do that. This information should really be stickied somewhere; it seems it would be applicable to many world corruption issues.

**Comment by Haggle1996** [comment]
While I don't disagree with it being useful information, the chances of someone ever reading it without first being walked through the crash process, then directed here are...abysmal. Many players don't even read the splash screen.

**Comment by Haggle1996** [comment]
To be honest, I'm not entirely certain all of my players can read.

**Comment by Kreidos** [comment]
The 2.7.2.0 update went without issue.

**Comment by OwenGr** [comment]
Awesome. Good to hear.
