### ISSUE TITLE
Sapphires are unobtainable.

### ISSUE THREAD

**Issue by Kreidos** [Haggle1996/RevolutionPack#440]
**Yes, I know you crush lapis to get sapphire dust. I'm referring to Sapphires proper.**

A few Practical Logistics items (eg. Energy monitor) are uncraftable as there is no way to obtain sapphires directly. If there's no balance reason for this, I suggest adding a way to craft them.

**Comment by Haggle1996** [comment]
What are we going to do tonight, Haggle?

The same thing we do every night....try to fix all the pack issues!

**Comment by romanticjo** [comment]
You can make them from bees, if you are really motivated.

**Comment by Haggle1996** [comment]
Added a 4:1 recipe in the alloy smelter.
