### ISSUE TITLE
Damage numbers displayed are inaccurate for armored mobs

### ISSUE THREAD

**Issue by McFrugal** [Haggle1996/RevolutionPack#441]
http://i.imgur.com/Y5PVhaF.png
Both Dynamic Surroundings and Battletext are reporting incorrect damage numbers when attacking armored mobs.  It displays the damage you'd be doing to an unarmored mob.

This probably only occurs in SSP.  This is without disabling any of the Required mods, but I didn't install all of the optional ones.

Also I'm not sure why Battletext is present since Dynamic Surroundings is doing Battletext's job already... you get two numerical damage popoffs like this.
Lastly, Dynamic Surroundings' empty heart popoffs can't be turned off?  I tried setting damage indicators to false in the config and they still show up.  The numbers do turn off, though, which I suppose could be used to use Battletext alongside Dynamic Surroundings without redundancy.  Is a different mod causing the empty hearts to show up?

**Comment by Haggle1996** [comment]
I'll keep an eye out for the damage issue; as far as battletext and dynamic surroundings, I'll remove battletext in the next update. I didn't realize they added this functionality (Dynamic Surroundings used to be called Better Rain...and that's all it did).

Not sure about the hearts, but I'll take a look after I remove BattleText

**Comment by Haggle1996** [comment]
Also, you should not have two indicators; by default in the pack, only one is displayed. You've either played with a config or gotten a corrupted config.

**Comment by Haggle1996** [comment]
Turning off the dynamic surroundings popoff indicator...the BattleText one provides a bit more fun and information. Unfortunately, may not be able to address this. I loaded up the original Damage Indicators, and well as the Zyin's HUD info, and they're all reporting the same thing. Something interferes with the damage display. Until someone figures out what it is, not sure what I can do about this.
