### ISSUE TITLE
Suggestion(?) Update to v14a of Reika's mods.

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#447]
As the title says, I'd love to play v14 of Reika's mods. However, I'd rather not update manually as a conflict could cause problems.

**Comment by Haggle1996** [comment]
As they've only been available for about 30 minutes, be patient.

**Comment by ghost** [comment]
Yeah, I understand. Reactorcraft does have one major bug but will be hot-fixed soon.
