### ISSUE TITLE
Loading Screen Game Shows Black Screen

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#449]
When launching the newest version 2.7.3.0 all the mod loading/mojang screen shows is black. 

Nothing major or anything but makes it hard to know where it is on loading everything.

(Can provide screenshot if necessary)

**Comment by Haggle1996** [comment]
Sounds like you need to reinstall the pack. You have a corrupted resource folder.

**Comment by ghost** [comment]
Possibly, although when looking through configs one of them had an option that disabled the mojang screen or something relevant to that. Although I do not remember the name of the config.

**Comment by Haggle1996** [comment]
Regardless of you playing with the configs, installing a fresh version of the pack and moving your saves over should fix it.

**Comment by Haggle1996** [comment]
Did you reinstall 2.7.4.0 and is the problem fixed?

**Comment by ghost** [comment]
I haven't been able to play in the past couple days. I'll try tomorrow.

**Comment by ghost** [comment]
I reinstalled the pack and it's kinda fixed. The forge splash screen (the thing you see when the game loads mods) isn't appearing.

**Comment by Haggle1996** [comment]
Sounds like your `enabled=false` is set in the splash.properties file. This should be set to true.

**Comment by ghost** [comment]
It's working now, thanks
