### ISSUE TITLE
Minecraft not responsive

### ISSUE THREAD

**Issue by coetyler** [Haggle1996/RevolutionPack#45]
Every time i try to join my server that i have it causes my minecraft to freeze and not respond and then it will shut down but it seems to get stuck on this  [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: mods.natura.items.BerryMedley@77498781
[11/7/2015 21:59:50 PM] [Client thread/ERROR] [NotEnoughItems]: Failed to find identifier for: com.kentington.thaumichorizons.common.items.ItemGolemBellTH@26ee446e

**Comment by Haggle1996** [comment]
Can you put the whole crashlog into a pastebin?

**Comment by Haggle1996** [comment]
Also, you mentioned 'server'. Are other players able to join?> Have you tried reinstalling your instance of Revoluiton?

**Comment by coetyler** [comment]
i reinstalled my instance and now i have no issue so apparently it was a bad install
