### ISSUE TITLE
Overworld bug on rejoining a Rev2 server

### ISSUE THREAD

**Issue by Imotepchief** [Haggle1996/RevolutionPack#451]
Upon logging out of the server and back in without restarting the client the overworld turns in to the moon, with high jumping/slow fall and a starry sky
https://gyazo.com/8b855a436b8e7be5fca346bc6d28a5f2  -  picture of the overworld during daytime.
This issue started occurring after altering a few of the configs:
Zombie Awareness Features: Scent sense - True, Sound sense - True, Extra Spawning surface - True
Randomthings: BloodMoonSpawnLimitMult=3, BloodMoonSpawnSpeed=10

I also set server difficulty to hard instead of normal.
I have since reverted all these changes, yet the problem still persists.

**Comment by Haggle1996** [comment]
This one might take the prize for 'weirdest bug reported'. :)

I would try reinstalling the pack; first on the client side and if that doesn't work, on the server. The jumping effect and starry sky are all handled client-side, so I suspect the dimensions IDs on this instance have somehow gotten corrupted.

**Comment by Aivech** [comment]
Before you reinstall it, could you upload a .zip or similar of the instance? I'd like to try to replicate this and see what happened.

**Comment by Imotepchief** [comment]
The issue was resolved by disabling multiverse....
Still don't know why it happened, but anywho.
