### ISSUE TITLE
Map Writer seems to be "having a disagreement" with Chromaticraft

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#454]
Seems my game crashes when I'm trying to use mapwriter (crashes before getting to the main menu[crashes right after loading completion{or seems completion might just be almost completion{running out of brackets also probably not helpful}}])

http://pastebin.com/8SeyAMq7

**Comment by Haggle1996** [comment]
This seems to have become an issue within the last release or two, particularly those with AMD cards. I've been unable to replicate it, but I run NVIDIAs on all my boxes. Regardless, without a crash report or log, there's not much I can do about this other than to suggest you use a different minimap.

**Comment by ghost** [comment]
Sorry I posted the pastbin but then my net went out before I could finalize it.I use a NVIDIA GPU,Also upon taking the mapwriter out the game could make it to the news screen before the main menu before crashing.

[Edit]
Seems to be working now (without map writer)

Also I really do enjoy your modpack

**Comment by Haggle1996** [comment]
Unfortunately, I could only resolve this by removing mapwriter. Sad to see it go.
