### ISSUE TITLE
Rebalance Sleep Mechanic

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#457]
Looking for ideas to rebalance the sleep mechanic further. The new sleep mechanic has mixed reviews, with some liking it a lot and some not liking it at all.

http://www.strawpoll.me/10453584

Feel free to comment here on ways to improve it.

**Comment by Alaric323** [comment]
Is there a function to tell whether or not you're sleeping in a sleeping bag or a bed, as well as how long you've been sleeping in a bed for?  My idea revolves around sleeping in a bed for around a minute straight, which then passes time to morning.  Within that time, if mobs arrive, or you otherwise leave the bed, time does not fast forward, and neither does it happen at all if you are in a sleeping bag.  The concept is that if you can sleep in a bed for a certain period of time, you most likely have your base well enough developed to not let monsters bother you to begin with.

**Comment by DragGon7601** [comment]
I do like how the current mechanics make it so you need to set up defences. But it can make travel a lot harder. It is unlikely that I would be set up where I am if my initial exploration had required me to hide in caves for half my play time. There needs to be a balace between the 2... Either make it so monster spawns depend on light and time so they dont spawn unless its really close to midnight (I dont know of a mod for this) or bring in something like [somnia](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291170). With this you can fast forward to morning... But if you do it where your exposed, you will DIE! As it dont "skip" the night, it fast forwards it! All the spawns and stuff still happen, they just get done as fast as possible! The down side is increased load on the server. 

There also maybe other issues with somnia too. Like I would not recommend going to sleep with cross sticks in your farm, or your likely to awake to your farm being entirely weeds! Your hunger bar would go down as if you were standing there all night (Your Health regens the same way). And I don't know what other mod interactions there would be, but Im sure there would be many both good and bad.

On a side note; If the quests are redone, I think the sleeping bag should have to be crafted (preferably out of supplied materials). And rules about sleeping/tiredness/ect should be explained in this quest. This would lower the number of times we get asked "Why do I have constant hunger & weakness?".  I hate to think of how many are suffering this and don't know how to ask.

**Comment by Haggle1996** [comment]
Somnia has a lot of undesirable side affects and mod interactions; it's an interesting idea but parts of Minecraft do not do well when sped up.

I'm leaning towards bringing back original sleep mechanics (sleeping advances time) but increase the frequency of blood moons to maybe 5~10% (currently at 3%). This should make early game easier (can sleep through nights), with the random, unlucky chance that you get a blood moon early (in which case, you would have to find a hole to hide -- but you would have to do that under the current method anyway). If I can find a mod that increases likelihood of a 'bloodmoon' event the longer you've been playing, I'd be interested in using that.

I'm also going to look at a couple of alternative 'blood moon' mods, namely the [Bloodmoon Mod[(http://minecraft.curseforge.com/projects/bloodmoon) and [Apocalypse Mod](http://minecraft.curseforge.com/projects/apocalypse-mod), to see if they give better options for controlling frequency of the 'disaster' nights.

**Comment by DragGon7601** [comment]
I case you didn't know; [Mob Properties](http://minecraft.curseforge.com/projects/mob-properties) can see how high the Apocalypse counter is and have effects based on it. But I see 2 issues with using The Apocalypse mod. Firstly, FatherToast doesnt seem to be updating his mods much. IDK, maybe they are done for 1.7.10 so it don't mater. Secondly, From what I can tell; the Apocalypse counter is for the entire server. So If you come late to the server after its been up for a week or two, you are going to die! 1-hit deaths will likely be the name of the game for new players unless they are on as soon as the server starts.

**Comment by Haggle1996** [comment]
I've decided to solve this using the Epic Siege Mod. This means the sleep energy mechanic will be going away, and your bed will only be useful for setting your spawn point. ESM allows me to disable time advancement as it is today. It also features a predictable blood moon event every x days, as well as a delayed start before the world becomes hostile to new players. It adds some cool epic mob bosses. It supplants and enhances Zombie Awareness style mobs, as well as giving them new abilities like pillaring up over walls and digging through dirt tunnels.

**Comment by Aivech** [comment]
I suppose our bases will now have to become more heavily defended than Fort Knox...

**Comment by Toksyuryel** [comment]
Now this is something I can get on board with! Give me a reason to get off my lazy butt and build a proper defensive wall around my base instead of just a birch fence that somehow keeps them at bay, and also a reason to build defenses inside.
