### ISSUE TITLE
Removal of dezil´s marshmallow from loot tables

### ISSUE THREAD

**Issue by mergendil** [Haggle1996/RevolutionPack#459]
This consumable comes from Draconic Evolution, gives 10min of every buffs to their max potential.
It can appear in Sandy burrows and other loot chests

Using it will give you the ability to "superman" through most content (including tanking a horde of zombies from the last level of a roguelike dungeon, without any armor and without breaking a sweat)

Only downsides is the time required to eat it and the spoiling of the food

I suggest it's removal from the pack

**Comment by Haggle1996** [comment]
Removed in the next update.
