### ISSUE TITLE
Weird harvesting behavior with Rotarycraft Fan. v0.9.1.1

### ISSUE THREAD

**Issue by andejx** [Haggle1996/RevolutionPack#46]
Noticed some odd behavior on my server with a Rotarycraft fan farm setup.

The setup.
Steam engine, powering stone shaft, powering the fan.
The fan says it has a Harvesting Speed: 512 rad/s, which the steam engine provides.
Water source blocks along the length of the fan range to keep the tilled soil watered.

It seems that when the plants are fully grown, sometimes the fan will harvest them correctly and blow the harvested food away leaving the seed to grow again, other times it will look like its harvested the plant... but its actually not... and it wont correctly "harvest" that plant until the plant receives another block update from something. 

Had a quick search on the forum for reika's mods but didn't notice anyone else mentioning the issue, so I'm wondering if its possibly something to do with the "right-click harvesting" mechanic that some of the mods in this pack seem to be implementing and whether that's messing up the rotarycraft fan as its supposed to be "replanting" the seeds, but its just doing the right-click mechanic it seems.

"RotaryCraft Fans are used in farming to break and automatically replant crops..." 

The only real solution I've found is to have an openblocks or rotarycraft sprinkler system running which touches the plants thus randomly giving them all block updates. But it still seems as though some are just getting stuck and never being harvested correctly.

**Comment by Haggle1996** [comment]
BTW, still testing this. There are several different factors that affect the ability for the fans to harvest plants. RailCraft heat, Zombie Awareness scents, etc., all seem to impact the fans harvest ability.

**Comment by Haggle1996** [comment]
I've removed all the pack-related problems with harvesting. Rotarycraft fans are derpy and don't always blow things. Use multiple fans instead of one per 3 rows.
