### ISSUE TITLE
SSP Crash

### ISSUE THREAD

**Issue by Arctis72** [Haggle1996/RevolutionPack#461]
I tried creating a world several times and kept seeing the same fatal error at the end. And before that some...loading screen crashes?
http://paste.atlauncher.com/view/04d9be87

**Comment by Haggle1996** [comment]
Try reinstalling the pack with just Select Recommended mods. You have an old video card and some of the optional mods are very intensive on the video card (which is why they're optional. :D )

**Comment by Arctis72** [comment]
I think that did the trick! Thanks, Haggle!

**Comment by Haggle1996** [comment]
If this fixed the issue, then let's close it. :)
