### ISSUE TITLE
Simpler wooden bucket recipe

### ISSUE THREAD

**Issue by Nagapito** [Haggle1996/RevolutionPack#463]
Being the wooden bucket recipe an early required item for the quests, shouldnt it have a easier recipe?  

I know its not that hard but, unless you have a desert right next to you, getting the sealant my be more challenging

**Comment by Haggle1996** [comment]
You can make the bucket with cactus green, which drops from green dye trees as well as any cactus variety (saguero, vanilla, tiny), wax from pams beehives, candelilla (which grows in dry biomes, not just deserts), candleberries (in agricraft village structures), also by combining dandelion and lapis, picked up from dye flowers and plants, and lastly, some is provided as a quest reward.
