### ISSUE TITLE
Manasteel shows as needing iron not steel

### ISSUE THREAD

**Issue by RabidDave** [Haggle1996/RevolutionPack#464]
Lexica Botania shows manasteel as needing iron not steel

**Comment by ghost** [comment]
If I'm correct, the Lexica Botania doesn't show recipe changes. You're better off using NEI to see recipes.

**Comment by Haggle1996** [comment]
Unfortunately, the mod author designed it this way. There's nothing I can do about it. Perhaps someone in the community edition of Botania will address it.
