### ISSUE TITLE
Barrels and drawers click diferent behaviour

### ISSUE THREAD

**Issue by Nagapito** [Haggle1996/RevolutionPack#467]
On a Jabba barrel, clicking gives you a stack and shift-click one item
On drawers, this is the opposite, click gives one item and shift-click a stack.

Both mods have a configuration to choose the mode, so... maybe changing one of them so both have the same behavior?

**Comment by Toksyuryel** [comment]
Personally I'm a fan of click for single and shift-click for stack as I find that I need stacks less often than I need specific small amounts. Plus it's just what I'm used to from Regrowth.

**Comment by Nagapito** [comment]
I too think shift+click for stacks makes more sense but... after a couple days I get used to one or the other system.... As long they are consistent.

having barrels and drawers mixed and different modes of interaction is chaotic!

**Comment by Haggle1996** [comment]
Fixed by changing JABBA to match Storage Drawers (click for 1, shift+click for stack)
