### ISSUE TITLE
consider replacing journeymap with antique atlas

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#469]
It would need a skin pack to look modern... And someone would need to make that, but it would fit better with the situation... No satellites to map the world

**Comment by ghost** [comment]
Ehh, it could work but theoretically you can make a satellite/space station with GC so late game it does make sense. Also, wouldn't that kinda be futile as anyone can install journeymap since it's client-side?

**Comment by Haggle1996** [comment]
I can't prevent players from changing any aspect of the pack...but I can influence their default experience. 

As an aside, JourneyMap is also one of the biggest impacts on pack performance. I have a fairly beastly machine (4790k, 32GB RAM, SSD, 970GTX) and it's a significant improvement in performance with JourneyMap off.

**Comment by Haggle1996** [comment]
Will not implement.
