### ISSUE TITLE
Weapon Box sometimes crafts different guns from the one selected

### ISSUE THREAD

**Issue by Toksyuryel** [Haggle1996/RevolutionPack#470]
Just now on the dev server I tried to craft an M4A1 and it gave me a flame-thrower instead. I switched to my creative test world and did some playing around with the weapon box to try to figure out what happened. I can't reproduce the exact circumstance that happened on the server, but I did find what I assume to be a related problem: if you don't toggle the selected weapon before pressing the button, the weapon box always crafts a G18 100% of the time no matter what's selected. Toggling the weapon seems to make it craft what's actually selected. On the server, I had toggled before crafting when it gave me the flame thrower but I've so far been unable to reproduce this in my creative world.

**Comment by Aivech** [comment]
Could be fixed by implementing a custom recipie for weapons instead of using the Weapon Box.

**Comment by Haggle1996** [comment]
It's a desync issue between the client and server. I'm half-tempted to fix this by removing the gun, bullet, case, and weapon boxes (leaving just the customization ones) and replacing them with standard recipes.

**Comment by Taraxus** [comment]
I'd be all for this, I _really_ dislike the way the gun and bullet box interfaces work. If there were a faster way to reload magazines, I'd be all for that as well.

**Comment by Haggle1996** [comment]
Addressed by replacing Gun Customization with Techguns
