### ISSUE TITLE
Make slag easier for concrete

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#471]
Currently, it's easier to smelt gravel then chisel it into IE concrete; change the recipe for slag so that it's easier than the above.

**Comment by Toksyuryel** [comment]
I can see this being an issue later in the game when gravel is cheap, but early on I find gravel to be at quite a premium and much prefer the slag recipe for making concrete.

But I also think I'm probably the only person who actually uses coarse dirt in any great quantity.

**Comment by Haggle1996** [comment]
I've changed this so that slag can be smelting in a furnace, producing concrete.
