### ISSUE TITLE
Chromaticraft dependancy loop in V14d

### ISSUE THREAD

**Issue by Whaffles** [Haggle1996/RevolutionPack#473]
In the version of Chromaticraft currently in the latest version of Revolution 2 (2.7.5.0), all endgame Chromaticraft content is gated behind a dependency loop (at the "Lumen Leaves" fragment & "Recharging" progression stage).

v15 of Reika's mods fixes this bug.
Source: https://sites.google.com/site/reikasminecraft/changelogs

So, yeah, it would be another tiny update for everybody, but at least we had a couple weeks since the last one. ^_^

**Comment by ghost** [comment]
If you think you get the Recharging progress for charging off of lumen leaves, you're wrong. You get it by putting eight power crystals around a pylon.

**Comment by Whaffles** [comment]
Yeah, I'm aware of that, and its unrelated to the problem.

To be clear, the Lumen Leaves fragment - the thing that lets you make the Luminescent Battery that you need to make the Lumen Tree in the first place - is dependent on progression (possibly "Recharging") that you need knowledge of the Lumen Leaves fragment to get to.

I linked Reika's changelog because he notes this issue in the patch notes for V15.
"ChromatiCraft: Fixed Lumen Leaves fragment dependency loop"

Took me the better part of an hour refining google searches to finally figure out this was an issue, though. X_X

**Comment by Haggle1996** [comment]
These are core mods. They're updated when the pack updates.
