### ISSUE TITLE
Solved: Paralysis when eating

### ISSUE THREAD

**Issue by Midconet40** [Haggle1996/RevolutionPack#474]
No matter what I eat, fresh or old, I get a paralysis debuff for a long period of time.

**Comment by ghost** [comment]
I haven't experienced this while eating (Sure others haven't either). 

You could try re-installing the pack to see if it persists.

**Comment by Haggle1996** [comment]
Yeah, it sounds like your potion IDs are corrupted. You should try
reinstalling your pack.

**Comment by Midconet40** [comment]
Seems like it was a ID conflict between the server and client mods

**Comment by Haggle1996** [comment]
Okay. Closing this issue.
