### ISSUE TITLE
Immersive coal coke not accepted by Rotarycraft blast furnace

### ISSUE THREAD

**Issue by Nagapito** [Haggle1996/RevolutionPack#476]
If Rotarycraft does not support minetweaking the blast furnace, maybe shapeless recipes to convert between the two coal cokes?

Or change the IE coke oven to produce Rotarycraft coal coke its accepted in the IE blast furnace?

**Comment by Haggle1996** [comment]
They used to be ore-dicted together, until I was told I cannot do this.

**Comment by Nagapito** [comment]
I assume Reika, right?

If it was Reika, I understand if he doesnt want them ore-dicted but what is his opinion of a shapeless recipe to convert bettween them or even the IE blast Furnace output Reika coal coke instead of IE coal Coke?

If he isnt against, that would solve the problem, the later solution even better, since it allowed to just 'remove' one type of coal coke from the game.

If he is against all the solutions... I guess... we (I) have to respect it.

**Comment by Haggle1996** [comment]
How would that be any different than having them in the ore dictionary?

**Comment by Nagapito** [comment]
To be honest.... yeah... its not different. :)

I guess he doesnt want it ore-dicted so players cant skip progression but... his coal coke is WAY easier and faster then any other method of producing coal coke... so... no reason to skip it. And the other machines already accept his coal coke, so we can already 'skip progression' on other mods with is coal coke....

But if he does not want it....
