### ISSUE TITLE
Suggestion: Remove Climatecontrol

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#478]
Rationale: climate control makes climate less plausible, not more. Snowy biomes neighbouring deserts, snow in the desert, frozen ocean neighbouring a desert, tiny patchwork biomes. Finding a place to build that looks plausible in terms of biomes and climate has proven to be a challenge.

**Comment by Haggle1996** [comment]
See #477 for the reasoning.
