### ISSUE TITLE
Suggestion: Add Steve's Factory Manager

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#479]
I personally think SFM would be a nice addition to Rev|2 for more compact (potentially advanced) automation. However, I do not know if it was not added for other reasons in the past. 

If this is added, Steve's Addons should be added too as it allows copying commands from one SFM controller to another. Does add RF transfer too but probably easier to use cables for that.

**Comment by Haggle1996** [comment]
SFM used to be in REV|1.

Besides making things too easy, SFM caused horrible world corruptions (as in true, region-corrupting problems). It's been abandoned by it's author for a very long time.

We had some hope that Advanced Systems Manager (a fork of SFM by the author of Steve's Addons) would solve the issues with SFM; unfortunately, it also caused horrible world crashes and corruption, and was then left unsupported by the author.

But even if all the bugs weren't present, SFM bypasses all the difficulty mechanics routing conduits and cables, allows for infinite transfer of RF, fluids, etc. Of all the mods I added to REV|1, I wholly regret adding SFM.

**Comment by Haggle1996** [comment]
#141

**Comment by ghost** [comment]
Huh, I've never experienced corruption or crashing from SFM.

Since it's not going to be added then, is there some type of machine/device that can drop only a certain amount of items and won't drop more of the item until the other item is gone?
Basically like the rapid item valve.

**Comment by Haggle1996** [comment]
There are several; Logistics Pipes for example.

**Comment by ghost** [comment]
I... have never used Logistics Pipes. Wonder how easy it is...

**Comment by Aivech** [comment]
You can also use a system with:
- Botania's Open Crate, or a redstone-sensitive Formation Plane setup, or a redstone system and a dropper.
- A [Weighted Pressure Plate](http://minecraft.gamepedia.com/Weighted_Pressure_Plate)

Of note is that an ItemStack entity containing multiple items counts as one entity for the plate.

Alternatively you can use an inventory+comparator system. There's lots of ways to do this.

**Comment by ghost** [comment]
Already found a solution a week ago similar to this using a hopper and pressure plate.
