### ISSUE TITLE
Marble is not enabled in world generation

### ISSUE THREAD

**Issue by Nagapito** [Haggle1996/RevolutionPack#480]
Since marble is not enabled in world generation, which I am kinda guessing the reason, why is it then enabled in the possible chisel blocks?

Although, I would prefer if there was some way of craft it instead of just totally disabling it and all the other chisel world generation blocks...

And please, do not tell me that I will have to wait until I can power an RFTools dimension to have some marble blocks on my base floor :P

**Comment by Haggle1996** [comment]
Marble spawns fine; I just tweaked it down significantly so it only spawns in large, but very rare blobs.

**Comment by Nagapito** [comment]
My bad... I only looked at chisel config, keep forgetting about COG...
And is anything on the pack to help find this blobs, since they are so rare? Kinda dont want to go making holes everywhere...

**Comment by Haggle1996** [comment]
No, there's no biome preference for the material. It generally spawns around y67, but can be as far down as y6, or up to y120, with the distribution curve centered over y67. It has approximately a 1.4% chance of spawning per chunk, so approximately 1/70 chunks will have a marble spawn, but your RNG gods may vary. Also, as the distribution is weighted around y67, locales without a y67 (such as ocean) are much less likely to generate the ore.

It spawns in large, flat disks, not veins.

**Comment by Nagapito** [comment]
Brb... going to sacrifice a couple goats at the RNG Altar.... :)

**Comment by Nagapito** [comment]
Maybe you might want to tweak this a little for Revolution 3 coz right now its even more rare then diamonds or emeralds since those ones have flowers pointing a direction!

I am not using Geostrata and I dont know if they are 'compatible' but without it.... its insanely rare! I agree that Chisel block generation is abusive but this makes me want to build with diamond blocks since they are more common!

And when you find a vein, its just a couple blocks! 
Managed two find 2 veins on highlands... I got 2 and half stacks.... Sorry for the rambling but, Chisel marble blocks have some unique properties that make them one of the more attractive blocks and being so rare...

Edit: Almost forgot.... And its a little infuriating to try finding marble and keep seeing quarry stone every where!

**Comment by Haggle1996** [comment]
You're also welcome to increase the frequency in newly-generated chunks by changing saves\DIM0\CustomOreGen_Options.txt and setting `chslMarbleFreq=1.0` higher than 1.0. 2.0 = 2x more frequent. I wouldn't recommend more than 4x, unless you like world gen to crawl. `chslMarbleSize=1.0` affects the size of the vein.

**Comment by Haggle1996** [comment]
Also, there's transmutation recipes for these blocks.

**Comment by Nagapito** [comment]
I already have a 200 chunk radius pregened... :(

And... transmutation recipes? NEI shows nothing... Is that a Chromaticraft? I am a total noob on Reika mobs and just discovering as I progress
