### ISSUE TITLE
R3: Blast Resistance

### ISSUE THREAD

**Issue by Leftorius** [Haggle1996/RevolutionPack#483]
We talked yesterday and I know what's coming so I don't know what your progress is but I want to help a little bit with some informations:

You can configure all blast resistance of open modular turrerts blocks! :) Hope it will help you, wanted to post this on irc but I think we can help you here more with just informations? 

and if you want to find out in an easy way wich blast resistance is there on a block, you can use wawla for this (config -> wawla general -> blast resistance)

**Comment by Haggle1996** [comment]
Probably not relevant anymore, since I changed what zombies can break. Now it's a whitelist and it's limited to unimproved stone, cobblestone, dirt, sand, gravel

**Comment by Aivech** [comment]
> a whitelist and it's limited to unimproved stone, cobblestone, dirt, sand, gravel

Does this whitelist support OreDict entries, and are Chisel and ExU variants of these oredicted?

**Comment by Haggle1996** [comment]
It does not.
