### ISSUE TITLE
DragonAPI crashing with UUID error

### ISSUE THREAD

**Issue by wsetzer** [Haggle1996/RevolutionPack#484]
I'm trying to run Revolution 2 v2.7.5.0, and I'm getting the following error at the beginning of stage 5/7 in forge:

[Client thread/ERROR] [FML]: Caught exception from DragonAPI
java.lang.IllegalArgumentException: Invalid UUID string: affe50759da749c1952dc0e69d906699
    at java.util.UUID.fromString(Unknown Source) ~[?:1.8.0_77]
    at Reika.DragonAPI.Auxiliary.Trackers.PatreonController.addPatron(PatreonController.java:115) ~[PatreonController.class:?]
[...]

I can provide a larger crash log if you like, but this seems like a fairly straightforward error in Dragon API.

**Comment by MrWisski** [comment]
Yup. just ran in to it. both server AND client both fail to load with this error.

Checked the UUID - it does match a player. Checked the file on reika's donator server...it looks OK (tho this is my first time seeing it - dunno what changed to break everything). Not entirely sure why this would be invalid, but reika isn't catching exceptions in this function T_T.

On the bright side, I do believe reika plays his own mods on a regular basis, and I kind of expect a quick fix from him.

**Comment by MrWisski** [comment]
yup. client and server just came up - this appears to be corrected now :D
