### ISSUE TITLE
RoC/ReC/CrC and PneumatiCraft liquids stored in Extra Cells fluid cells ceased to work (upgrade issue only)

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#485]
After upgrading to 3.0.0.1, I found I couldn't interact with any of my liquids from PneumatiCraft and from any of Reika's mods which were stored in Extra Cells fluid storage cells. Import/Export buses didn't work, terminals didn't work, interfaces didn't etc.. When making _new_ fluid storage cells, newly-generated or collected liquids do work, but there was no way to retrieve what was already stored. Extra Cells blocks and items which were configured before upgrading started working again as soon as new liquid was stored in new fluid storage cells.

Workaround: cheat a creative storage upgrade from JABBA in. Cheat in a filled liquid container and put it into a creative-upgraded barrel. Pipe the now-infinite containers out into an EnderIO fluid tank which will fill the tank from the container. Pipe the empty container out into a trashcan. Cheat in new fluid storage cells and configure them, take the old ones out of your ME drives and delete them, and import the new liquid from the tank using a fluid import bus.

**Comment by Aivech** [comment]
Alternatively you can use an RoC magic wand on a reservoir (might want to go into creative mode first lest you spontaneously combust or something), or the EnderIO creative buffer (not 100% sure on the last one)

**Comment by Haggle1996** [comment]
Unfortunately, fluids have this issue, as mods that don't use Forge's fluid registry don't support getting swapped around. 

What might be an easier alternative is to revert to 2.7.5.0 save, install the R3 update, temporarily disable TiCo and Jsonables (by renaming their JARs to *.JARX), load the save once in R3, then reload the pack with those mods enabled. That will force their IDs after the list.

**Comment by Haggle1996** [comment]
I'm going to close this, solely because I can't do anything about it. Thanks for posting the workaround!
