### ISSUE TITLE
[Simple Issue] Re-enable sleeping?

### ISSUE THREAD

**Issue by sstarnes3** [Haggle1996/RevolutionPack#487]
So to start off, sorry if this is the wrong place to post this. I'm not really sure where to go to get help with this sort of thing. Normally just reading the mod or modpack's website would get me the answers I need but this time I can't find anything that's helpful. 

So I added the Somnia mod to the revolution 2 pack. (For those that don't know it's a mod that allows you to simulate the night instead of skip it)

The first time I booted up revolution 3 the mod still worked fine and I was able to simulate nights. However, the second time I booted it up I was no longer allowed to sleep at all. I only get the message "spawn point set" in chat.

What I need is simple, I need to know what is disabling my ability to sleep and how to re-enable it.

Again sorry if this is the wrong place to post this but all google searches I did led me to the minecraft wiki to tell me what a bed was. Thank you in advance for any helpful post I get.

**Comment by Haggle1996** [comment]
I hope you figured this out...if not, it's in ESM.cfg; sleeping=true

**Comment by sstarnes3** [comment]
I was about to buck up and just play the the game just sitting through the night watching youtube videos in another tab. But then I was like 'hey I should check that forum post and maybe re-open it for others with my problem.' And you totally saved it dude. Thank you so much!
