### ISSUE TITLE
[Request]Add Automagy

### ISSUE THREAD

**Issue by vcordie** [Haggle1996/RevolutionPack#49]
Automagy is a thaumcraft addon which adds additional automation to thaumcraft. A pure thaumcraft ae like system, wireless redstone, autocrafting with golems, automatic cow milking, etc. I'd love for it to be in the pack by default.

**Comment by Haggle1996** [comment]
Permissions requested from author.

**Comment by Haggle1996** [comment]
And obtained. Added in next version.
