### ISSUE TITLE
Random Crashes (Dev Server 1)

### ISSUE THREAD

**Issue by andresmarver** [Haggle1996/RevolutionPack#490]
While playing in Dev#1, I randomly crashed three times, at three different locations, in three different time periods.

I have BoP, Bibliowoods BoP, Natura, and Bibliowoods Natura disabled.

[crash-2016-07-11_20.38.09-client.txt](https://github.com/Haggle1996/RevolutionPack/files/358579/crash-2016-07-11_20.38.09-client.txt)
[crash-2016-07-11_22.19.24-client.txt](https://github.com/Haggle1996/RevolutionPack/files/358580/crash-2016-07-11_22.19.24-client.txt)
[crash-2016-07-11_23.52.22-client.txt](https://github.com/Haggle1996/RevolutionPack/files/358581/crash-2016-07-11_23.52.22-client.txt)

**Comment by Haggle1996** [comment]
Something is contending with your sound driver. Sometimes a full power off
then on can address it. It can also be a driver problem. I've encountered
it a couple of times over the years with other modpacks; sometimes, just
starting minecraft first, then whatever you're streaming, is enough to fix
the issue.
