### ISSUE TITLE
OS error in OpenComputers computers connected to medium to large RotaryCraft/ReactorCraft builds 

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#492]
The problem:

ReactorCraft and RotaryCraft tile entities automatically register themselves as OpenComputers components. That makes interactions easy, and it means that if you connect an OC computer to a RotaryCraft/ReactorCraft tile entity, all other tile entities connected to this one will also be visible to the computer. This, too, is very useful, but it means that the number of supported components is easily exceeded, resulting in an OS error and making the computer unusable. Large builds like a fusion reactor can have more than 2000 connected components, while the default limit for a tier 3 computer is 32 (or 48, for a server with a tier 3 component bus).

The solution:
Set the third entry in the parameter list "cpuComponentCount" in  OpenComputers.cfg to something very large. I have used 32767. 

Edit:
These large numbers come about because _every_ tile entity of RoC/ReC registers itself, including steam lines, neutron absorbers, gearboxes, dynamometers, HP turbine blocks etc.., and in a reactor they are necessarily all connected in some way. It is not possible to split these builds into smaller groups. Even a standard RoC factory setup can easily exceed the default limit.

**Comment by Haggle1996** [comment]
Thanks, DaMachinator! I'll get this merged into the next update.
