### ISSUE TITLE
After upgrading to 3.1.0, the fusion reactor ceases to produce neutrons after a time 

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#494]
As the title says: after starting up a fusion reactor, it runs for about 10 minutes and generates power, and then it ceases to produce neutrons for no discernible reason. I tried an old version of my build and the current one with both versions of the pack, and the behaviour is consistent: the reactor runs without any problem for 45 minutes (I stopped testing after that time) and shows no sign of acquiring a problem in 3.0.0.1, but it runs for about 10 minutes and then ceases to make neutrons in 3.1.0.

**Comment by Haggle1996** [comment]
I'm not sure what could be affecting it...so little was changed between 3.0.0.1 and 3.1.0. You could try removing Fossils and Archaeology and Electrical Age, see if it's somehow a mod interaction problem. The versions of Reika's mods are unchanged.

EIO was also updated; perhaps something is not feeding where it's supposed to?

**Comment by Ieldra2** [comment]
I was monitoring my reactor and all supply chains were working perfectly fine. Also, Enderio shouldn't be a problem in the first place since all of my reactor supply chains use either bedrock pipes or export buses. I'll do some testing with a new instance in the next few days to get to the bottom of this, but for now I simply downgraded.

**Comment by Ieldra2** [comment]
Found the problem: I have the problem, again, with some fluids stored in Extra Cells fluid storage cells not adapting to a changed id or something like that. This time, nitrogen and deuterium wasn't affected but tritium was, so my fusion reactor didn't get any tritium after the initial filling of the preheaters was used up.

Isn't there a way to get around that? It is rather annoying to have to cheat 50-250 kB of each of a handful of fluids in after every upgrade.

**Comment by Aivech** [comment]
> mods that don't use Forge's fluid registry don't support getting swapped around.

Unfortunately, we cannot force every mod author to use the Forge fluid registry, and it is not practical to find and remove those mods that do not.

**Comment by Ieldra2** [comment]
..but it the Forge fluid registry really the problem? If I store my liquids in drums they appear to convert fine... it may be something with Extra Cells.

**Comment by Haggle1996** [comment]
The mod at issue is extra cells and it's method of storing fluids. Perhaps bedrockium drums attached through a fluid bus would alleviate the problem?

**Comment by Aivech** [comment]
The fluid storage bus has in the past had its own far more severe issues.
These may be fixed by now - I certainly hope so.
