### ISSUE TITLE
Immersive Engineering - Industrial Coke Oven

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#498]
Still using old times, not updated to 3.1.1 speeds.

**Comment by devanchya** [comment]
Coal Blocks are also ignored in the Immersive Engineering setup.
MineTweaker Patch below

`# Coke oven produces coal coke faster
mods.immersiveengineering.CokeOven.removeRecipe(<ImmersiveEngineering:material:6>);
mods.immersiveengineering.CokeOven.addRecipe(<ImmersiveEngineering:material:6>, 500, <minecraft:coal>, 240);
mods.immersiveengineering.CokeOven.removeRecipe(<ImmersiveEngineering:stoneDecoration:3>);
mods.immersiveengineering.CokeOven.addRecipe(<ImmersiveEngineering:stoneDecoration:3>, 4500, <minecraft:coal_block>, 2160);
`

**Comment by Haggle1996** [comment]
Thanks, devanchya! I'll get this merged in next I'm back.

**Comment by Haggle1996** [comment]
Merged in the next update.
