### ISSUE TITLE
Revolution Server.

### ISSUE THREAD

**Issue by Lishem** [Haggle1996/RevolutionPack#499]
When i make a Server it starts up fine, i port forwarded, my friends join and everything. But when we use any of the mod items that aren't in regular minecraft you can't craft them. It's like all of the mods arnt compatible or something yet it just doesnt let you use anything that revolution installs on the server.
Any Help D:
Thanks,
Spencer Morris

**Comment by Haggle1996** [comment]
The only time I've ever seen anything like this is when there's been a mismatch of mods between the clients and the server. Make sure you 'Select Recommended' for both the client and server installations.

**Comment by Lishem** [comment]
Where is Select recommended?

**Comment by Haggle1996** [comment]
After selecting the pack to install and entering it's name, you're presented with a list of optional mods. The 'Select Recommended' button is on the bottom.
