### ISSUE TITLE
Duplicate Recipe

### ISSUE THREAD

**Issue by LordIconMC** [Haggle1996/RevolutionPack#5]
Wooden Lattice and Rotary Craft wooden gear have the same recipe so you cant create wooden gears.

**Comment by Haggle1996** [comment]
Good catch! Fixing now

**Comment by Haggle1996** [comment]
Fixed on the development server -- players do not need to do anything, it just magically fixes itself (go minetweaker!) It will be in the next configuration update of the pack;.
