### ISSUE TITLE
Screenshot option not being saved in EiraIRC

### ISSUE THREAD

**Issue by jusvit** [Haggle1996/RevolutionPack#502]
Can't update  Auto-Perform-Action, might be due to old configs.

**Comment by Haggle1996** [comment]
Is this the same as https://github.com/blay09/EiraIRC/issues/343 ?

**Comment by jusvit** [comment]
No, that'sabout default turning it on.

**Comment by Haggle1996** [comment]
Closing, as I can't do anything about this. I'll keep an eye on Blay's issue tracker.
