### ISSUE TITLE
Rev1 installation issue ("update" downgrades to 1.2.3.0 and all new instances are this version)

### ISSUE THREAD

**Issue by DragGon7601** [Haggle1996/RevolutionPack#504]
We have had <mikeb> on the IRC with an installation issue. Rev1 told him it wanted to update, so he let it. And it downgraded to 1.2.3.0. He believes 1.5.0.1 is the latest version for Rev1.

I checked what it had to offer if I tried for a new install, 1.2.3.0 was the latest. 

I looked over the Website (http://revolutionpack.info/) to see what the latest it said was... Couldn't find a version number but it looks like the latest post was for v13 of Reika’s mods (http://revolutionpack.info/post/2600-1500/). Tried to see what the ATLauncher site said... No longer lists Rev1. :S 

So I have no way of confirming what the latest version is meant to be, but if the second number of that post is the rev1 version then it is at lest 1.5.0.0.

**Comment by Haggle1996** [comment]
1.5.0.1 is the last version of REVOLUTION|1

**Comment by Haggle1996** [comment]
I see what the problem was -- a previously-linked file was no longer available. It should appear now on the launcher.
