### ISSUE TITLE
[suggestion] Remove these RecurrentComplex structures

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#506]
I suggest removing these RecurrentComplex structures from the active-folder:
- depot
- dormitory
- dormitory_kid
- local_archive
- warehouse

These are not working with enviromine/will break due to physics.

**Comment by Aivech** [comment]
This is intentional. Centuries-old buildings are unlikely to be structurally sound.

**Comment by ghost** [comment]
True, but the fact that they fall apart only once you come across them is rather silly.

**Comment by Haggle1996** [comment]
Why? Old floors don't collapse when walked upon?

**Comment by ghost** [comment]
They should've collapsed sooner if zombies, skeletons, etc have walked on it prior to the player being there. As from what I can tell, zombies have existed for at least a few years before the player woke up. Therefore, some of the buildings should've already collapsed due to activity there (spawners).
