### ISSUE TITLE
No way to heal

### ISSUE THREAD

**Issue by ray10k** [Haggle1996/RevolutionPack#509]
I recently updated to 3.1.1, and now I seem unable to recover lost health, neither by eating food or by having saturation. This led to an extremely tense situation where I had only 1 heart while in the middle of a mining session.
I have not tried potions of health/regen, yet.

**Comment by ray10k** [comment]
As best I can tell, healing/regen potions work.
That said, I would like to know if this is a bug, or an unreported feature to make early game more difficult.

**Comment by Haggle1996** [comment]
My apologies for the delay; most players ask for help in the support IRC channel. Yes, natural regeneration is off on purpose. Eating will restore half the food value in health. Potions, besides being craftable, can be found in many dungeon chests. There are also a variety of magical means for obtaining regeneration -- many of which are obtainable relatively-early in the game. Certain world-generated features also cause regeneration when you're in proximity to these features (no spoilers, though).

**Comment by ray10k** [comment]
Fair enough, but eating does not restore any health for me either.
For proof, please look at this (spoiler alert for some chromaticraft stuff):
https://youtu.be/YZ59QC5woqo?t=922
As can be seen, I have some damage, eat some food, but do not recover any of my lost health.

**Comment by Haggle1996** [comment]
By any chance, did you turn off Hunger Overhaul from the mod list? This is what enables food to heal you.

**Comment by ray10k** [comment]
On closer review: Yes I did. Thank you for helping me, and best of luck with the pack!
