### ISSUE TITLE
Normal Earth Gravity on Moon

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#510]
The moon has Earth-like gravity and the air tank reserves are not showing up in the HUD

**Comment by Haggle1996** [comment]
Is this on DEV #1 or #2?

**Comment by Pterodactlol** [comment]
Dev #1

**Comment by Pterodactlol** [comment]
Further testing has revealed that this problem is more extensive. The gravity is earth-like, the sky is earth-like (as in, the Moon and Sun appear as on Earth even where they should not), and the oxygen tank GUI does not appear on all planets and space stations, with the exceptions of the Asteroid and Kuiper Belts.

**Comment by Haggle1996** [comment]
Closed by removing the mod.
