### ISSUE TITLE
Remove Dezil's Marshmallow from loot chests

### ISSUE THREAD

**Issue by WidjettyOne** [Haggle1996/RevolutionPack#511]
Dezil's Marshmallow is an overpowered food item from Draconic Evolution. It's supposed to only be available for the player named 'dezil', and [shouldn't be obtainable](https://github.com/brandon3055/Draconic-Evolution/issues/201) in any other way. However, it's appearing in loot chests from Chromaticraft, specifically the hidden chest in the 'spiral' buildings on top of the Nether. It appears in stacks of 15 or so.

The marshmallow completely fills the hunger/satiation bar, and gives the effect of every positive potion, at a very high level, for 10 minutes. Once you've eaten a marshmallow, you can kill the wither by punching it a couple of times, because the strength potion effect is so strong. You can also jump at least 5 blocks in the air, and you take no damage from lava.

**Comment by jusvit** [comment]
Is it a one time use?

**Comment by WidjettyOne** [comment]
@Dimmerworld It is, though given that one chest had 30 of them, and 1 use is enough to trivially kill the wither, the Gaia guardian, or the End Dragon, it's still quite broken.

**Comment by Haggle1996** [comment]
Are you on the latest version of the pack? They were removed a couple of updates ago from the loot chest list, but if the loot was already generated, it may still be in some chests (though they do rot).

**Comment by WidjettyOne** [comment]
No, I'm still on Rev 2 actually. So it's probably fine now. Sorry to bother you.
