### ISSUE TITLE
Matter Overdrive Sniper Scope Uncraftable

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#512]
The glass pane required in the recipe for the Matter Overdrive Sniper Scope has an item ID of 102:13, which renders it uncraftable.

**Comment by Aivech** [comment]
This should be easily fixable via a minetweaker recipe, and is a known bug with Matter Overdrive.

**Comment by Aivech** [comment]
Could you please post a screen capture of the recipe? I'll try to make the requisite script.

**Comment by Aivech** [comment]
Hopefully fixed by https://github.com/Haggle1996/RevolutionPack/commit/80b38a71eb265f92dc48a75c1c2bce246ae5aaaa .

I'll need someone to test it, though, since this is the first time I've ever made a MineTweaker script. Hopefully I got all the item names right.

**Comment by Haggle1996** [comment]
Thanks, @DaMachinator!

**Comment by Aivech** [comment]
So it works?

**Comment by Haggle1996** [comment]
I had to tweak it since the latest update to Matter Overdrive changed some item names, but yes it works.

**Comment by Aivech** [comment]
That's probably not true - those were the item names from the 1.10 code.

**Comment by Haggle1996** [comment]
Ah...maybe it's in reverse -- I had to backdate the item names to match 1.7.10. Regardless, it works now.
