### ISSUE TITLE
Ocean freezing over winter stays frozen

### ISSUE THREAD

**Issue by chrisduran** [Haggle1996/RevolutionPack#513]
I'm by the ocean in a plains biome, and the ocean next to me froze over in winter. That was cool! Unfortunately, it never unfroze, even through a full summer cycle.

Interestingly, I had some frozen water blocks near my crops that never unfroze in summer either.

I'm testing a few things to see if I can figure it out, but thought I would post here on the off chance somebody has come across the problem before me. I switch the HarderWildlife config to metric half-way through play (maybe in winter) - I've switched back to see if that is the culprit. UPDATE: either it wasn't, or the damage was done. I would assume that metric/imperial would have been purely aesthetic.

I posted to the Harder Wildlife mod thread, as it seems at least one other person has come across this earlier in their thread. The dev replied that they are unable to reproduce but will likely look at the logic for their 1.10 update.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2451299-reasonable-realism-its-a-pack-its-a-mod-it-makes?comment=1008

At any rate, I thought to submit this issue regardless, as I thought you may want to know about this possibility.

See attached screenshots for the issue as described.
![screen shot 2016-08-05 at 9 18 42 pm](https://cloud.githubusercontent.com/assets/939252/17435069/669fa662-5b62-11e6-830d-490e5f5abd36.png)
![screen shot 2016-08-05 at 9 39 19 pm](https://cloud.githubusercontent.com/assets/939252/17435070/66a07efc-5b62-11e6-9e4f-ce362a504cc0.png)
![screen shot 2016-08-05 at 9 39 29 pm](https://cloud.githubusercontent.com/assets/939252/17435071/66a7eb92-5b62-11e6-8fc2-8116dbfafd4e.png)

**Comment by Haggle1996** [comment]
Thank you for reporting this. I've noticed this as well since the last few updates of Harder Wildlife. Best I can offer at this point is to recommend you turn off seasons if it's causing problems for you.

**Comment by chrisduran** [comment]
No worries, that was the solution I came to also. 

For the benefit of others that may read this: After turning off seasons, I installed and used a mod called WorldEdit to fix up the affected area: there is a command called /thaw that will melt the ice/snow in a specified radius.

**Comment by Haggle1996** [comment]
You can also use /cofh replaceblocks to replace ice with water.
