### ISSUE TITLE
Draconic Evolution Armor uncraftable

### ISSUE THREAD

**Issue by DrunkenSquirrel** [Haggle1996/RevolutionPack#516]
One of the ingredients in the wyvern armor pieces is diamond armor of the same type, but diamond armor has been deactivated and has no recipe.

**Comment by DorinnB** [comment]
#465 
You can loot them on mob or treasure chest.
I had to farm lower roguelike dungeon for all part but boot.
Boot was looted on treasure chest but not called "diamond boot" (sorry I can't remember the name. It's an enchanted custom boot)

**Comment by Haggle1996** [comment]
Yes, it is intended that you farm the dungeons for these items.
