### ISSUE TITLE
Can't install after selecting optional mods.

### ISSUE THREAD

**Issue by Trackmurk** [Haggle1996/RevolutionPack#517]
Hi. As the title says, I want to install Revolution 3. If I do it normally (only the required mods) it's ok. It downloads and it's playable. HOWEVER when I add optional mods or the recommended ones, message pops up saying Revolution 3 3.1.1 Wasn't installed. Can somebody help me? I would really appreciate it :)

**Comment by jusvit** [comment]
Ubselect journey map than manually install it after

**Comment by jusvit** [comment]
Unselect*

**Comment by Trackmurk** [comment]
oh..OH..THANK YOU DUDE, IT WORKS!!

**Comment by Haggle1996** [comment]
Unfortunately, JourneyMap's distribution license doesn't allow me to cache it -- it must always be downloaded live from the curse site, which sometimes goes down.
