### ISSUE TITLE
Wyvern armor uncraftable requires diamond armor which is uncraftable :/

### ISSUE THREAD

**Issue by Unistic** [Haggle1996/RevolutionPack#519]
Hey,

Did alot of work to get this draconic ignots lol. The recipe for diamond armor is uncraftable and it says use rotarycraft steel instead.  Rotarycraft steel isn't usable in place of diamond within the wyvern armor recipe which still requires diamond armor in order for you to craft it.

So please enable diamond armor craft-able usable for recipes.

Please, Thank you!

**Comment by Aivech** [comment]
Go through the Roguelike Dungeons and kill mobs to get armor. Then repair it in an anvil.
