### ISSUE TITLE
[ENHANCEMENT] Add bee progression for nuclear materials

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#52]
Make it possible to research bees that produce certain nuclear elements.

**Comment by Solego** [comment]
Hell
Yes

**Comment by TheMachinator** [comment]
Make it have a low chance of producing nuclear waste, maybe

**Comment by Haggle1996** [comment]
Ooo...I like that idea.

**Comment by TheMachinator** [comment]
In retrospect, that was a bad idea.

**Comment by TheMachinator** [comment]
Maybe we could have them spawn only in hives in randomly generated Reccurent Complex structures and give them some nasty effects for the player to breed out of them.
Radiation poisoning perhaps?

**Comment by DaMachinator** [comment]
If I can find some documentation on how this works I might be able to work on this.

**Comment by Haggle1996** [comment]
The documentation is buried on bdew's site (it's Gendustry that adds custom bee progression). I pulled out Binnie's Extra Bees/Trees in favor of doing the custom progression. However, a better source for how to do this is the Beyond Reality modpack, also on ATLauncher. I wanted to do bee progression similar to how they did it for GregTech. They added dozens of custom bee species.

If you don't get around to this, I will soon. Bees are going to be important to the HQM quests.

**Comment by DaMachinator** [comment]
I found the documentation. Bdew could do with some site maintenance time.

**Comment by Haggle1996** [comment]
Replaced by #139
