### ISSUE TITLE
Server Doesn't Load After Adding IP To Config File

### ISSUE THREAD

**Issue by NateConnell** [Haggle1996/RevolutionPack#520]
The server crashes with message: 
[15:47:21] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:47:21] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by Haggle1996** [comment]
Please post the full crash log to pastebin.com or gist, then post the link here; i can't help you with what you've provided.

**Comment by NateConnell** [comment]
http://pastebin.com/ESzneQt4

**Comment by Haggle1996** [comment]
You need to dedicate more RAM to the pack. :)

The `java.lang.OutOfMemoryError: Java heap space` error indicates Minecraft ran out of memory. Looking at line 30 `Memory: 90211184 bytes (86 MB) / 1819803648 bytes (1735 MB) up to 1908932608 bytes (1820 MB)` shows you only have 1820 MB allocated. You'll need to dedicate a minimum of 3072 MB, for the pack to run.

**Comment by NateConnell** [comment]
Thanks!

**Comment by NateConnell** [comment]
Wait, can this be reopened? I spoke too soon and it still doesn't work. No crash log made for the past three tries. Still trying...

**Comment by Haggle1996** [comment]
It can be reopened, but without a crash report or error log, I couldn't help you anyway. If you have an updated log, please post it.

**Comment by NateConnell** [comment]
Nope sorry, I'll search on the internet for answers, thanks anyway!
