### ISSUE TITLE
Mutant Enderman

### ISSUE THREAD

**Issue by CodingManDan** [Haggle1996/RevolutionPack#521]
Mutant Endermen are crashing my server. I think whats happening is chromaticraft Lumen Turrets are shooting a Mutant Enderman and they are trying to teleport to me but I am offline (if you notice I am not online, my username is Danco_CEO in MC) 

Crash #1
http://pastebin.com/VLZgLuZT

Crash #2
http://pastebin.com/C4WZndPi

**Comment by CodingManDan** [comment]
After some testing I can recreate this issue by placing a Lumen Turret next to a mutant enderman then logged off (while a friend was still online watching) when the Mutant Enderman dies the server crashes.

**Comment by devanchya** [comment]
this would be a bug in Mutant Creatures.   The Enderman attach to a Person to do the "Blackhole" attack at the end,

**Comment by Haggle1996** [comment]
Individual mobs can be disabled by changing the config/MutantCreatures.cfg file.
