### ISSUE TITLE
Mutant Creeper and ESM

### ISSUE THREAD

**Issue by CodingManDan** [Haggle1996/RevolutionPack#522]
With the introduction of Epic Sedge Mod I am noticing mobs spawning in our base. The only problem with this are Mutant Creepers which will cause a large amount of damage to a base even if killed.

**Comment by devanchya** [comment]
The creepers are a very rare spawn, how often are they spawning for you?   I've seen 2 in 8 months of regular play

**Comment by Aivech** [comment]
The intended method of spawning the creatures from Mutant Creatures is to throw some mutating splash potion at a normal mob (4 obsidian around a water bottle IIRC). This has a 50/50 chance of killing the mob or mutating it.

This being the case, natural spawns should be very low.

**Comment by CodingManDan** [comment]
We get about 3 mutant spawns every real life day of playing. Creepers I have seen 3 in the first week of upgrading to rev3. I disabled the Mutant Creepers after the 3rd one took a chunk out of our house.

devanchya are you on rev2 still? When we were on rev2 mutant mobs were very rare I think we only saw 2 or 3 in total it wasn't until rev3 that we started getting spammed with mutant mobs.

**Comment by Haggle1996** [comment]
Individual mobs can be disabled. See Haggle1996/RevolutionPack#521 for details.
