### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by IReminder** [Haggle1996/RevolutionPack#525]
There is a Bug with Auto Workbench from BC Factory and Crafting Tweaks you can duplicate your Items with. Simply put Items into the Crafting Grid and then remove them via Crafting Tweaks. You don't use your Items for the Crafting Grid of the Auto Workbench but you always get them back and therefore duplicate them.

http://puu.sh/rctzK/25e2ec6442.jpg

**Comment by Haggle1996** [comment]
Addressed by disabling Crafting Tweaks for the Auto Workbench
