### ISSUE TITLE
Openturrets basic turrets causes metadata loss

### ISSUE THREAD

**Issue by happy2pester** [Haggle1996/RevolutionPack#526]
Simply, when I set up a disposable item turret, if the item i use has metadata, then that metadata is lost when the item is fired. I've tried it out with 6 things from 6 different mods all with the same results.

Thaumcraft Gold coins (4324:18) > Alumentum (4324)

decocraft Gold Ingot Stack (5874:7) > Creeper Plushie (5874)

Bibliocraft Dark Oak Furniture paneler (699:5)> oak furniture paneler (699)

Botania mana powder (4817:23) > Manasteel ingot (4817)

You get the idea, I've tested it with those, but i would guess this applies to everything with metadata.

**Comment by Aivech** [comment]
Resolved because Open Modular Turrets has been removed in 3.2.0.
