### ISSUE TITLE
Several Biome ID conflicts between GalaxySpace and ChromatiCraft

### ISSUE THREAD

**Issue by AshIndigo** [Haggle1996/RevolutionPack#527]
As stated in the title there are various ID conflicts between those 2 mods.'

Here is what I have currently found
- 206 Aura Ocean Biome and MakeMake Biome
- 209 Central Biome (ChromatiCraft Dimension) and Io Biome
- 204 Crystal Forest and Pluto Biome
- 205 Crystal Mountains Biome and Kuiper Belt Biome
- 203 Glowing Forest and Ceres Biome
- 207 Structure Biome (ChromatiCraft Dimension) and Phobos Biome
- 208 Voidland Biome and Deimos Biome

**Comment by Haggle1996** [comment]
Which pack and version are you on?

**Comment by AshIndigo** [comment]
Revolution 3 3.1.1

**Comment by Haggle1996** [comment]
That is concerning. These were shuffled around in the last update to fix
these IDs. Is this an existing map you've had previous to 3.1.1?

**Comment by AshIndigo** [comment]
No it's a fresh map on this version. I did do a temp fix by shifting all afflicted ids in the ChromatiCraft config by 20 which seemed to do the job

**Comment by Haggle1996** [comment]
Fixed in the next update by an update to ChromatiCraft

**Comment by AshIndigo** [comment]
It isnt. With default configs its back to my previous list of conflicts

**Comment by Haggle1996** [comment]
Try reinstalling the pack; I pushed a configuration fix to ChromatiCraft and you may have grabbed the bad version.

**Comment by Haggle1996** [comment]
The CrC biomes should start at 239 if you've got the right config file.

**Comment by Aivech** [comment]
In addition, the game should not be able to start if the ID's are conflicting....

**Comment by Haggle1996** [comment]
It won't start if they're conflicting with biomes in the normal dimension loaders...the Galaxy Space loader doesn't fire up until you visit one of it's worlds, so you don't get the conflict until you've visited one of it's planets. This is why thousands of people can play the pack, but not run into the issue.
