### ISSUE TITLE
Chiseled obsidian has no harvest level

### ISSUE THREAD

**Issue by Aivech** [Haggle1996/RevolutionPack#530]
By using the iron chisel's in-world chisel ability to chisel obsidian, you can obtain obsidian without having diamonds. 

Setting:

```
# If this is true, the iron chisel can left click chisel blocks. If false, it cannot.
B:ironChiselCanLeftClick=true
```

to "false" in the Chisel config will remedy this, as a diamond chisel will then be required to obtain obsidian in this manner.

**Comment by Haggle1996** [comment]
I'll add this in the next update.

**Comment by Haggle1996** [comment]
Changed in the next update.
