### ISSUE TITLE
Techguns Cybernetic Parts Progression Blocking; Fabricator Recipe

### ISSUE THREAD

**Issue by chareon** [Haggle1996/RevolutionPack#531]
It is currently impossible to create the fabricator from the techguns mod as it requires cybernetic parts to create the fabricator housing, but you create cybernetic parts in the fabricator.

**Comment by Haggle1996** [comment]
Odd, I haven't changed any of the recipes. Perhaps its acquired by killing/capturing the world-gen bases?

**Comment by chareon** [comment]
I've done some exploring and haven't found any, but I'll check in with the mod developer and see what they have to say. I wanted to verify that the modpack wasn't making any changes before bugging them about it.

**Comment by aurumvorax** [comment]
According to the mod wiki, cybernetic parts are aquired by killing cyberdeomns in the nether.  I haven't checked this yet, as I keep getting slaughtered in the nether by soldier zombie pigmen.  I'd reccommend changing the spawning rates.

**Comment by Aivech** [comment]
I would also use NEI (or one of its addons) to dump the dungeon loot tables and check those for it.

**Comment by chareon** [comment]
Just verified that they do indeed drop off cyberdemons.
