### ISSUE TITLE
Refinery Confusion

### ISSUE THREAD

**Issue by aurumvorax** [Haggle1996/RevolutionPack#532]
There are apparently 4 types of refinery, buildcraft single block, galacticraft single block, pneumaticraft multiblock stack, and the immersive engineering multiblock. 

Buildcraft refinery tooltip says it is disabled, use the IE refinery instead - recipe present and refinery works for oil -> fuel/gasoline.

Galacticraft refinery tooltip says it is disabled, use the BC Addons multiblock instead.  BC Addons not part of the pack anymore. This recipe is disabled, which makes sense.

Immersive engineering refinery's recipe requires kerosene and oil to produce fuel/gasoline.

pneumaticraft refinery works just fine, and can produce diesel, kerosene, gasoline and LPG.

I know it's just tooltips for the most part, but it's quite confusing.  I guess the intention is to use the pneumaticcraft refinery at first, then combine your kerosene with oil for more fuel?  The diesel and the LPG already have major uses, I guess this is to make a use for kerosene in a larger production chain?

**Comment by Haggle1996** [comment]
Fixed in the next update...by removing Galacticraft (it's replaced with advanced rocketry)
