### ISSUE TITLE
Starter Quests

### ISSUE THREAD

**Issue by Eb-** [Haggle1996/RevolutionPack#533]
I've written a few starter quests that are very similar to the old HQM quests. The rewards may need some tweaking, but the basics are all there.

The first quest is for a spawn dimension/structure, and may need a little editing.
[DefaultQuests.zip](https://github.com/Haggle1996/RevolutionPack/files/531283/DefaultQuests.zip)

**Comment by Haggle1996** [comment]
These are REALLY nice. Thank you for putting them together. I'm including them in the next update.

If there's anything I can do to help you expand these quests, please let me know! I can add you as a collaborator so you can modify the json directly.

I'd love to see a quest for making a Techguns hand cannon in the starter set.

**Comment by Eb-** [comment]
Unless if you have some sort of spawn building planned, I'd recommend removing the "leaving the bunker" quest, else players will have to travel to 0,0 to start doing the rest of the quests.

**Comment by Haggle1996** [comment]
Yar, I saw that. I've been contemplating adding a spawn structure. It's certainly been asked for.
