### ISSUE TITLE
Uncraftable Golemancer's Bell

### ISSUE THREAD

**Issue by Excaerious** [Haggle1996/RevolutionPack#534]
On Revolution 3, the Golemancer's Bell seems to be uncraftable because another Thaumcraft addon (I believe it's Thaumic Exploration) overrides the Golemancer's Bell with one of a null value. If you click on this in NEI you will immediately crash. This obviously renders all Golems unusable since you can't interact with them in any useful way. I attached a screenshot of this behavior.

![golem bell](https://cloud.githubusercontent.com/assets/6412128/19422623/401a6110-93e5-11e6-9900-a458f9f4fc3b.png)

**Comment by Haggle1996** [comment]
Duplicate of #382
