### ISSUE TITLE
Draconium Dust / Ingot recipe inconsitency

### ISSUE THREAD

**Issue by Toperoco** [Haggle1996/RevolutionPack#535]
So the recipe for Draconium Ingots are pretty lategame, the Dust on the other hand can be replicated in the ChromatiCraft Item Fabricator and then smelted into the Ingots. Draconium Ore is disabled, but the ender dragon still drops dust, so it is a lot easier obtainable that way since you can basically get infite from there on. No way anyone would go the route of the Ingot recipe!

**Comment by Haggle1996** [comment]
So what would you like to see changed?

**Comment by chareon** [comment]
If the goal is to prevent Draconium access at mid game then Draconium Dust should be removed from the Dragon's drop table.

**Comment by Toperoco** [comment]
Exactly. Getting free and infinite Draconium after killing the dragon (which I consider early game in this pack) doesn't feel in balance with the progression of the other tech mods.
edit: It might be smarter to disable the Item Fabricator recipe and add a way to grind the Ingots into Dust, since Draconic Evolution has recipes that require the Dust.

**Comment by Haggle1996** [comment]
I've resolved this by removing the Arc Furnace recipe for making dust into ingots. 

Since it's again Reika's terms to disable or change how his mods work, I can't disable the Item Fabricator. However, you will now need to both kill the dragon for the dust and make at least one ingot the hard way.

**Comment by ignitediris** [comment]
So... This has a consequence that might not be intended. I just had a quick conversation with Ptero via IRC and the removal of this recipe breaks the usefulness of another mods ability to give you direct access to the Draconium Ore. I don't want to ruin the method for others but suffice it to say, it is crazy expensive my means of power requirement. As far as I am aware, that method is the only way of getting draconium in mass quantities.

Unless of course, the expensive recipe is the only intended way of getting the ingots. In that case, might I recommend removal of the method I am hinting at?
