### ISSUE TITLE
AE2Cells recipes do not appear in NEI right

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#536]
AE2Cells have been changed to require a block of steel in place of the plate.   They do not appear in NEI properly.  Appears to be a minetweaker order bug.  have not been able to find a trival fix.

**Comment by Aivech** [comment]
The wrong recipe appears in NEI?

**Comment by devanchya** [comment]
None of the AE2Cells appear to show recipes,  when you click on them in the normal manors "nothing" happens which leads me ot think the NEI doesn't see the recipe right.

**Comment by Haggle1996** [comment]
I can't replicate this problem on my machine; all the craftable cells have recipes. The rest are creative-mode only. Perhaps you need to delete your NEI cache from the save folder?
