### ISSUE TITLE
Techguns Ammo Tab missing

### ISSUE THREAD

**Issue by chareon** [Haggle1996/RevolutionPack#537]
The Techguns ammo tab is missing in 3.4.1. It was there in 3.2.0, I can't comment on the versions between.

The tab that should appear but doesn't - https://github.com/pWn3d1337/Techguns/wiki/Techguns-Inventory-Tab

**Comment by Haggle1996** [comment]
I've got this fixed and I'll be pushing the update in the next day or so

**Comment by Haggle1996** [comment]
Fixed in the next update.
