### ISSUE TITLE
harder ores slouice

### ISSUE THREAD

**Issue by woofiegaming34** [Haggle1996/RevolutionPack#539]
the sluice not  working i followed the instructions but its not working for me and the ore dust does not come out and the gravel keeps dispersing when it goes down the slouice

**Comment by Haggle1996** [comment]
The sluice is very dicey -- it's very easy to be in the wrong spot and get no ore. Try visiting http://reasonable-realism.wikia.com/wiki/Prospecting for ideas on how to find ore.
