### ISSUE TITLE
Add Recurrent Complex structures consistent with lore

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#54]
Also remove the fantasy structures from Recurrent Complex.
Also, add a spawn structure using Recurrent Complex which introduces players to the lore.

**Comment by TheMachinator** [comment]
A very good tutorial on making Recurrent Complex structures:

https://www.youtube.com/watch?v=vSudNS55k3M

**Comment by TheMachinator** [comment]
Where is this "lore"?

**Comment by DaMachinator** [comment]
Depending on how long ago the war happened, the structures could be enhanced with a little radiation...

**Comment by Haggle1996** [comment]
Closing this care of @DorrinB. Thank you so much for the hard work!!!!
