### ISSUE TITLE
Melting superconducting wires

### ISSUE THREAD

**Issue by LordOOTFD** [Haggle1996/RevolutionPack#540]
My electricraft system is intermittently melting my superconducting wires. I searched for similar problems and can't seem to find anyone with the exact same issue, the wires might be melting from a fail safe which causes the wires to melt before the network calculation crashes the game, but the system I have set up should not have the complexity to cause that.

The setup I have which is causing the issue is a gas turbine generator fed with ender io fluid conduits connected through a 2:1 diamond torque gearbox to a generator which then connects to about 8 induction motors. most of the motors are connected with relays and resistors for power regulation. I have tried removing the relays and disconnecting various motors in series but can't find the problem.

The wires will also melt if you connect the generator to ANY load immediately after the previous network melted down.

Also replacing the superconducting cables with normal cables does not solve the problem. Any help with this would be great!

**Comment by Haggle1996** [comment]
Did you ask about this on Reika's issue tracker or perhaps his forum?

**Comment by Haggle1996** [comment]
I'm certain these work as there's quite a few on one of my dev servers. If you have further problems with them, report it on Reika's issue tracker.

**Comment by Aivech** [comment]
This is a known issue on Reika's end, see https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1167

It is a temporary workaround for a bigger underlying issue.
