### ISSUE TITLE
Steel ingots craft into libVulpes Steel block

### ISSUE THREAD

**Issue by ArchAngel075** [Haggle1996/RevolutionPack#541]
Steel ingots craft into libVulpes Steel block which does not work in the recipe for steel slab which disables arc furnace (unless creatively 'swapping' the types or using chisels)

**Comment by Aivech** [comment]
What is the result of the command "/mt hand" whilst holding the libVulpes Steel Block?

**Comment by Haggle1996** [comment]
I've already fixed this for the next update. I don't close them until they're released. In the short term, you can put the block in a chisel and change it to the steel you want.
