### ISSUE TITLE
Incorrect Botania recipes.

### ISSUE THREAD

**Issue by Sentrus** [Haggle1996/RevolutionPack#548]
Hello. I'm playing on a REV3 server (3.4.2) and I've got recipe issues no one else on the server seems to have. Here's a few example screenshots: http://imgur.com/a/4QLrJ

My startup log is too large to paste anywhere, but I can zip it up and get it to you somehow if you'd like.

I've tried a clean reinstall of the pack on ATLauncher without any luck. 

I'm not even sure if this is something you can fix, but no one seems to have any ideas and I can't find any information about this.

Thanks for your time.

**Comment by Sentrus** [comment]
Nevermind. I forgot ATLauncher caches the mod downloads. I had a botched download in there somewhere.

**Comment by Haggle1996** [comment]
You have a corrupted NEI cache. Delete the NEI folder from your instances saves folder and then load the pack.

On Tue, Oct 25, 2016 at 3:00 PM -0600, "Sentrus" notifications@github.com wrote:

Hello. I'm playing on a REV3 server (3.4.2) and I've got recipe issues no one else on the server seems to have. Here's a few example screenshots: http://imgur.com/a/4QLrJ

My startup log is too large to paste anywhere, but I can zip it up and get it to you somehow if you'd like.

I've tried a clean reinstall of the pack on ATLauncher without any luck. 

I'm not even sure if this is something you can fix, but no one seems to have any ideas and I can't find any information about this.

Thanks for your time.

**Comment by Sentrus** [comment]
Thanks. Looks like Optifine corrupts NEI. Didn't add Optifine this time and it stayed uncorrupted.

**Comment by Yuri4171** [comment]
It's not an issue with NEI and Optifine, it's Optifine and Reika's sanity checker.  If you set "Attempt to Repair Environment Sanity" and "Check Environment Sanity" in DragonAPI.cfg to true, the issue is "fixed," though I provide no guarantees that doing this will cause no other issues. It's worked for me at least.
