### ISSUE TITLE
Souls are impervious to player damage apart from guns and chainsaws

### ISSUE THREAD

**Issue by AshIndigo** [Haggle1996/RevolutionPack#553]
I am unable to kill a soul with any weapon apart from guns and apparently chainsaws. And if it gets your gun then your done for and can't get your stuff. Even though pylons can bring it to half a heart it wont die.

**Comment by Haggle1996** [comment]
If you're unable to damage it, save/reload or disconnect/reconnect. There's a bug with it occasionally not taking damage except from ranged items (the chainsaw is actually a ranged weapon in code).
