### ISSUE TITLE
Disable Harder Wildlife Lizards

### ISSUE THREAD

**Issue by ghost** [Haggle1996/RevolutionPack#556]
I created a world a 1-2 hours ago and everything was running fine up until 15 min ago when I crashed from doing nothing. I re-launched the pack, loaded the world, and crashed again after a minute.

Crash log: [pastebin](http://pastebin.com/dyb5ZQZY)

Edit: Moving away from a desert prevented further crashes

**Comment by Barhandar** [comment]
Disable lizards in Harder Wildlife's config.

**Comment by Haggle1996** [comment]
Yar, several people have reported this, though I've never once experienced it on any of my dev servers, test server, or SSP testing instances. I'm going to disable the lizards in the next update.

**Comment by romanticjo** [comment]
Booh! we love the lizards.

**Comment by Haggle1996** [comment]
Fixed in next update.
