### ISSUE TITLE
Harder ore prospecting broken

### ISSUE THREAD

**Issue by romanticjo** [Haggle1996/RevolutionPack#557]
Seed: -2712070230249969382
location: [577, 67, -277] is right over an iron vein, and bone meal does not yield any poor joes.

**Comment by Barhandar** [comment]
This might be on Harder Ores's side. It's also my experience that no flowers were bonemealed when I tried to prospect right over a (discovered later) tin motherlode.

**Comment by Haggle1996** [comment]
Several reasons they won't spawn:
- The chunk hasn't been scanned yet (this is the scanning spam you see in the log). This is particularly noticeable in SP, as the game only scans when you're playing, versus MP where chunks are scanned all the time, even when you're not connected.
- The ore is too deep
- RNG and you just got unlucky. Clear the grass in the area and repeat bonemealing.
- You pregenerated the world using a tool that breaks proper chunk generation (Forge Essentials and Bukkit in particular).

Regardless, Reasonable Realism (and therefore, Harder Ores) is no longer supported for 1.7.10, so not much I can do about it.

**Comment by romanticjo** [comment]
most likely culprit: chunk scanning, none of the other conditions are applicable.
