### ISSUE TITLE
Zombies absolutely obliterate underground due to passive griefing targetting natural materials, but never dig to get to players in cover

### ISSUE THREAD

**Issue by Barhandar** [Haggle1996/RevolutionPack#558]
SpecialAI passive griefing is bored (no target) block-breaking, not breaking to get to the target. [This is the result.](http://i.imgur.com/cYSYzyR.png) SAI passive griefing is the same thing as EpicSiegeMod's "general griefable blocks" list. _Not_ "digging blacklist" one.

Please disable SpecialAI's passive griefing of natural blocks ASAP. SpecialAI.cfg, 

```
passive_griefing {
    [...]
    S:target_blocks=
```

This will let zombies continue breaking light sources without destroying underground. Alternately, reset that option to default so they break playermade constructions that are not adequately protected, instead.

**Comment by Haggle1996** [comment]
No, and no.
