### ISSUE TITLE
Server crash, maybe still prob. with burning Rainbowtrees?

### ISSUE THREAD

**Issue by t3rraz** [Haggle1996/RevolutionPack#567]
Here the Crashlog from the Servercrash, with this world we cant Play. At moment it is ok, we startet from a Backup and used a command from the communitiy to prevent this. 

[crash-2016-11-06_10.22.16-server.txt](https://github.com/Haggle1996/RevolutionPack/files/575348/crash-2016-11-06_10.22.16-server.txt)

**Comment by aurumvorax** [comment]
I believe this is no longer an issue, as Reika has fixed this bug
