### ISSUE TITLE
Add more thaumcraft aspects to mobs and plants

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#57]

**Comment by TheMachinator** [comment]
This may help, although the only mod we have installed that it covers is the Twilight Forest:
[Thaumcraft Mob Aspects] (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076360-1-7-x-thaumcraft-addon-thaumcraft-mob-aspects)

**Comment by Haggle1996** [comment]
This was originally a request from a player, which I captured here for further consideration. Yes, the mod would solve the problem, but I'm inclined to leave it out as there's no shortage of aspects in the pack, and this mod would make certain areas of the TC research easier. For example, needing to scan the super zombie that spawns from eerie biomes.
