### ISSUE TITLE
Nothing Registers In-Game

### ISSUE THREAD

**Issue by Supradth** [Haggle1996/RevolutionPack#570]
I can load into the game, slowly. When i enter the game, i can walk around but when i try to chop down a tree or dig up dirt it doesn't drop the items. I tried that pregen but it didn't work. I have a decent computer. if you need my specs let me know.

**Comment by Haggle1996** [comment]
Most likely you don't have enough RAM allocated to your instance. For SP, I recommend 5GB, with 4GB minimum. MP can go down to 3.5 GB

Get Outlook for iOS

On Tue, Nov 8, 2016 at 9:19 AM -0700, "Supradth" notifications@github.com wrote:

I can load into the game, slowly. When i enter the game, i can walk around but when i try to chop down a tree or dig up dirt it doesn't drop the items. I tried that pregen but it didn't work. I have a decent computer. if you need my specs let me know.

**Comment by Supradth** [comment]
ok, so i set my settings to 4096 min and 5120 max, turned all my in game settings as low as i can and it started off ok, but as soon as game started generating chunks, stopped working. Almost like i had a gigantic delay. i have 16gb ram atm. i have an AMD Radeon R9 200 series video card. AMD fx(tm)-6300 six-core processor 3.50 ghz. 64 bit os, windows 10. maybe this helps. i might not have a strong enough computer i guess.

**Comment by Kataiser9** [comment]
While I can't know exactly what your problem is, this does sound like it's likely just chunk gen lag. Worldgen is not fast in this pack; my computer is around the same level as yours, and if I reach the edge of what's already been generated (at least in the overworld) things slow down extremely quickly.

What problems did you have with pregeneration, exactly? 'Cause that's pretty much the best solution there is, I think. You might also find the command "/cofh tps" useful - if it displays your tick time at more than 50 ms, you're going to encounter delays (and if you're generating a lot of chunks at once, it WILL be over that number).

**Comment by Supradth** [comment]
when i tried to type in /pregen spawn 100. nothing happened. at least i think that's what it was, i found it on a google search. i'll check out /cofh tps.

**Comment by Supradth** [comment]
I changed from 4 min 5 max to 6 min 8 max, turned all my video settings down for better performance, and was able to get the /pregenspawn 50 to work. at 4000/10000 (40%) it stopped and saved. Didnt start back up. While doing this i was getting around 12 fps. I saved and exited. I tried to rejoin but it just sent me back to main menu. The log said i was running something like 570k ms behind and 17k ticks were skipped. I exited completely out of mc back to the ATL interface and open back up the Revolution 3 instance.  It works but really laggy. I can handle the lag, to a point. guess i just had to up my ram distribute.

**Comment by Haggle1996** [comment]
You can't really play the game while it's pregenerating, and doing so will likely halt the game. That said, with 5GB of ram, you shouldn't need to pregenerate for single player. If the game is unplayable on a fresh map with 5GB, you may not have a powerful enough computer or something else is wrong.

Get Outlook for iOS

On Wed, Nov 9, 2016 at 2:28 PM -0700, "Supradth" notifications@github.com wrote:

I changed from 4 min 5 max to 6 min 8 max, turned all my video settings down for better performance, and was able to get the /pregenspawn 50 to work. at 4000/10000 (40%) it stopped and saved. Didnt start back up. While doing this i was getting around 12 fps. I saved and exited. I tried to rejoin but it just sent me back to main menu. The log said i was running something like 570k ms behind and 17k ticks were skipped. I exited completely out of mc back to the ATL interface and open back up the Revolution 3 instance.  It works but really laggy. I can handle the lag, to a point. guess i just had to up my ram distribute.
