### ISSUE TITLE
[1.4.4] Quest "A Simple Firearm" not completable

### ISSUE THREAD

**Issue by Shuro** [Haggle1996/RevolutionPack#578]
The Quest states to craft a Hand Cannon which is loaded, but the receipt only gives you an empty Hand Cannon. 

I fixed the Quest here: #577

**Comment by TheEndermage220** [comment]
I know it states fixed, but I'm currently having this issue still.

**Comment by Haggle1996** [comment]
I neglected to merge the fix. This will be fixed in the next update.
