### ISSUE TITLE
Update Harder Ores to 15.26.1c.jar

### ISSUE THREAD

**Issue by Eb-** [Haggle1996/RevolutionPack#579]
More of a suggestion.

15.25.1c adds a flag to disable chunk re-scanning. Super useful for server admins who have large pre-generated worlds such as myself.

**Comment by Eb-** [comment]
Requesting this gets expedited in an update. I have a server launch on the 18th which requires this mod update, and would like my players to be able to quickly grab the client and play.

**Comment by HoneyMomo** [comment]
I'm just manually downloading it and going to plop it and swap it with my Revolution|3 files.

**Comment by Haggle1996** [comment]
Done.
