### ISSUE TITLE
Consistent Ore Re scanning, Never Stops.

### ISSUE THREAD

**Issue by HoneyMomo** [Haggle1996/RevolutionPack#581]
Greetings!

I've been having a memory leak problem with my modded server recently, and I'm no expert in finding memory leaks, but I did notice the only thing that was always show up in my debut log was the following:

20:00:52  [Info] [HarderOres]: 254 chunks remain to be rescanned for ores.
20:01:52  [Info] [HarderOres]: 221 chunks remain to be rescanned for ores.
20:02:52  [Info] [HarderOres]: 206 chunks remain to be rescanned for ores.
20:03:52  [Info] [HarderOres]: 215 chunks remain to be rescanned for ores.
20:04:52  [Info] [HarderOres]: 212 chunks remain to be rescanned for ores.
20:05:52  [Info] [HarderOres]: 200 chunks remain to be rescanned for ores.
20:06:52  [Info] [HarderOres]: 215 chunks remain to be rescanned for ores.
20:07:52  [Info] [HarderOres]: 212 chunks remain to be rescanned for ores.
20:08:52  [Info] [HarderOres]: 200 chunks remain to be rescanned for ores.
20:09:52  [Info] [HarderOres]: 215 chunks remain to be rescanned for ores.

This is only a small chunk, but it does it with nobody on the server, and does it with people on the server. My server crashes after about an hour due to a kind of memory leak, and I'm unsure if this would have any effect on the problem.  

Thanks! Sorry if this is unrelated or normal. I tried to google it and search as many ways as possible before coming here.

**Comment by HoneyMomo** [comment]
Update: I increased my RAM to deal with the memory leak a little better. However, i'm not sure what happened last night while nobody was on.

04:06:29  [Info] **[HarderOres]: 1438 chunks remain to be rescanned for ores.**
04:07:12  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 27040ms behind, skipping 540 tick(s)
04:07:17  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 4797ms behind, skipping 95 tick(s)
04:08:00  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 27444ms behind, skipping 548 tick(s)
04:08:05  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 4746ms behind, skipping 94 tick(s)
04:08:48  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 27091ms behind, skipping 541 tick(s)
04:08:52  [Info] **[HarderOres]: 1438 chunks remain to be rescanned for ores.**
04:08:53  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 4838ms behind, skipping 96 tick(s)
04:09:38  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 27984ms behind, skipping 559 tick(s)
04:09:43  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 4840ms behind, skipping 96 tick(s)
04:10:26  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 27558ms behind, skipping 551 tick(s)
04:10:31  [Warn] Can't keep up! Did the system time change, or is the server overloaded? Running 4786ms behind, skipping 95 tick(s)

**Comment by Eb-** [comment]
This is a known problem with HarderOres, as of right now, there's no fix, only a workaround. The workaround requires Harderores 15.26.1c, and for chunk rescanning to be disabled in the config. I have put in a request for Rev|3 to package the latest HarderOres (https://github.com/Haggle1996/RevolutionPack/issues/579).

Please note, disabling chunk rescanning will make it so sluices will not work in any unscanned chunks! Disable at your own risk.

**Comment by Haggle1996** [comment]
The latest Harder Ores is included in 3.5.0; however, I don't think the chunk rescanning is related to your issue.
