### ISSUE TITLE
Advanced Rocketry Space Station Visuals Broken

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#589]
When in an Advanced Rocketry Space Station, the sky is completely black with no stars visible except for the sun.  The planet being orbited is likewise not visible.  Using the warp drive to switch planets does not resolve the visual issue.

**Comment by Kataiser9** [comment]
Not sure this pack is still being maintained, but I did some digging on this and found a fix. It's Dynamic Surroundings causing it. You can remove the mod, or make the following config changes.

In config\dsurround\dsurround.cfg, put this in the "dimensions" section:

`dimensions {

    # Configuration files for configuring Dimension Registry [default: ]

    S:"Config Files" <

	AdvancedRocketry.json

     >

}`

Then make a new file in the same folder called AdvancedRocketry.json, with these contents:

`{

    "entries":[

        {

	    "dimId":-200,

	    "weather":false,

	    "haze":false,

	    "aurora":false,

	    "seaLevel":0

	}

    ]

}`

Not totally sure I remember the default dimension ID of the space station right, but I THINK it's -200. You can check easily in the Advanced Rocketry config.

**Comment by Haggle1996** [comment]
Has this been addressed in 3.5.0?

**Comment by Haggle1996** [comment]
Try this again in the next update. Lots of updates to Advanced Rocketry
