### ISSUE TITLE
Pleaze Help 

### ISSUE THREAD

**Issue by Gamerthekid** [Haggle1996/RevolutionPack#590]
I have a problem, every time I start Revolutions 3 it starts but before the menu can come up it crashes.
below is my log

http://paste.atlauncher.com/view/372ef141

**Comment by metnavman** [comment]
Update your video drivers and Java

**Comment by Gamerthekid** [comment]
Thank you very much.

**Comment by Gamerthekid** [comment]
helped a lot.
