### ISSUE TITLE
Modular Power Suit Armor issues

### ISSUE THREAD

**Issue by Kannei** [Haggle1996/RevolutionPack#592]
Looks to be a simple fix being to change the config of the mps on the jetpack to anything but 0.0 on base energy use
These is set to 0.0 and that is likely preventing the jetpack form functioning. 
D:"Jetpack.Jetpack Energy Consumption.base"=0.0
D:"Jetpack.Jetpack Thrust.base"=0.0
machinemuse->Powersuits

I changed them and tested in singleplayer and it works there. (not working on the dev server Gwydion is running).

**Comment by Kannei** [comment]
update: An updated version of the mod is tested, and jetpack now works even with the 0.0 configs.
But - now from modules alreaddy added, armor values sems to have 0 effect and settings and modules cannot be changed. any module settings changed, pops back to what it was after its changed. And the jetpack acts a litlte strange, not constantly working. Conclution: The mod is useless as it is curnelty in the pack.

**Comment by Haggle1996** [comment]
pWn3d1337/Techguns#32

**Comment by pWn3d1337** [comment]
I don't think this has something to do with Techguns, the referenced error is a minig speed problem. So techguns mining speed boni migh override powersuits minig speed.

**Comment by Haggle1996** [comment]
This _should_ be fixed with the next update.
