### ISSUE TITLE
Suggestion - Why remove the ability to break spawners from the bedrock pick?

### ISSUE THREAD

**Issue by dieselfuelonly** [Haggle1996/RevolutionPack#602]
Can't wrap my head around this config change for the pack - by the time you have the infrastructure to bore bedrock and make a bedrock pick, you will have already been well through the tech and tools to build a silk touch boring machine and grab the spawners you need.  Why remove the ability to harvest them in a RoC-usable fashion with the bedrock pick?  Seems like more of an annoyance than a reasonable nerf.

**Comment by Haggle1996** [comment]
Generally, I favor making players build more infrastructure whenever possible. In the case of the bedrock pick, which is one of the first bedrock tools to make, I felt it gave players too much freedom without having to build infrastructure. So at least making them get a silk touch boring machine and move it around reduces that. If I could nerf the boring machines, I would do that too.
