### ISSUE TITLE
Chromaticraft Far Lands issues

### ISSUE THREAD

**Issue by metnavman** [Haggle1996/RevolutionPack#604]
Hey all!

I wanted to ask a question and see if anyone else who's progressed this far has dealt with the same issue/found a work-around.

Rev3 version 3.4.4

There appears to be a serious issue with reliably getting out to the Far Lands of CrC, once you've progressed to that stage of the mod. I know that actually seeing the Lumen Streams is a problem that's solved for this pack by turning off Culling Tweaks in Fastcraft. This is a serious performance hit for the modpack, but something that is likely required. That said, take a look at the following that I've already posted over on Reika's end.

[1332](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1332)

If anyone else is having the issue I describe at Reika's github (not Fastcraft culling), and has figured out a way around it, I'd love to hear about it. Thanks!

**Comment by AshIndigo** [comment]
DieselFuelOnly found a fix for it #598 it just needs to added to the main pack

**Comment by metnavman** [comment]
Not only is that not the issue being discussed, I specifically mentioned what that particular thread was talking about and had already done that.

**Comment by AshIndigo** [comment]
This is technically a duplicate issue then

**Comment by metnavman** [comment]
Okay, I was nice before. 

Did you even read the post I made and the link I put? What I'm asking/talking about has NOTHING to do with the ability to see the Lumen Streams or Fastcraft. If you're not going to take the time to comprehend what the thread is about, go away.

**Comment by AshIndigo** [comment]
OK fine I'll admit that I didn't read the issue on Reikas tracker because you ramble about the culling tweaks issue then just post a "By the way look at this" These aren't correlated at all. A better way of writing this would be restating your issue here instead of repeating the fast craft issue then telling people to go to another issue to actually know your problem

**Comment by metnavman** [comment]
They seem correlated enough that you mentioned it without even reading what I wrote, which is why I wrote that it _wasn't related_ and to _read the linked issue_. There's no reason to repeat my issue here, as it's not an issue with Revolution|3, but rather an issue on Reika's end. I merely wished to know if anyone else was experiencing the issue I described on Reika's github. I've edited the original post to further clarify, as it was apparently needed.

This whole thing is moot anyways, having already been almost 2 weeks ago. I simply teleported with Journeymap out to where the Far Lands typically start spawning and bypassed the Lumen Stream issue. It's apparently known by Reika and Co. so hopefully V17 does something about it, provided they figure out the source of the problem.

**Comment by AshIndigo** [comment]
Alright reread the edited version, looks good. That said hopefully v17a adds a fix for it in the near future.

**Comment by Kannei** [comment]
I have also noticed the issue of terrain failing to loade after exiting a sky river, it seems to sometimes work to then log out and logg in again. Even thou from what is written in the original issues post that didnt always help for some. But I havent had issues with none of very few sky rivers  yet when i have been looking for them.

**Comment by Gamerthekid** [comment]
you guy's crack me up

**Comment by Gamerthekid** [comment]
O and that whole sky river terrain load issue your talking about is just because of how the developer of this mod pack has made the chunks load, as their needs to be a limit or their would be unbelievable lag, Haggle1996 talks about this in one of the post made someone with a similar issue. He (I think he) says that it will be fixed in the next update.
