### ISSUE TITLE
A fatal error has occured, this connection is terminated

### ISSUE THREAD

**Issue by glaceogen** [Haggle1996/RevolutionPack#605]
A friend of mine started a server with Revolution 3 and every time I try to get on I get disconnected with the message ''A fatal error has occured, this connection is terminated''.

Log: [http://paste.atlauncher.com/view/d6718dbb](url)

**Comment by metnavman** [comment]
Your link doesn't work.

**Comment by Haggle1996** [comment]
It works if you copy the text, not the link. 

There's multiple mismatched mod errors. One or both of you need to reinstall the pack.
