### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by Notero** [Haggle1996/RevolutionPack#607]
http://pastebin.com/gpbmiSiU

here is the crash report i couldnt fix it pls help me

**Comment by metnavman** [comment]
Caused by: Reika.DragonAPI.Exception.InstallationException: ElectriCraft was not installed correctly

Start by re-installing that.

**Comment by Haggle1996** [comment]
Without the full crash report, I couldn't tell you exactly what is wrong -- but yes, that installation is not correct. Try reinstalling the pack.
