### ISSUE TITLE
Crash when exploring new chunks

### ISSUE THREAD

**Issue by Turmfalke2** [Haggle1996/RevolutionPack#608]
hi,
My game frequently crashes when exploring new chunks.

https://paste.pound-python.org/show/sPLZabvP3MdAOPplsy0d/

**Comment by metnavman** [comment]
You should do a permgen on a new world to help with that. There's a LOT that spawns and this helps.

http://revolutionpack.info/article/rev3-first-day/

Pregenerating a World, towards the bottom

**Comment by Haggle1996** [comment]
As metnavman said, pregenerating your world will help address these issues, particularly on slower machines. Concurrent Modification Issues do happen on occasion -- it's safe to reload and keep going. It just means two mods tried to modify the same blocks at the same time.
