### ISSUE TITLE
[Server thread/ERROR] [enviromine]: Physics updates are taking too long!

### ISSUE THREAD

**Issue by Turmfalke2** [Haggle1996/RevolutionPack#609]
hi,
I have a fairly powerful pc here, but with the enviromine physics enabled (as is the default in this modpack) the game freezes every minute or so for a few seconds. Also while it was still enabled it would constantly demolish normal worldgen structures.

I had to disable the physics to get the modpack in an playable state.

**Comment by metnavman** [comment]
Enviromine is pretty garbage for that. Permgen from your other issue I responded to will help with this immensely when you start a new world. Or, just disable the physics in the Enviromine config.

**Comment by Aivech** [comment]
On another note, the worldgen structures are supposed to be unstable.

**Comment by Haggle1996** [comment]
The message you're seeing in the log occurs because I have Enviromine world updates throttled down really low to prevent serious lag. Enviromine will only process 100 blocks per tick, and if there's more to process, it will spit this message out and then process the missed ones next cycle.
