### ISSUE TITLE
Mob spawning is completely ridicouls 

### ISSUE THREAD

**Issue by Turmfalke2** [Haggle1996/RevolutionPack#610]
Right after spawning in a new world I directly get assaulted by several zombies with SMGs. This pretty much sets the tone for the rest of the game. What is the point in making swords or bows if half the zombies spawn with ranged firearms? Even when I am using the starting pistol I am constantly in situations were the enemies spawn faster than I can shoot them. Without there being any spawners I can destroy. They just spawn in thin air a few blocks above the surface and start shooting you. 

Also given that in the early game you can't regenerate without being hungry I find my self permanently holding down space bar. Is that the vision you had for the modpack? That the player is permanently jumping while an infinite amount of zombies shoot at him?

**Comment by metnavman** [comment]
This isn't a bug. You should hide at night and get away from open caves.

**Comment by thetrav** [comment]
I switched to peaceful mode.  
The killer for me is that most of the ranged enemies that spawn overnight don't go away during the day.  Far too brutal

**Comment by Haggle1996** [comment]
Just due to the spawn mechanics, I highly recommend players do not build within the area around the world spawn. Minecraft keeps a 20x20 area permanently chunk loaded, which means the difficulty is always climbing and mobs don't have a chance to reset on chunk unload.

**Comment by Gamerthekid** [comment]
That is fucking hilarious.

**Comment by Gamerthekid** [comment]
sorry
but 
really that is to funny
