### ISSUE TITLE
HarderOres is constantly rescanning chunks

### ISSUE THREAD

**Issue by Turmfalke2** [Haggle1996/RevolutionPack#611]
hi,
HarderOres constantly prints that there are ~15000 chunks to be rescanned. This numbers never seems to go down. This number never seems to go down and only grows as I explore more of the world. Is this the intended behaviour? I can't imagine constantly scanning 15000 chunks to be great for the overall performance of the modpack.

**Comment by metnavman** [comment]
Pregen your world.

http://revolutionpack.info/article/rev3-first-day/

**Comment by Haggle1996** [comment]
There's a config option to disable rescanning chunks, but this is actually useful. It's just spammy in your log, it's not the culprit for performance.
