### ISSUE TITLE
MCA.zs is defective 

### ISSUE THREAD

**Issue by Turmfalke2** [Haggle1996/RevolutionPack#612]
hi,
When ever I start the game I get a my chat flooded with messages about not finding GoldDust in MCA.zs

http://pastebin.com/WsHcxbC0

**Comment by metnavman** [comment]
If you're using version 3.5, that makes me think this is probably an issue related to #595 
I wonder if the new version re-broke that.

**Comment by Haggle1996** [comment]
I can't replicate this. Try reinstalling your pack and make sure you're on the latest version.
