### ISSUE TITLE
Better Questing 2 progress restart on minecraft reboot.

### ISSUE THREAD

**Issue by Blazingi** [Haggle1996/RevolutionPack#614]
Hi, i'm losing quest progress every time i restart MC and also getting starter eq. I can bypass quest bug by creating a party and then joining it. Then my previous 'session' is displayed as random string of letters and numbers, so it doesn't save players name correctly. Thanks for any help.

E: It works fine on server, but not on SSP

**Comment by Gamerthekid** [comment]
This is most likely caused by the fact that your MC is not saving properly. if you send me the logs I can figure out what is wrong. Or send them to the ATlancher help website.
