### ISSUE TITLE
Lootable bodies disappearing

### ISSUE THREAD

**Issue by dieselfuelonly** [Haggle1996/RevolutionPack#615]
Lootable bodies is just way too buggy... more often than not it seems that what you die your body cannot be found.  Somtimes it seems they can be found in nearby tunnels or caves and other times its impossible.

**Comment by Haggle1996** [comment]
If you can't stand to lose your stuff ever, turn on the /gamerule keepInventory. Sheesh! There is no perfect death chest mod!
