### ISSUE TITLE
General Minecraft Issue but Using Revolution 3.4.4

### ISSUE THREAD

**Issue by Trellinane** [Haggle1996/RevolutionPack#622]
My question is general in nature.  Sorry in advance if this is not a good place to post this.

I have an i7 920 with an NVIDIA GeForce GT 610 and 24 GB ram.
Using Java 8 64 bit and Windows 8.1 64 bit.

I typically start out with over 60 to 90 fps.  However, I always have an issue in late game of minecraft lagging out to less than 5fps.  I have tried over and over to be more efficient in how I build, what I build and where I build and it still ends up in the same place.  Admittedly, I have a large ME system, multiple processing stations, etc.  It also usually happens when I get the Tokamac Reactor as well but it happens sometimes without this being built so I cant say this is the exclusive cause.  Any ideas what is the issue with why I can never enjoy late game minecraft?  Please help.

I post this here simply because Revolution 3.4.4 is the latest thing I have been playing and because I have really enjoyed it and want to continue further with it.  In addition, the Rev community has always been extremely helpful.  Thank you.

**Comment by metnavman** [comment]
There is any number of reasons that could be causing this. 

The Fusion Reactor is a large culprit, if you do not ensure that every inch of it is chunk-loaded. You'll have Neutron entities piling up and causing insane lag if you're not in range to keep the whole thing loaded. I had this exact issue with mine, and had to overlap some chunk-loading. 

I'm currently in an ongoing conversation regarding Neutrons and whether or not they are being completely absorbed by the Fusion Reactor absorbers. You'd be helpful to that if you'd put on some glasses to check for radiation and see if you've got places around your reactor that are getting irradiated. There's conflicting reports on if they're being 100% absorbed. Escaping Neutrons that go into chunks that aren't loaded contribute to lag, and if you see irradiated areas around your Fusion Reactor that's got Absorbers surrounding it, that points to Neutron escape.

Your computer is solid, so if you're building smartly, spreading out over multiple chunks/dimensions and not loading down a couple chunks with a bunch of stuff to process, I'd start with the Fusion Reactor.

**Comment by Haggle1996** [comment]
Try these settings for your graphics: http://i.imgur.com/f6Nu5nr.png
