### ISSUE TITLE
Armor turned to dirt blocks, all items switched around then they deleted themselves...

### ISSUE THREAD

**Issue by gavin1hey** [Haggle1996/RevolutionPack#626]
I was tabbed out to look something up and when i tabbed back in all the missing spaces in my inventory were dirt and my armor including the traveler's gear were dirt blocks. Then after a few seconds of trying to figure out what happened and fixing my inventory my stuff started to disappear one by one. When my friends were able to get on a few of their items did the same thing but no quite the exact same. We are sort of early in the game so no real big things yet but like two minutes into a diamond block appeared in my inventory then disappeared. About 10 seconds later it appeared in someone else s inventory and did that for a bit. After that stopped my items then again got deleted and armor moved around. This time a few of my items would appear back for a few seconds then leave again.. Anyone have any clue as to whats happening or how to fix this because Ive lost a lot of items when it initially happened and now i cant progress without something like this occurring again...

**Comment by Gamerthekid** [comment]
Dude are you in a server or playing on LAN

**Comment by Gamerthekid** [comment]
Because if you are then someone is acting as an admin and is hard core
fucking with you.

**Comment by Aivech** [comment]
Closing this issue unless someone else can replicate it as it sounds like a server administrator playing pranks.

**Comment by gavin1hey** [comment]
I was in a lan with no cheats turned on

**Comment by Gamerthekid** [comment]
Ya but if that person puts themselves as an admin then it really does not
matter if you have cheats on or off. This is because if this person was an
admin on your server (I am assuming it is your server of course) They would
have "permission" to turn cheats on, for them self or the entire server.
