### ISSUE TITLE
Remove Sand from SpecialAI passive griefing list

### ISSUE THREAD

**Issue by Sekkys** [Haggle1996/RevolutionPack#633]
Similar to the tweak that removed grass from the list, I'd like to propose sand be removed as well for the same reason. After a day or two on a server, deserts aren't even deserts anymore, it ends up being worse than grass and the holey ground since sand has physics and ends up creating *giant* holes when the zombies dig it up.

EDIT : I have no idea why it double posted this

**Comment by Haggle1996** [comment]
Passive griefing is now turned off in the next update.
