### ISSUE TITLE
Pack freezes upon launch

### ISSUE THREAD

**Issue by MemeMachine1234** [Haggle1996/RevolutionPack#642]
Can't get past the screen telling about news. The game just freezes up. Occasionally I've been able to get to a screen that tells me "Out of Memory" but it freezes there, too.

**Comment by Haggle1996** [comment]
Sounds like you need to increase the memory allocated to Minecraft in your AT Launcher settings. Try setting it to 4GB or greater (ignore the warning about going over 4GB).

**Comment by Aivech** [comment]
Note that said warning is still valid **for _other_ packs.**

**Comment by DragGon7601** [comment]
Could also be downloading the chromaticraft music files... It only does this once, bit it can take some time if you have a slower connection. There is 9 music files taking up a total of 109 MBs for it to download currently. Each time you load the game it will try to download 1-2 of them until you have them all.
