### ISSUE TITLE
Chromaticraft related: crash when I try to connect on my singleplayer rev3 world 

### ISSUE THREAD

**Issue by tapetonpseudo** [Haggle1996/RevolutionPack#643]
(Not a native english speaker, first time on github)

It's been a while since I've made my rev|3 world. I recently started to use the crystal repeaters in chromaticraft. But now my MC crash everytime I load my world.

https://pastebin.com/eDLksPaU

**Comment by Haggle1996** [comment]
Looks like a save file corruption. You should restore from a previous backup.
________________________________

**Comment by tapetonpseudo** [comment]
I will try, thanks.
