### ISSUE TITLE
FOV zooms in very far when multiple speed boosts present

### ISSUE THREAD

**Issue by erplsf** [Haggle1996/RevolutionPack#647]
I'm running 3.7 without modifications on local server.

When I have Speed III buff from CC and Advanced Combat Armor from Techguns equipped, my FOV zooms in very far. Changing config line
`B:"Ignore speed boosts for field of view"=true` to false in Numina config (core Modular Power Suits mod) located at config/machinemuse/Numina.cfg, fixes it.

Someone in chat suggested that it was changed in new version?

**Comment by Aivech** [comment]
This I believe is vanilla behavior - if you give yourself a high enough level of Speed buff in vanilla with commands, the same thing should happen. If the Numina config fixes it, I'd go with that.
