### ISSUE TITLE
[cross-mod interaction / Bug] RF Transfer Cables not connecting

### ISSUE THREAD

**Issue by xzereha** [Haggle1996/RevolutionPack#648]
The RF Transfer Cables from Electricraft doesn't connect with other mods that use RF (tested with AE2, Ender IO and OpenComputers). The pipes do transfer power, this can easily be tested by putting a Ender IO conduit on the Cable since it connects to other Cables fine.

On all tests I have tried setting the RF Cable to many different throughput values, both higher, lower and the same as the IO for the CapacitorBank

Steps to reproduce
Put Electricraft RF battery
Cable from Battery to Capacitor Bank = No RF/t
Insert a conduit between the final cable and the Capacitor Bank = RF (equivalent to the conduits flow assuming the EC cable is set to the same or higher throughput)

![2017-05-28_06 11 44](https://cloud.githubusercontent.com/assets/5268435/26526068/68a31c70-436d-11e7-9d9a-7acc01a99c4a.png)

**Comment by Haggle1996** [comment]
Report this on Reika's tracker. There's nothing I can do about this.
