### ISSUE TITLE
Eldritch Revolution - Server Crash Help

### ISSUE THREAD

**Issue by Jterrana12** [Haggle1996/RevolutionPack#652]
So I started a server with some friends. After playing for about 30-45 minutes, each time the server crashes. I cannot figure out why it keeps crashing. The server pack is Eldritch Revolution and I downloaded it from it ATLauncher. Below is the crash report. I hope someone is able to help and let me know why it crashed.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.8.9-1.3.2.jar)
  CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  LoadingPlugin (FastLeaveDecay-1.2.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar)
  ProgressionTransformer (Progression-1.8.9-0.6.9.jar)
  DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  FMLPlugin (InventoryTweaks-1.60-40.jar)
  TrashSlot (trashslot-mc1.8.9-2.0.11.jar)
  IvToolkit (IvToolkit-1.2.6.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2 (1).jar)
  FarseekCoreMod (Farseek-1.8.9-1.0.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 6/27/17 9:07 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:259)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:713)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 498227064 bytes (475 MB) / 2594701312 bytes (2474 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 2 total; -Xmx8G -XX:MaxPermSize=256M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
	FML: MCP 9.19 Powered by Forge 11.15.1.1902 101 mods loaded, 101 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9-universal.jar) 
	UCHIJAAAA	ivtoolkit{1.2.6} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.8-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.8.9-alpha-0.0.2.jar) 
	UCHIJAAAA	mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
	UCHIJAAAA	tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.8-32} [Immersive Engineering] (ImmersiveEngineering-0.8-32.jar) 
	UCHIJAAAA	Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
	UCHIJAAAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAAAA	intangible{0.0.25} [Intangible] (intangible-1.8.9-0.0.25.jar) 
	UCHIJAAAA	JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3-pre-1} [AbyssalCraft] (AbyssalCraft-1.8.9-1.9.3-pre-1.jar) 
	UCHIJAAAA	acheads{1.3.0} [AbyssalCraft Heads] (AbyssalCraft Heads-1.8.9-1.3.0.jar) 
	UCHIJAAAA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJAAAA	acintegration{1.4.5} [AbyssalCraft Integration] (AbyssalCraft Integration-1.8.9-1.4.5.jar) 
	UCHIJAAAA	AppleCore{1.3.2} [AppleCore] (AppleCore-mc1.8.9-1.3.2.jar) 
	UCHIJAAAA	aura{592} [Aura Cascade] (AuraCascade-592.jar) 
	UCHIJAAAA	basemetals{1.8.0} [Base Metals] (BaseMetals_1.8.9-1.8.0.jar) 
	UCHIJAAAA	BiblioCraft{2.0.1} [BiblioCraft] (BiblioCraft[v2.0.1][MC1.8.9].jar) 
	UCHIJAAAA	guideapi{1.8.9-2.0.0-28} [Guide-API] (Guide-API-1.8.9-2.0.0-28.jar) 
	UCHIJAAAA	BloodMagic{1.8.9-2.0.0-20} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-20.jar) 
	UCHIJAAAA	Botania{r1.8-299} [Botania] (Botania-unofficial.r1.8-299.jar) 
	UCHIJAAAA	BuildCraft|Core{7.2.7} [BuildCraft] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.2.7} [BC Silicon] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.2.7} [BC Transport] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.2.7} [BC Builders] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.2.7} [BC Energy] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.2.7} [BC Robotics] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.2.7} [BC Factory] (buildcraft-7.2.7.jar) 
	UCHIJAAAA	IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.2.1} [BuildCraft Compat] (buildcraft-compat-7.2.1.jar) 
	UCHIJAAAA	Chameleon{1.8.9-1.1.5} [Chameleon] (Chameleon-1.8.9-1.1.5.jar) 
	UCHIJAAAA	ChestTransporter{2.2.1} [Chest Transporter] (ChestTransporter-2.2.1-MC1.8.9.jar) 
	UCHIJAAAA	chiselsandbits{8.12} [Chisels & Bits] (chiselsandbits-8.12.jar) 
	UCHIJAAAA	cookingforblockheads{2.0.2} [Cooking for Blockheads] (CookingForBlockheads-mc1.8.9-2.0.2.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.8.9-v2c} [CosmeticArmorReworked] (CosmeticArmorReworked-1.8.9-v2c.jar) 
	UCHIJAAAA	craftarcanum2{1.0.0} [Craft Arcanum 2] (CraftArcanum2-1.0.0.jar) 
	UCHIJAAAA	MineTweaker3{3.0.11} [MineTweaker 3] (CraftTweaker-1.8.9-3.0.11.jar) 
	UCHIJAAAA	lootablebodies{1.4.1} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.4.1.jar) 
	UCHIJAAAA	cyclopscore{0.5.7} [Cyclops Core] (CyclopsCore-1.8.9-0.5.7.jar) 
	UCHIJAAAA	ElecCore{1.4.313} [ElecCore] (ElecCore-1.8.9-1.4.313.jar) 
	UCHIJAAAA	deepresonance{1.1.4beta23} [DeepResonance] (deepresonance-1.8.9-1.1.4beta23.jar) 
	UCHIJAAAA	dldungeonsjdg{1.8.10} [Doomlike Dungeons] (DoomlikeDungeons-1.8.10-MC1.8.9.jar) 
	UCHIJAAAA	DummyCore{2.2.189.0.} [DummyCore] (DummyCore-2.2.189.0.jar) 
	UCHIJAAAA	enchiridion{3.1.4} [Enchiridion] (Enchiridion-1.8.9-3.1.4.jar) 
	UCHIJAAAA	enderthing{0.6.8} [Enderthing] (enderthing-1.8.9-0.6.8.jar) 
	UCHIJAAAA	EnderZoo{1.8.9-1.1.5.37} [Ender Zoo] (EnderZoo-1.8.9-1.1.5.37.jar) 
	UCHIJAAAA	evilcraft{0.9.8} [EvilCraft] (EvilCraft-1.8.9-0.9.8.jar) 
	UCHIJAAAA	Farseek{1.8.9-1.0} [Farseek] (Farseek-1.8.9-1.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-1.2.jar) 
	UCHIJAAAA	FloodLights{1.2.5-142} [Flood Lights] (FloodLights-1.8.9-1.2.5-142.jar) 
	UCHIJAAAA	grimoireofgaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.8.9-1.3.3.jar) 
	UCHIJAAAA	hardcorewither{1.1.1} [Hardcore Wither] (hardcoreWither-1.8.9-1.1.1-16-universal.jar) 
	UCHIJAAAA	HelpFixer{1.8.9-1.2.12} [HelpFixer] (HelpFixer-1.8.9-1.2.12 (2).jar) 
	UCHIJAAAA	InfernalMobs{1.6.6} [Infernal Mobs] (InfernalMobs-1.8.8.jar) 
	UCHIJAAAA	inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
	UCHIJAAAA	ironbackpacks{1.8.9-2.0.5} [Iron Backpacks] (IronBackpacks-1.8.9-2.0.5.jar) 
	UCHIJAAAA	journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar) 
	UCHIJAAAA	jwin{univ_compat_filler} [Just What I Needed] (JWIN_v0.12.0_1.8.9.jar) 
	UCHIJAAAA	minecolonies{1.8.9-0.4.912} [MineColonies] (minecolonies-universal-1.8.9-0.4.912.jar) 
	UCHIJAAAA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJAAAA	moarcarts{2.3.0-34} [MoarCarts] (moarcarts-1.8.9-2.3.0-34.jar) 
	UCHIJAAAA	modernmetals{0.10.0} [Modern Metals] (ModernMetals_1.8.9-0.10.1.jar) 
	UCHIJAAAA	numina{0.5.0-004} [Numina] (Numina-0.5.0-004.jar) 
	UCHIJAAAA	powersuits{0.11.0-7} [MachineMuse's Modular Powersuits] (ModularPowersuits-1.8.9-0.11.0-7.jar) 
	UCHIJAAAA	me{1.3.2.1} [More Enchantments] (MoreEnchantments-1.8-1.3.2.1.jar) 
	UCHIJAAAA	AencEx{0.0.1} [AencEx] (MoreEnchantments-1.8-1.3.2.1.jar) 
	UCHIJAAAA	Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
	UCHIJAAAA	nethermetals{1.1.2} [Nether Metals] (NetherMetals_1.8.9-1.1.2.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.8.9-2.1.6.jar) 
	UCHIJAAAA	yurtmod{3.06} [Nomadic Tents] (NomadicTents[1.8.9]-3.06.jar) 
	UCHIJAAAA	potioncore{1.1_for_1.8.9} [Potion Core] (PotionCore-1.1_for_1.8.9.jar) 
	UCHIJAAAA	nep{1.2_for_1.8.9} [Not Enough Potions] (NotEnoughPotions-1.2_for_1.8.9.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.8-rc.1} [OpenComputers] (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar) 
	UCHIJAAAA	progression{0.6.9} [Progression] (Progression-1.8.9-0.6.9.jar) 
	UCHIJAAAA	progressiveautomation{1.6.44} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.44.jar) 
	UCHIJAAAA	progressivemobs{0.4} [Progressive Mobs] (progressivemobs-0.4.jar) 
	UCHIJAAAA	ProjectE{1.8.9-PE1.1.4} [ProjectE] (ProjectE-1.8.9-PE1.1.4.jar) 
	UCHIJAAAA	Psi{beta-23} [Psi] (Psi-beta-23.jar) 
	UCHIJAAAA	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UCHIJAAAA	reccomplex{0.9.7.8.1} [Recurrent Complex] (RecurrentComplex-0.9.7.8.1.jar) 
	UCHIJAAAA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2 (1).jar) 
	UCHIJAAAA	xreliquary{1.8.9-1.3.1.296} [Reliquary] (Reliquary-1.8.9-1.3.1.296.jar) 
	UCHIJAAAA	rftools{4.23beta40} [RFTools] (rftools-1.8.9-4.23beta40.jar) 
	UCHIJAAAA	rftoolsdim{4.22beta32} [RFTools Dimensions] (rftoolsdim-1.8.9-4.22beta32.jar) 
	UCHIJAAAA	runesofwizardry{1.8.9-0.6.0} [Runes of Wizardry] (Runes-of-Wizardry-1.8.9-0.6.0.jar) 
	UCHIJAAAA	runesofwizardry_classics{1.8.9-0.2.1} [Runes of Wizardry - Classic Dusts Pack] (RunesofWizardry-Classics-1.8.9-0.2.1.jar) 
	UCHIJAAAA	SchoolsMagic{1.0} [Schools of Magic] (SchoolsMagic-1.8.9-1.1.jar) 
	UCHIJAAAA	SoulShardsTOW{1.8.9-2.2.8-16} [Soul Shards - The Old Ways] (SoulShards-TOW-1.8.9-2.2.8-16.jar) 
	UCHIJAAAA	stackable_potions{1.0} [Stackable Potions] (StackablePotions-1.8-1.0.jar) 
	UCHIJAAAA	StorageDrawers{1.8.9-2.7.0} [Storage Drawers] (StorageDrawers-1.8.9-2.7.0.jar) 
	UCHIJAAAA	storagenetwork{1.11.1-final} [Storage Network] (StorageNetwork-1.8.9-1.11.1-final.jar) 
	UCHIJAAAA	Talismans 2{2.2.1} [Talismans 2] (Talismans2-1.8.9-2.2.1.jar) 
	UCHIJAAAA	thaumicbases{2.1.189.32} [Thaumic Bases] (ThaumicBases-2.1.189.32.jar) 
	UCHIJAAAA	Torcherino{@VERSION@} [Torcherino] (Torcherino-TehNut-1.8.9-2.2s.jar) 
	UCHIJAAAA	totemic{1.8.9-0.7.5} [Totemic] (Totemic-1.8.9-0.7.5.jar) 
	UCHIJAAAA	trashslot{2.0.11} [TrashSlot] (trashslot-mc1.8.9-2.0.11.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.3.jar) 
	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.8.9-1.3.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
CoreXU2 (extrautils2-1.8.9-alpha-0.0.2.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
LoadingPlugin (FastLeaveDecay-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.8.9-1.6.0.8-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
ProgressionTransformer (Progression-1.8.9-0.6.9.jar)
  joshie.progression.asm.ProgressionTransformer
DCLoadingPlugin (DummyCore-2.2.189.0.jar)
  DummyCore.ASM.DCASMManager
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
FMLPlugin (InventoryTweaks-1.60-40.jar)
  invtweaks.forge.asm.ContainerTransformer
TrashSlot (trashslot-mc1.8.9-2.0.11.jar)
  net.blay09.mods.trashslot.coremod.MinecraftClassTransformer
IvToolkit (IvToolkit-1.2.6.jar)
  
NowWithRendering (redstonepaste-mc1.8.8-1.7.2 (1).jar)
  net.fybertech.nwr.NowWithRendering
FarseekCoreMod (Farseek-1.8.9-1.0.jar)
  farseek.core.FarseekClassTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''DummyCore'
	Profiler Position: N/A (disabled)
	Player Count: 4 / 20; [EntityPlayerMP['Zepharius'/53769, l='world', x=-545.94, y=49.00, z=508.58], EntityPlayerMP['RoboticKittyMeow'/53576, l='world', x=-687.59, y=62.38, z=447.69], EntityPlayerMP['NoobNewt'/55346, l='world', x=148.81, y=56.00, z=-263.20], EntityPlayerMP['SinisterRouge'/123605, l='world', x=-452.52, y=73.00, z=88.02]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Taraxus** [comment]
You have the wrong pack website. I'd try here:
https://sites.google.com/site/eldritchrevolution/
