### ISSUE TITLE
Suggestion - Make Decocraft optional

### ISSUE THREAD

**Issue by chaos234** [Haggle1996/RevolutionPack#654]
I know that Decocraft adds a few things but from my knowledge with this mod in FTB Inf. Ev. and in Resonant Rise 3 either the server nor the client was able to handle this mod.

TPS spikes at only 4 placed objects and if they are not high enough the client - with BetterFPS/Optifine or even without them - will have FPS lag spike. My badest value with this mod was 5 FPS until I removed them (and this with a GTX 970 ... not rly funny).

Since this knowledge I'll never use this mod again and removing it directly but since it is in the Questing Mod Database I know have to go throw it to reorganize all IDs to prevent any crashes or bugs.

Best way will be to make it optional and remove it from the questing mod so that each player can decide if he wants it in or not.

My state is clear and it is removed compleatly so I hope that it will be moved to the optional section.

**Comment by Aivech** [comment]
Decocraft is present in the custom generated structures, so removing it would probably cause all of those to need to be fixed.

**Comment by Haggle1996** [comment]
@DaMachinator is correct, removing Decocraft would break the world gen structures as well as some quests. Before blaming mods for your problems, try removing OptiFine and setting your graphics settings exactly as pictured [here](http://i.imgur.com/f6Nu5nr.png). Note that not all graphics cards offer Advanced OpenGL, so don't panic if it's missing.

**Comment by chaos234** [comment]
@Haggle1996 Without OF I am not be able to play with more than 40 FPS on a well builded base with machines, fluid tanks and so on. In addition OF has nothing todo with the TPS lag which can/will occour with Decocraft and TPS are not FPS and it's not only me who have had those problems with Decocraft in any modpack.

It is like the same with an Logistics Pipes Network which will also harm the TPS if it's overused, even if they are opaque or not (those pipes are consuming a lot of ms compared to a view into Opis).

**Comment by Haggle1996** [comment]
Ah gotcha! The decocraft issue with lag was addressed some versions ago. Having too many of them will definitely lag FPS, but that's true of any mod, as you pointed out. Decocraft also eats up a lot of memory in comparison to other mods, but outside of the increased memory and lower FPS at some world gen structures, it shouldn't affect your TPS. if you know how to use Opus, you can use its client or server timings to figure out what the worst offenders are. Often there's just one or two bad blocks killing performance, and breaking and replacing them often solves the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chaos234** [comment]
Ok, this is an option with which I can deal :)
