### ISSUE TITLE
Server Crashs around all 1 hour (Clean install)

### ISSUE THREAD

**Issue by t3rraz** [Haggle1996/RevolutionPack#658]
it Crashs every hour +- and i dont know why, its a clean install, any idea ? 

[crash-2017-08-06_14.46.31-server.txt](https://github.com/Haggle1996/RevolutionPack/files/1203061/crash-2017-08-06_14.46.31-server.txt)

**Comment by Haggle1996** [comment]
There's an erroring tile entity at (264,64,-504. Looks like a tech guns flag. Try breaking it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by t3rraz** [comment]
sorry for the bad txt format, haggle, and thanks for answering.

I thinked the same, so i restartet the server without the techgun mod, an then with the mod again, after few hours the same problem. Everytime the Teammate spawns there, the server crashes. At the moment we play without the techgun mod.

-- Block entity being ticked --
Details:
	Name: CampFlagTileEnt // techguns.tileentities.CampFlagTileEnt
	Block type: ID #3020 (tile.BasicMachine // techguns.blocks.machines.BasicMachine)
	Block data value: 7 / 0x7 / 0b0111
	Block location: World: (264,64,-504), Chunk: (at 8,4,8 in 16,-32; contains blocks 256,0,-512 to 271,255,-497), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #3020 (tile.BasicMachine // techguns.blocks.machines.BasicMachine)
	Actual block data value: 7 / 0x7 / 0b0111
