### ISSUE TITLE
Thaumic Horizons resurrection resulted in no gravestone and loss of baubles

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#66]
An infused player body was located in the curative vat from Thaumic Horizons with a bound soul beacon in place.
In the Outer Lands dungeon dimension from Thaumcraft, the Eldritch Construct boss was encountered.  A fully charged gravel gun was used in an attempt to kill the boss.  Instead, the boss was enraged and immediately killed the player in one hit.  The player was wearing enchanted awakened ichorium robes and a number of baubles.
The player was resurrected in the vat without apparent problem.  Upon returning to the death site, there was no gravestone and the player's items were cast about on the floor.  All items except for the baubles were recovered. The previously equipped baubles were not present.

**Comment by Haggle1996** [comment]
Duplicate root cause of Haggle1996/RevolutionPack#15
