### ISSUE TITLE
Unable to log into new server

### ISSUE THREAD

**Issue by RikeSilvermist** [Haggle1996/RevolutionPack#665]
I just made a new server last night for Revolution 3, it is all set up and shows it is online but whenever I try to log into it, I keep getting the error message "A fatal error has occurred, this connection is terminated."

[latest.log.zip](https://github.com/Haggle1996/RevolutionPack/files/2300348/latest.log.zip)

**Comment by Haggle1996** [comment]
I would need the server log to know for certain. I'm guessing you have a mod mismatch. Make sure you pick the same optional mods (I recommend using the 'Select Recommended' set for both client and server). Make sure you didn't select MC Heli.

**Comment by RikeSilvermist** [comment]
I thought I had uploaded the logs. What logs are you needing and I'll see
if I can find them.
