### ISSUE TITLE
Chromaticraft structure recipe not showing

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#69]
At the bottom of the Chromaticraft Book GUI, below the abilities section, there are supposed to be recipes showing the configuration for the various structures such as the casting room/temple/altar, etc.  This section is blank for me despite the fact that I have the knowledge fragment for casting rooms.

![chromic lexicon](https://cloud.githubusercontent.com/assets/13791753/9316923/38ac4972-4506-11e5-87fe-08abbc089348.png)

In the progression tab, I have completed the first, second, and third rows. In the fourth row, I have not completed "more complex crafting" since the casting basin requires a casting room for rune crafting.

**Comment by ReikaKalseki** [comment]
Gui Scale?

**Comment by Pterodactlol** [comment]
GUI scale was set to Auto. Switching to Normal has resolved the issue. Thank you for your assistance

**Comment by ReikaKalseki** [comment]
What...it works best on Auto...
