### ISSUE TITLE
Thaumic Horizons infusions worn off

### ISSUE THREAD

**Issue by Pterodactlol** [Haggle1996/RevolutionPack#70]
I had infused myself with all of the player infusions for Thaumic Horizons and they were working. Now, I have only the invisibility and regeneration abilities, and the invisibility can not be toggled even with the keybindings set appropriately.

**Comment by Haggle1996** [comment]
Just a note to let you know that the Thaumic Infusions author has disappeared and is not responding to any requests on his forum page. While it's very useful to have these logged so that other players are aware, my only options are to pull the mod out entirely, or wait to see if he returns.

**Comment by Haggle1996** [comment]
Should be fixed in 1.2.4.0
