### ISSUE TITLE
RoC BoP Gems not craftable into BoP Gems

### ISSUE THREAD

**Issue by JOBGG** [Haggle1996/RevolutionPack#75]
The Rotarycraft versions of the BoP Gems
* Ruby
* Peridot
* Topaz 
* Tanzanite 
* Malachite 
* Amber 
that result from running silk touched ore through RoC Processing (Grinder/Extractor) have no recipe to craft them into their usable BoP variants.

**Comment by Haggle1996** [comment]
Fixed in next update by adding recipes for RotaryCraft Ruby, Peridot, and Amber gems into Ruby/Peridot/Amber blocks. Topaz, Tanzanite, Malachite do not have RotaryCraft equivalents
