### ISSUE TITLE
Nerf bonemeal

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#77]
Reduce bonemeals affect on crops. Nerf it to the ground!

**Comment by JOBGG** [comment]
Is this your todo list?

**Comment by Haggle1996** [comment]
Both issue tracker and to-do list.

**Comment by DorinnB** [comment]
Crop grow really, really slowly.
Same for sugar cane.

**Comment by Haggle1996** [comment]
Based on current growth rates, I'm going to leave bone meal alone for now.

**Comment by Haggle1996** [comment]
Just a note, in the upcoming 1.2 version, sugar cane is no longer penalized for growing in the wrong biome, and its general growth speed has been improved somewhat.
