### ISSUE TITLE
entire pack not working

### ISSUE THREAD

**Issue by username445** [Haggle1996/RevolutionPack#78]
So I'm on the ATLauncher looking at the new packs and see this pack.  It looks interesting so I decide to see what mods it has.  That is when I see that it has both Hardcore Questing Mode AND Jurassicraft (my favorite mods ever) so I decide to download it.  The download goes smoothly and I'm on the title screen in minutes.  I create a new world, and then I have to wait for at least an HOUR to get into the world, and then it starts not responding.  So I wait some more and after a while, it crashes without letting me do anything.  I have a decent computer, so when something crashes, something must be wrong.  All my other modpacks work perfectly, but this one doesn't work at all!  Can you please fix this? I didn't use any of the optional mods in hopes that it would go fast.

**Comment by Haggle1996** [comment]
Most likely you forgot to change the world type to ATG or Biomes O' Plenty. Mushroom island biomes in the Default world type will hang world generation.

Take a look at the first couple of paragraphs of this article. It will help you get the pack setup correctly.
http://haggle1996.github.io/RevolutionPack/articles/your-first-day/
