### ISSUE TITLE
Unnamed Boss

### ISSUE THREAD

**Issue by LordIconMC** [Haggle1996/RevolutionPack#8]
![2015-04-27_21 13 11](https://cloud.githubusercontent.com/assets/10004239/7362635/cf65875c-ed31-11e4-9e86-030f6743ee00.png)

**Comment by Haggle1996** [comment]
This is the Praetor from Thaumcraft. The %s appears when he's too far away from you (and shows when you get close). The author is working on the next version of Thaumcraft, so probably won't update this since its a cosmetic issue.
