### ISSUE TITLE
Spontaneously closing down

### ISSUE THREAD

**Issue by Bamseoejne** [Haggle1996/RevolutionPack#88]
I've come across a problem where the game just shuts down, whether I'm just mining, fighting of hordes of zombies or something else it doesn't matter.

The good thing is that it saves all progress up to the point where it shuts down.

**Comment by Haggle1996** [comment]
I need more information than this. Log files, crash logs, or the console output. I also need to know what you were doing at the time of the crash. Do you receive any other errors like 'NVIDIA error #8' or something similar? If you're not getting any errors, you may want to look at your operating system error logs.
