### ISSUE TITLE
All other players on server disconnect when Ender IO Dark Steel Armor ability is triggered

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#89]
All players except for the player initiating the action.

SleepyTrousers/EnderIO#2743

**Comment by viperior** [comment]
Just replicated this issue by kicking all other players when I activated my Glider ability for my Dark Plate.

**Comment by Haggle1996** [comment]
Fixed in 1.2.2.0

**Comment by viperior** [comment]
Awesome, thanks. :D
