### ISSUE TITLE
Crafting recepies changed

### ISSUE THREAD

**Issue by pixxul** [Haggle1996/RevolutionPack#90]
Some of the crafting recipes (i.e. quarry or ender quarry) were changed in the last version (1.0.10.0 -> 1.1.0.0). But these recipes were reset to their old "original" version. So for instance, the quarry SHOULD use a Heat Ray Barrel and a Bedrock Pickaxe, but the recipe still shows up for Redstone and a Diamond Pickaxe. When you try to craft it with the original recipe, the quarry shows up, but you can't take it out of the crafting table and it snaps back to the output tile of the crafting table.

**Comment by Haggle1996** [comment]
I've confirmed in a fresh copy of 1.1.0.0 that the old recipes do not show up and I can only craft the quarries using their new recipes. You can try a reinstall of the pack, or better yet, install a fresh instance of Revolution and then copy your savegame over. If you still have the problem, please reopen the ticket.

**Comment by Haggle1996** [comment]
To provide some clarification -- the issue you describe can happen when different versions of the scripts/.zs files exist between the server and client. Your minecraft client uses it's local version to inform NEI, but the server uses it's local version for the actual crafting. Reinstalling one or both of the machines should fix the problem (if you can identify who has the bad config).

**Comment by Haggle1996** [comment]
Another user on the dev server has reported this problem -- and a clean install is not addressing it; however, I cannot reproduce it connecting to the same server.

**Comment by Haggle1996** [comment]
I can reproduce this now.

**Comment by Haggle1996** [comment]
MineTweaker 3 is reverted in 1.1.1.1 in order to address the issue the pack. I will keep an eye on the MineTweaker thread for further resolution. You should be able to craft recipes without problems.
