### ISSUE TITLE
Crash shortly after creating a new world.

### ISSUE THREAD

**Issue by megamadman7** [Haggle1996/RevolutionPack#93]
For some reason, a few minutes after I created a new world the game crashed with this error:
http://pastebin.com/J7Vngf7x

Does anyone know a fix?

**Comment by Haggle1996** [comment]
The AlreadyDecorating error is random based on the seed used. It's not uncommon -- most players get none, and some get 1 to 4 before their world is done generating. It can only happen while the world is generating, so an established world doesn't encounter this error unless you go exploring (and then only rarely). It is harmless, and you should be able to reload the save and keep going without issue, other than the inconvenience.

If you're getting frustrated, you can disable the Farseek and Streams mods, and choose the Biomes O Plenty world type. While you won't get the unique world gen, you'll get a stable world.

Please try reloading the same save; if it instantly crashes again try a different randomly generated seed. If that still doesn't work, let me know and we can dig deeper.

**Comment by megamadman7** [comment]
Thank's for the advice! Loving the pack so far.
