### ISSUE TITLE
Harvestcraft rice can't be planted if Hunger Overhaul is active

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#97]
Usually rice is planted by planting the plant - not the seed - on water. This didn't work and some research indicated that Hunger Overhaul is to blame. I disabled Hunger Overhaul and now rice could be planted. 
Oddly enough, EnderIO's farming station *can* plant rice correctly with HO active. Only manual planting is affected.

**Comment by Haggle1996** [comment]
This issue has been reported repeatedly on HO and Pam's issue trackers. MatrexsVigil/harvestcraft#14

The only workaround for now, besides the EIO method you mentioned, is to plant on Ztones Garden Soil.

**Comment by Haggle1996** [comment]
This is fixed as of pack version 1.2.1.0
