### ISSUE TITLE
Unable to get RotaryCraft Aluminum Powder

### ISSUE THREAD

**Issue by megamadman7** [Haggle1996/RevolutionPack#99]
I seem to have hit a brick wall.  I need the RC aluminum powder(which is NOT oredict compatible)in order to make silicon in the blast furnace.  However, I have searched both NEI, the internet, and this github to find a way to make it and have found nothing.  Is this intentional or a bug?

**Comment by Haggle1996** [comment]
It is not the same as standard aluminum powder. It's a new alloy created in the latest version of RotaryCraft. Look carefully in the RotaryCraft manual to learn how to make it. Since its very new, you may want to try the MCF page for Reika's mods if you're stuck.
